### ISSUE TITLE
error while transposing

### ISSUE THREAD

**Issue by ltosti** [theislab/anndata#104]
Hi there,

I was trying to transpose an adata object and got the following error:

```pytb
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/anaconda3/envs/leiden/lib/python3.6/site-packages/anndata/base.py in transpose(self)
   1531         if sparse.isspmatrix_csr(X):
   1532             return AnnData(X.T.tocsr(), self._var, self._obs, self._uns,
-> 1533                            self._varm.flipped(), self._obsm.flipped(),
   1534                            filename=self.filename, layers=layers, dtype=self.X.dtype.name)
   1535         return AnnData(X.T, self._var, self._obs, self._uns,

AttributeError: 'ArrayView' object has no attribute 'flipped'
```

anndata= 0.6.17

Any idea about how to fix it?

**Comment by falexwolf** [comment]
Ah, damn, you're trying to transpose a view of an AnnData, and that's not implemented right now...

Make it a proper object by calling `.copy()` on it before transposing.

I added a more sensible error message than what you got, which gives you that hint: https://github.com/theislab/anndata/commit/518868cb5362d996cbe4248088492f39d9e5628c

Thanks for reporting!
