### ISSUE TITLE
Unable to slice with non-categorical obs index

### ISSUE THREAD

**Issue by joshua-gould** [theislab/anndata#120]
```
import anndata
import numpy as np
import pandas as pd
adata = anndata.AnnData(X=np.array([[1,2], [1,2], [1,2]]), obs=pd.DataFrame(index=[0,1,2]), var=['a','b'])
subset = adata[:,0]
```

'Don’t call _normalize_index with non-categorical/string names'
AssertionError: Don’t call _normalize_index with non-categorical/string names

**Comment by snyquist2** [comment]
I am getting the same error when attempting to slice with the string var name as well.

```
subset = adata[:,'a']
subset = adata[:,adata.var_names[0]]
subset = adata[:,'0']
```
all throw the same error

**Comment by Koncopd** [comment]
Hi, i will check.

**Comment by falexwolf** [comment]
Thanks, Sergei! The main problem here is that AnnData is in an invalid state and we should have thrown errors in the first place. I'll take care of it.

**Comment by ivirshup** [comment]
Closing this, since it's an unsupported use case.

**Comment by cryptovec** [comment]
what the heck this was a use case in your official tutorial
