### ISSUE TITLE
Ordered categoricals create problems with downstream analysis

### ISSUE THREAD

**Issue by ld2113** [theislab/anndata#122]
I was discussing a seemingly novel behaviour of anndata with @LuckyMD

When interacting with an anndata object that has a column with strings, it gets converted to a categorical and a warning is printed. This is great. Since recently the conversion however creates an ordered categorical datatype. Looking at the recent commits (especially c411161bde6e5513d8e80b78e3aa0421bdb8b086) this seems to be intended.

This does however create problems when using such an ordered categorical as an input to a model fitting procedure in e.g. MAST through rpy2 and anndata2ri.

We were wondering if categoricals should really be stored as ordered in anndata.

**Comment by falexwolf** [comment]
I'm assuming you're running on the latest pandas and anndata, and this discussion is about the fixes made by @flying-sheep to accommodate for the new way pandas treats categoricals and strings.

@flying-sheep: I didn't notice the `ordered` flag in the `pd.Categorical` constructor. I agree that much of the functionality within Scanpy assumes that `.cat.categories` has a meaningful order. I'm not sure whether this is what the `ordered` flag also aims at. In my opinion, `.cat.categories` called on a `pd.Categorical` instance, by definition has a fixed order, as it's always a `pd.Index` instance (which by definition it ordered), irrespective of whether `pd.Categorical` was called using `ordered=True` or not. I suspect the `ordered=True` flag is related to how certain operations are defined within pandas. For instance, if something is `ordered` you could implement an "approximate" addition as an increment, which you cannot when it's not `ordered`. But this obviously has nothing to do with our use cases, which all only use the _order_ in `.cat.categories` to match colors or put labels in a defined order.

If it's causing problems somewhere, I suspect we could remove the `ordered` flag in the linked commit.

PS: What kind of problems is it causing?

**Comment by flying-sheep** [comment]
Hmm. `Categorical(ordered=True)` is meant for cases where we have categories like “Low”, “Medium”, and “High”. That is, ordinal data. We don’t necessarily have that here (e.g. cluster labels have no intrinsic order even though they might be called “Cluster 1” through “Cluster 9”)

> If it's causing problems somewhere, I suspect we could remove the ordered flag in the linked commit.

I’m pretty sure we can’t. Pandas’ changes about how categorical data works contain that [min and max don’t work on unordered categorical data](http://pandas.pydata.org/pandas-docs/stable/user_guide/categorical.html#sorting-and-order).

I can’t pinpoint where that resulted in an error, but I know it did (should have written a more informative commit message…). I checked out the parent commit to the change (b2b9e5dd4367bde3a84b72b74dc2a661114f899d) and ran the anndata and scanpy tests with it, but didn’t get an error anymore that had to do with the sorting. Weird. Maybe they reverted it in 0.24.1?

BTW: I’m currently developing https://github.com/flying-sheep/anndata2ri/, you might want to try it out.

**Comment by LuckyMD** [comment]
We're getting unintentional behaviour with ordered categoricals when using `anndata2ri` to move from AnnData to R to use differential expression testing with MAST (and I suspect this is also true for any other R tool for DE testing). If you add a batch covariate into the model which is an ordered categorical, it is treated differently than a non-ordered categorical would be treated. Ordered categoricals can be regressed against e.g., using intervals for each category such that the interval counts are normally distributed with regards to the underlying scale. This produces different results than using non-ordered categoricals. I'm not sure how ordered categoricals are treated in `sc.pp.regress_out()`, but it could have a similar effect. So using `ordered=True` in `sanitize_anndata()` could have been a breaking change. Although I guess there is a test for `sc.pp.regress_out()` with categorical data, so maybe this treats ordered and unordered categoricals the same.

As @flying-sheep suggests categoricals in `AnnData` are not strictly ordered. Thus, I would consider using `min()` and `max()` on categorical data a bad idea anyway. I wonder where it is needed.

**Comment by flying-sheep** [comment]
That’s the problem: I don’t know anymore, but I’m pretty sure it was a necessary change.

We can try changing it back and see what breaks.

**Comment by flying-sheep** [comment]
Aha! Found it!

https://github.com/theislab/anndata/blob/3e93ed702ff83eca59edc1f63a035ff93319ca12/anndata/base.py#L212-L213

So how can we fix this one?

**Comment by falexwolf** [comment]
Awesome! :)

**Comment by maximilianh** [comment]
Sorry, I don't understand the result of this discussion. Like le-ander, I've added cluster info to my ad.obs with ad.obs["cluster"]=df["cluster"].astype("category") but now I cannot write it to an h5ad anymore, because it complains that cluster is unordered, "Categorical is not ordered for operation max". I'm relatively sure that this used to work. I guess that I don't understand why min/max is needed at all to write an object to an h5 file. Should I force all categorical fields to be ordered, is that the solution? Should I do ad.obs["Cluster"] = pd.Categorical(df["Cluster"], ordered=True), for all my categorical fields?

**Comment by flying-sheep** [comment]
> now I cannot write it to an h5ad anymore, because it complains that cluster is unordered, "Categorical is not ordered for operation max"

that’s what I meant when I said

> We can try changing it back and see what breaks.

You found where it breaks. Can you create a minimal reproducible example so we can write a test for this?

**Comment by maximilianh** [comment]
Versions:
scanpy==1.4.3+80.g740c557 anndata==0.6.16 umap==0.3.9 numpy==1.14.2
scipy==1.1.0 pandas==0.24.2 scikit-learn==0.19.1 statsmodels
0.8.0 python-igraph==0.7.1 louvain==0.6.1

Minimal example:

import scanpy.api as sc
ad = sc.read_h5ad("data/pbmc3k_raw.h5ad")
sc.pp.neighbors(ad)
sc.tl.louvain(ad)
ad.write("test.h5ad")

TypeError: Categorical is not ordered for operation max
you can use .as_ordered() to change the Categorical to an ordered one

**Comment by maximilianh** [comment]
I don't see why h5ad-writing involves getting the min-max values of a
categorical field.

**Comment by ivirshup** [comment]
@maximilianh, it looks like your version of anndata is out of date (most recent release was `0.6.21`), do you still get this error if you update it?

@flying-sheep, I hadn't realized we have ordered categoricals now. I see the use, but I don't think we have a way to tell if a categorical is ordered or not when we read it from a `h5ad` file.

**Comment by maximilianh** [comment]
Thanks Isaac! I'm not getting this error anymore. I guess there never was a
problem and I just didn't check the requirements when I install scanpy
master from github. Sorry!

**Comment by maximilianh** [comment]
I guess I'm still surprised by how quickly these libraries and their
underlying dependencies change, I'm not used to that yet from other
software. Also, I should not be using the master branch and just
always install the release.

**Comment by LuckyMD** [comment]
@ivirshup I think ordered categoricals were put in, and then taken out again. It def shouldn't be the default to create a random order in the categoricals, as that has a meaning when it comes to statistical testing.
