### ISSUE TITLE
Sorting AnnData X by obs

### ISSUE THREAD

**Issue by salilgarg** [theislab/anndata#125]
Hi,

Apologies in advance as I know this is probably trivial and I'm missing something but I've been at it for a day and can't figure it out.  I have an AnnData object with obs that I've added from other analyses ('Cell_type', 'State1Z', 'State2Z', 'State3Z'), the last 3 of which are continuous variables.  What I want to do is sort the 'X' of the AnnData in place through the obs parameters (like 'State1Z').  The reason for doing this is that I color the cells using these parameters and right now the plotting functions in scanpy.pl are plotting the cells in order of X, as opposed to the largest values of 'State1Z' being on top.

If it were a pandas dataframe I would do something like:
mydf.iloc[mydf['State1Z'].abs().argsort()]
but everything I try with AnnData either returns just a 1-D vector or the obs part as a dataframe (without the attached X).
Any suggestions?  Is there a built in method to sort on obs that I'm missing?  Thanks in advance and sorry if this is trivial.

**Comment by LuckyMD** [comment]
Hi,

In most plotting functions there should be a `sort_order` parameter which, if `True`, plots the highest value last. I thought this was actually the default behaviour though.

**Comment by salilgarg** [comment]
Hi,

Thanks for the response.  My AnnData actually has two samples, which I had been displaying together by having 'State1Z' varying from -1 to 0 for one sample type and 0 to 1 for the other sample type (and then using a diverging colormap like RdBu).  Then you can visualize the distinction between samples and the degree of 'State1Z' or other colormapped feature.  This worked for pd dataframes because I could use .abs().argsort() so both -1.0 and 1.0 were plotted on top.  I can't figure out how to get similar behavior out of AnnData.  Right now the 0 to 1 sample plots correctly (due to sort_order) but -1.0 to 0 does not on the same plot.  I'll consider changing my structure or copying out to a pd dataframe.

**Comment by LuckyMD** [comment]
This sounds like a little more difficult. I would consider this a scanpy feature request though. You would basically need another option for `sort_order` instead of just `True` or `False`.

**Comment by salilgarg** [comment]
Ty and agreed!  Apologies if this was posted in the wrong place.
