### ISSUE TITLE
dimensions not preserved after split and merge

### ISSUE THREAD

**Issue by flying-sheep** [theislab/anndata#13]
Hi,

I observed the following issue:

1. I have split up my AnnData object in two parts
2. removed some cells from the second AnnData object,
3. Did louvain clustering on the second part, and
3.  merged this part back together with the first part.

However, after applying the concatenate function, I ended up with more features even though I definitely had the same number of genes in both parts.

cc @mbuttner

**Comment by falexwolf** [comment]
I guess that's due to the non-unique variables issue that we discussed via email some time ago.

I'll add a warning - or enforce making them unique - in the concatenate function. I'll just look at another example first... Should be done by Monday...
