### ISSUE TITLE
when reading loom files, construct a matrix from 1D attributes

### ISSUE THREAD

**Issue by neuromusic** [theislab/anndata#131]
While loom supports multidimensional annotations, the community tends to store embeddings (e.g. tSNE, umap) in individual 1D attributes ("_tSNE1","_tSNE2", etc. see: http://linnarssonlab.org/osmFISH/availability/).

It would be useful to import these files into the scanpy ecosystem (incl cellxgene) if these dimensions could be composed into a new obsm dimension when loading a loom file.

Example API:
``` Python
# indicates the target key and which attributes it should be constructed from
obsm_names = { 
    'X_spatial': ['X','Y'],
    'X_tsne': ['_tSNE_1','_tSNE_2'],
}

fname = "osmFISH_SScortex_mouse_all_cells.loom"
adata2 = anndata.read_loom(
    fname,
    obsm_names=obsm_names,
)
```

I've implemented this for review. PR incoming...

**Comment by ivirshup** [comment]
Closed by #132
