### ISSUE TITLE
Backwards breaking change: Sparse observation and variables annotation

### ISSUE THREAD

**Issue by falexwolf** [theislab/anndata#136]
We had this discussion several times already, last time here: https://github.com/theislab/anndata/pull/133

It would be great to generate a new attribute for sparse annotations of observations and variables. Presumably `.obss` and `.vars`, where `s` stands for sparse.

I'd assume that @Koncopd could be the one to implement it, let's talk about it soon! If anyone else would feel there is bandwidth, please let me know.

**Comment by flying-sheep** [comment]
why not just into obsm?
