### ISSUE TITLE
obs is ignored when initializing AnnData with DataFrame

### ISSUE THREAD

**Issue by fabianrost84** [theislab/anndata#137]
Minimal example:
```python
import anndata
import numpy as np
import pandas as pd

X = pd.DataFrame(np.empty((2,100)))
obs = pd.DataFrame(np.empty((2, 5)))

anndata.AnnData(X=X, obs=obs)
```
Output:
```python
AnnData object with n_obs × n_vars = 2 × 100 
```
Please note, that this `AnnData` has no entries in `obs`, so `obs` was ignored. In contrast, `obs` is set correctly, when I pass an array to X:
```python
anndata.AnnData(X=X.values, obs=obs)
```
Output:
```python
AnnData object with n_obs × n_vars = 2 × 100 
    obs: 0, 1, 2, 3, 4
```

**Comment by flying-sheep** [comment]
This is the culprit:

https://github.com/theislab/anndata/blob/a500a05c820667d6ed13732ff6db9cc973365845/anndata/base.py#L799-L802

**Comment by falexwolf** [comment]
@flying-sheep, agreed! Sorry, I wasn't thinking of that. Would you amend it?

**Comment by fabianrost84** [comment]
What about this?
