### ISSUE TITLE
Conversion to categorical makes None "None"

### ISSUE THREAD

**Issue by ivirshup** [theislab/anndata#141]
I was trying to use categorical labels where some samples don't get a label and ran into this. I think that we should allow having null labels, and visualizing shouldn't meaningfully mutate the object.

```python
import scanpy as sc
import numpy as np

pbmc = sc.datasets.pbmc68k_reduced()
some_subset = np.random.choice(
    pbmc.obs_names, int(pbmc.shape[0] / 2), replace=False
)
pbmc.obs["has_nulls"] = None
pbmc.obs.loc[some_subset, "has_nulls"] = "a value"
pbmc.obs["has_nulls"].isnull().sum()
# 350
sc.pl.pca(pbmc)
pbmc.obs["has_nulls"].isnull().sum()
# 0
```

**Comment by flying-sheep** [comment]
yikes, definitely. do categoricals support “nan” or some other not-set value?

**Comment by falexwolf** [comment]
If yes, then this [https://github.com/theislab/scanpy/blob/0401341877e586e36412db1e178601bf1f545037/scanpy/_settings.py#L58] was stupid of me...

**Comment by ivirshup** [comment]
I suspect this: https://github.com/theislab/anndata/blob/34f4eb63710628fbc15e7050e5efcac1d7806062/anndata/base.py#L1419 

and that ‘is_string_dtype’ doesn’t work is to blame.

**Comment by grst** [comment]
Here's a test-case: 

**Actual behaviour**
```python
import numpy as np
from anndata import AnnData
adata = AnnData(
    obs=pd.DataFrame().assign(
        str_with_nan=["foo", "bar", None, np.nan, "foo"],
        booelan_with_nan=[True, False, np.nan, None, True],
    )
)
adata._sanitize()
```
```console
... storing 'str_with_nan' as categorical
... storing 'booelan_with_nan' as categorical
```
```python
adata.obs["str_with_nan"].values
```
```console
['foo', 'bar', 'None', 'nan', 'foo']
Categories (4, object): ['None', 'bar', 'foo', 'nan']
```
```python
adata.obs["booelan_with_nan"].values
```
```console
['True', 'False', 'nan', 'None', 'True']
Categories (4, object): ['False', 'None', 'True', 'nan']
```

**Expected behaviour**
 * `boolean_with_nan` is not converted to categorical (bool stays bool)
 * `str_with_nan` is converted to categorical, but `nan` and `None` are treated as special values.

**Comment by ivirshup** [comment]
Thanks for the example @grst! I've got a fix opened up.

About the boolean arrays, we don't quite have a solution ready for nullable booleans. I've put some thoughts on this here #504.
