### ISSUE TITLE
Performing KMEANS Clustering on Dataset

### ISSUE THREAD

**Issue by JPV95** [theislab/anndata#143]
Hello,

I have a single cell NGS data that I am trying to further analyze beyond the analysis that we get from 10x Genomics. I see that there is Louvain clustering, etc. However, for the analysis, especially those that are visually concerned, I would like to use K-MEANS with k = 6, how do I assert this in ScanPy.

Please, any help you may be able to provide will be useful

Thank you,
JPV95

**Comment by falexwolf** [comment]
There is no way to do it in Scanpy. You can use scikit learn for it. 🙂
