### ISSUE TITLE
ImportError: cannot import name 'IndexMixin' with scipy 1.3.0rc1

### ISSUE THREAD

**Issue by scottgigante** [theislab/anndata#146]
A warning in advance that `anndata` is broken for `scipy` version `1.3.0`.

```
File "/home/travis/build/KrishnaswamyLab/PHATE/Python/test/test.py", line 14, in <module>
    import anndata
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/anndata/__init__.py", line 1, in <module>
    from .base import AnnData
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/anndata/base.py", line 21, in <module>
    from scipy.sparse.sputils import IndexMixin
ImportError: cannot import name 'IndexMixin'
```

**Comment by ivirshup** [comment]
Looks like it's moved to `scipy.sparse._index.IndexMixin` now: https://github.com/scipy/scipy/pull/7827

**Comment by flying-sheep** [comment]
That’s what we get for using undocumented stuff.

Was it changed or just moved? If there have been no semantic changes we can just do

```py
try:
    scipy.sparse._index import IndexMixin
except ImportError:
    from scipy.sparse.sputils import IndexMixin
```

**Comment by ivirshup** [comment]
It's very different.

`_boolean_index_to_array`, `_check_ellipsis`, and `_unpack_index`, are now functions inside of the `_index` module, but I think he new implementation shares no methods with the old one.

**Comment by bkmartinjr** [comment]
FYI:  SciPy 1.3.0 was just released, breaking AnnData for "fresh" installs.

**Comment by csweaver** [comment]
Could we add a temporary fix by excluding scipy 1.3.0 from valid versions in requirements.txt? And solve the IndexMixin problem later?

**Comment by falexwolf** [comment]
@flying-sheep, `IndexMixin` had been introduced by you; when taking a looking a long time ago, I also had the feeling that we could implement it ourselves to prevent relying on an undocumented or (it seems that this is now the case) private function.

**Comment by flying-sheep** [comment]
It’s pretty large and hairy though. I think relying on bulletproof numpy functionality might be a better idea than copying it and having to maintain our fork of the thing ourselves.

Do you think it’s likely they move it again or rename it soon?

**Comment by falexwolf** [comment]
Ok, agreed. Re move/rename: I have no clue; I haven't followed Scipy's codebase in that great detail. But I'd share the expectation that some convergence should be expected.

**Comment by flying-sheep** [comment]
Ah, sorry, I missed @ivirshup’s comment that we only use `_unpack_index`, which isn’t that large and hairy!

I’ll quickly copy it into anndata

**Comment by falexwolf** [comment]
Awesome!

**Comment by falexwolf** [comment]
I'll quickly make `v0.6.20` so that the bug that everyone encounters in default installs gets fixed....

**Comment by falexwolf** [comment]
It's out in version `0.6.20`.

**Comment by nahidfarhady** [comment]
I got this error after updating scipy:
`ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all().
`
