### ISSUE TITLE
Can't assign to obs in AnnData view

### ISSUE THREAD

**Issue by joshua-gould** [theislab/anndata#148]
<table>
<tr>
<td><code>In [1]:</code></td>
<td>

```py
import anndata
import pandas as pd
adata = anndata.AnnData(
    X=np.array([[1,2], [1,2], [1,2]]),
    obs=pd.DataFrame(index=['a','b','c']),
    var=pd.DataFrame(index=['a','b']),
)
s = adata[:, ['b','a']]
df = pd.DataFrame(index=['a', 'b'], data={'c1':[1,2]})
df2 = s.obs.join(df)
df2['c1']
```

</td>
</tr>
<tr>
<td><code>Out[1]:</code></td>
<td>

```
a    1.0
b    2.0
c    NaN
Name: c1, dtype: float64
```

</td>
</tr>
<tr>
<td><code>In [2]:</code></td>
<td>

```py
s.obs = df2
s.obs['c1']
```

</td>
</tr>
<tr>
<td><code>Out[2]:</code></td>
<td>

```
KeyError: 'c1'
```

</td>
</table>
</tr>

**Comment by ivirshup** [comment]
@joshua-gould, that seems wrong, thanks for the report! (btw: I think you're missing an `import numpy as np`)

@falexwolf or @flying-sheep: this should be creating a copy of s then assigning `df2` to that, right? The setter looks like it's trying to do the modification in-place:

https://github.com/theislab/anndata/blob/fc7f3cb06c191aff4fcad6af88f0c3012d7d1a65/anndata/base.py#L1090-L1098

(ditto with var)

**Comment by flying-sheep** [comment]
In the commit that introduced the view functionality,  542edccc29edf0b9d43b3a912c213cf18b599a6d, the `AnnDataAttributeView` and `ArrayView` classes already had copy-on-write behavior (their `__setitem__` methods called `adata_view._init_as_actual(…)`)

That was also the last commit that touched the last two lines of `obs.setter` and so on, not introducing COW behavior for those.

I also think that the only sound behavior would be to be consistent here,

**Comment by ivirshup** [comment]
Agreed.

I just keep running into code that's definitely trying to make modifications in-place.

Aside on the formatting above:

* I think you might want `In[2]:` 
* Is that just a table, or is there nice notebook formatting now? I can't look at the source markdown on this repo :(

**Comment by flying-sheep** [comment]
Sadly just a table. It was an experiment to see how much work it is, and the answer is: too much (I had to do the HTML markup manually)
