### ISSUE TITLE
Files with singleton categoricals cannot be opened

### ISSUE THREAD

**Issue by vals** [theislab/anndata#15]
What I mean by this is that you might have a categorical, which internally in the `h5ad` is represented by e.g. `uns/condition_categories`. If there is only one `condition` (perhaps because it's a subset of data), this will fail the Pandas check for unique categories, because the `shape` for `uns/condition_categories` is `(1, )`.

This can be avoided by when writing the file to `h5py`, detecting singleton categories and appending a dummy category, to ensure there are at least two unique values in `uns/conditions_categories`.

**Comment by falexwolf** [comment]
Sorry about this. It's a known bug https://github.com/theislab/scanpy/issues/102 and I should already have fixed it. I'll provide a fix and a new anndata release today.

**Comment by falexwolf** [comment]
Fixed in https://github.com/theislab/anndata/commit/330cb0d243ae6a81c86efd3cd310982d8066f4a3. Will prepare a new release 0.5.7 just in a bit after fixing another little thing...

**Comment by falexwolf** [comment]
0.5.7 is out with a few further minor updates...

**Comment by falexwolf** [comment]
Btw: congrats on your SpatialDE paper! And thank you for citing Scanpy. Soon, there will be Scanpy 1.0... a lot better...

**Comment by vals** [comment]
Just tested 0.5.7 and it worked! Thanks!

Thanks for the congratulation too :), was looking at choices for highly variable genes detection in Bioconductor, but having a readily available Python defualt was quite a time saver!
