### ISSUE TITLE
UnboundLocalError: local variable 'vstack' referenced before assignment mnn

### ISSUE THREAD

**Issue by GuidoBarzaghi** [theislab/anndata#150]
Hello everyone,

First of all, thanks for your amazing work!

I just wanted to point out a potential issue as I'm not sure if it's something related to my data, environment or similar, or it's more general.
I encountered the error while running the following commandline:

```py
Merged_data = sce.pp.mnn_correct(Scanpy_object_1, Scanpy_object_2, var_subset=HVGs, 
                                 batch_key="Experiment", do_concatenate=True)
```

which pointed at the following site:

https://github.com/theislab/anndata/blob/289957d5410f0f6825f0841de00c4c612d95f2ad/anndata/base.py#L1908

I quickly overcame the issue by reimporting vstack in case `if any(issparse(a.layers[key]) for a in all_adatas)` evaluates True

**Comment by juhaa** [comment]
I came across the same error today. Inspecting the concatenate function, seems like this problem occurs when
1. none of the adata.X are sparse, and
2. some layers contain a sparse matrix

The variable `any_sparse` is checked if scipy.vstack needs to be imported and it is assigned here:

https://github.com/theislab/anndata/blob/289957d5410f0f6825f0841de00c4c612d95f2ad/anndata/base.py#L1828

Then the error you mentioned arises here with the conditions mentioned:
https://github.com/theislab/anndata/blob/289957d5410f0f6825f0841de00c4c612d95f2ad/anndata/base.py#L1899-L1910

I guess the best solution would be to also check for sparse layers when assigning `any_sparse`. But for now we can just import the vstack before concatenation.

**Comment by LuckyMD** [comment]
I still have this error in anndata 0.6.22.post1, so it doesn't seem to have been fixed by the commit above.

A small reproducible example:

```pytb
test = sc.datasets.pbmc3k() 
test.obs['batch'] = [1 if idx < 1000 else 2 for idx in range(test.n_obs)] 
test.layers['counts'] = test.X                                                                                                                                                                                                    
test_split = [test[test.obs['batch'] == i].copy() for i in test.obs['batch'].unique()]                                                                                                                                            

for i in test_split: 
    sc.pp.scale(i) 

merged = test_split[0].concatenate(test_split[1:])                                                                                                                                                                                
---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
<ipython-input-47-e04297f9f939> in <module>
----> 1 merged = test_split[0].concatenate(test_split[1:])

/home/icb/daniel.strobl/miniconda3/envs/benchmarking_data_integration_trvae/lib/python3.7/site-packages/anndata/core/anndata.py in concatenate(self, join, batch_key, batch_categories, index_unique, *adatas)
   1901             for key in shared_layers:
   1902                 if any(issparse(a.layers[key]) for a in all_adatas):
-> 1903                     layers[key] = vstack(layers[key])
   1904                 else:
   1905                     layers[key] = np.concatenate(layers[key])

UnboundLocalError: local variable 'vstack' referenced before assignment
```

**Comment by flying-sheep** [comment]
Yeah, some of the logic is fucky. `any_sparse` is defined as

https://github.com/theislab/anndata/blob/289957d5410f0f6825f0841de00c4c612d95f2ad/anndata/base.py#L1828

and a condition to import `vstack`.

https://github.com/theislab/anndata/blob/289957d5410f0f6825f0841de00c4c612d95f2ad/anndata/base.py#L1900-L1901

But then `vstack` is used under this condition:

https://github.com/theislab/anndata/blob/289957d5410f0f6825f0841de00c4c612d95f2ad/anndata/base.py#L1906-L1908

So `any_sparse` will be false if no `X` is sparse, `vstack` won’t be imported, but if any layer is sparse, the code tries to use `vstack` anyway.
