### ISSUE TITLE
Broken logic in HDF5 writing

### ISSUE THREAD

**Issue by flying-sheep** [theislab/anndata#156]
We have two separate copies (sigh) of some logic I broke (sorry) that need to be replaced with a fixed helper function:

https://github.com/theislab/anndata/blob/a9390d6fca537fafdf9e93f1b85a91c10af7ca58/anndata/readwrite/write.py#L151-L154

https://github.com/theislab/anndata/blob/a9390d6fca537fafdf9e93f1b85a91c10af7ca58/anndata/readwrite/write.py#L280-L286

Alex said the intention is to test if we’re dealing with a `h5py.Dataset` and dense array with matching dimensions and dtypes and if so, simply replace it.

I have no idea about zarr, so I’m filing this instead of quickly fixing it.

**Comment by Koncopd** [comment]
I believe it should be something like [this](https://github.com/theislab/anndata/pull/157). Still need to test it.

**Comment by ivirshup** [comment]
Closing as this has been superseded.
