### ISSUE TITLE
anndata in scanpy seems to break scipy sparse data

### ISSUE THREAD

**Issue by reemagit** [theislab/anndata#159]
Whenever I import anndata or scanpy it seems that scipy sparse matrix assignment is broken. The minimal example is:

```python
import numpy as np
from scipy.sparse import csr_matrix
import anndata
x = csr_matrix(np.eye(10))
x[0,3] = int(4)
```

which for which I get the error

```pytb
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-36-2e1809373207> in <module>
----> 1 x[0,3] = int(4)

~/anaconda2/envs/macrophage/lib/python3.6/site-packages/scipy/sparse/_index.py in __setitem__(self, key, x)
     67             if x.size != 1:
     68                 raise ValueError('Trying to assign a sequence to an item')
---> 69             self._set_intXint(row, col, x.flat[0])
     70             return
     71 

~/anaconda2/envs/macrophage/lib/python3.6/site-packages/scipy/sparse/compressed.py in _set_intXint(self, row, col, x)
    795     def _set_intXint(self, row, col, x):
    796         i, j = self._swap((row, col))
--> 797         self._set_many(i, j, x)
    798 
    799     def _set_arrayXarray(self, row, col, x):

~/anaconda2/envs/macrophage/lib/python3.6/site-packages/anndata/h5py/h5sparse.py in _set_many(self, i, j, x)
    176     i, j, M, N = self._prepare_indices(i, j)
    177 
--> 178     n_samples = len(x)
    179     offsets = np.empty(n_samples, dtype=self.indices.dtype)
    180     ret = _sparsetools.csr_sample_offsets(M, N, self.indptr, self.indices,

TypeError: object of type 'numpy.float64' has no len()
---------------------------------------------------------------------------
```

I am using anndata 0.6.21. Am I doing something wrong?

EDIT: just as a clarification, this error doesn't occur if I don't import anndata

**Comment by ivirshup** [comment]
I think I just caught this myself.

Are you using scipy `v1.3`?

**Comment by reemagit** [comment]
No, I am using the last version 1.4.3. 

As I have understood, the __setitem__ function of scipy CSR matrices ([…]/scipy/sparse/_index.py) first converts the value to be set to a scalar and then calls _set_many. 
_set_many is in turn overridden by anndata ([…]/anndata/h5py/h5sparse.py), but for some reason the new function expects an array with multiple values and not a scalar (line 178 in […]/anndata/h5py/h5sparse.py, where len(x) is called). Since the scalar has no __len__ the exception is raised. 

I found that a quick workaround is adding a line right before line 178, converting the scalar to a 1-element array:
x = np.asarray([x]).flatten()
I am not sure if it breaks something else, but so far I have been able to run all the functions that were broken (scipy matrices and also the sc.tl.paga() function in scanpy). All seem to be running correctly.

Do you think this is a valid solution?

**Comment by ivirshup** [comment]
Right now, scanpy is pinned to versions of scipy below `v1.3.0` due to some sparse matrices issues and dependencies not being compatible. While we're working on getting `v1.3.0` matrices working in #160, for now I'd suggest just downgrading scipy to `v1.2.1` until at least the next release. Would this work for you're use case?

That description of the issue sounds pretty accurate! We've already got the behavior fixed for in memory matrices (by just not overwriting their methods), but are trying to make sure we're not removing capabilities from backed `AnnData` objects.

**Comment by phitlingt** [comment]
Having the same issue and I have downgraded scipy to v1.2.1, the workaround solves my problem for now. Thank you!

**Comment by flying-sheep** [comment]
This is of course fixed by now:

https://github.com/theislab/anndata/blob/5a6459cbb2de947f8ff56507a0819d58dcdf7e40/anndata/core/sparsedataset/__init__.py#L172-L175
