### ISSUE TITLE
Data subsetting method 

### ISSUE THREAD

**Issue by ahy1221** [theislab/anndata#17]
Is there a plan to add data subset method for extracting some particular cells for the anndata object ?

**Comment by falexwolf** [comment]
What do you mean beyond subsetting via `adata[my_cells]` where `my_cells` could be any valid numpy indexing object?

**Comment by elfore** [comment]
Do we have this method now? "subsetting via adata[my_cells] where my_cells could be any valid numpy indexing object"

**Comment by ivirshup** [comment]
Does `adata[my_cells]` not work for you?

**Comment by elfore** [comment]
It worked for me, thanks

**Comment by brianpenghe** [comment]
Does anyone know why `adata[my_cells,:]` stopped working?

**Comment by ivirshup** [comment]
@brianpenghe, could you elaborate on that?

**Comment by brianpenghe** [comment]
> @brianpenghe, could you elaborate on that? A traceback and versions would be useful.

It seems that subsetting an anndata used to work by two methods:
`adata[my_cells,:]`
`adata[my_cells]`

But it seems that recently only the second method works, after I've already subsetted the anndata once.

**Comment by ivirshup** [comment]
Hmm. I can't immediately reproduce that. Could you open a new issue and provide some more info there? Things like version numbers and the traceback. It'd be especially helpful if you could reproduce this with some randomly generated data or one of the example datasets.
