### ISSUE TITLE
Layers with different numbers of .vars

### ISSUE THREAD

**Issue by arnavm** [theislab/anndata#173]
Hi,

I love that AnnData has added support for multiple layers. This will enable us to store multiple kinds of single cell data in a single file. In the current implementation, it seems for each subsequent layer, the number of variables, and names of those variables, must the same as the base layer. This is fine for gene-centric applications (e.g. RNA velocity) but for regulatory information (e.g. open chromatin, transcription factor binding sites), the data may not fit that paradigm (i.e. one feature <-> one gene). Is it possible to make layers where the .var can be of arbitrary dimension and annotation?

Thanks!

**Comment by Koncopd** [comment]
Hi, i think what you need is [adata.obsm](https://anndata.readthedocs.io/en/stable/anndata.AnnData.obsm.html#anndata.AnnData.obsm)

**Comment by LuckyMD** [comment]
Hey!

I think there is still an ongoing discussion for how data should be stored together with different feature spaces. You could of course store this in `adata.obsm`, but I guess that is not exactly the solution you are going for. If you're interested in storing epigenetic data in Anndata in general, it might be worth taking a look at [Episcanpy](https://github.com/colomemaria/epiScanpy)

**Comment by ivirshup** [comment]
Just my two cents, I've been putting antibody counts from CITE-seq in a separate AnnData object for processing, then adding that as a dataframe to obsm for downstream analysis. However, support for this is only on development branches at the moment. I'm hoping to include this workflow in a demonstration of new features for the next round of releases.

**Comment by arnavm** [comment]
I hadn't heard of Episcanpy, I'll have to check that out. It's promising but it looks like it can only handle epigenomic data, not data with both epigenomic and RNA-seq information.

adata.obsm might be best workaround for now.
