### ISSUE TITLE
what is the .h5ad file?

### ISSUE THREAD

**Issue by fenghuijian** [theislab/anndata#180]
Hi,
I have some question about the .h5ad file .
What is a h5ad file? 
What is its data storage structure? 
Why is it read much faster than CSV.

**Comment by Koncopd** [comment]
Hi, this is a hdf5 file with some additional structure specifying how to store AnnData objects.
We use [h5py](http://www.h5py.org/) package, so you can read more about the hdf5 file format there.

**Comment by josinejansen** [comment]
Hi Koncopd, 
Do you happen to know how to re-write an .h5ad file to a 'regular' .h5 file?
I'd like to execute some downstream analyses with a subset of cells I created with Anndata/Scanpy, using a software package which can not read the .h5ad format, but CAN however read the .h5 format.
Thanks in advance,

Josephina

**Comment by Koncopd** [comment]
Hi, @josinejansen . You can open a h5ad file as if it is a standard hdf5 file.
