### ISSUE TITLE
unable to reorder the observation or variables when anndata has categorical data in the obs

### ISSUE THREAD

**Issue by screamer** [theislab/anndata#187]
I load an exising anndata from h5ad file. However, it is unable to be reodered by observation index or variable index. It works untill I converted the catgorical type to str in the obs.

The data can be accessed at the following link:
ftp://ngs.sanger.ac.uk/production/teichmann/BBKNN/PBMC.merged.h5ad

adata=sc.read_h5ad(input_file)
nindex = np.random.permutation(adata.obs.index)
adata=adata[nindex,:]

IndexError: index 8 is out of bounds for axis 0 with size 8

Version:
scanpy 1.4.4.post1
anndata 0.6.22.post1

**Comment by ivirshup** [comment]
Looks like there's something misaligned between the categorical and the saved colors in uns. You can get around this by running something like:

```python
def reset_colors(adata):
    to_remove = [k for k in adata.uns.keys() if "_colors" in k]
    for k in to_remove:
        del adata.uns[k]

adata = sc.read_h5ad(input_file)
reset_colors(adata)
nindex = np.random.permutation(adata.obs.index)
adata = adata[nindex,:]
```

Any chance you know what operations got you to this state?

**Comment by screamer** [comment]
I have no idea how it happens ? I just got it from the website and attempts to run some codes on it.

Thanks for your help!
All the best
