### ISSUE TITLE
adata.copy() doesn't deepcopy layers

### ISSUE THREAD

**Issue by gokceneraslan** [theislab/anndata#201]
After copying an anndata via `adata.copy()`, layers of the resulting object are still pointing to the layers of the original object:

```python
import scanpy as sc

adata = sc.datasets.paul15()
adata.layers['L'] = adata.X.copy()
adata.layers['L'].sum()
```

Output: 6083492.0

```python
bdata = adata.copy()
adata.layers['L'] *= 2.0
bdata.layers['L'].sum()
```

Output: 12166984.0

I realized that when I saw scvelo normalizing the layers of the original object even though I passed a copy to scv.pp.filter_and_normalize...

**Comment by ivirshup** [comment]
What version are you on? I'm not able to reproduce on `master`.

**Comment by VolkerBergen** [comment]
Hi Gokcen, I just run this minimal example and couldn't reproduce that either.

**Comment by gokceneraslan** [comment]
Can anybody try with the stable anndata package?

![image](https://user-images.githubusercontent.com/1140359/64431019-8d390f00-d087-11e9-8874-9655b4e79fa9.png)

**Comment by VolkerBergen** [comment]
With your version ('0.6.22.post1') I get the same error, with the latest ('0.6.22.post1+29.g16615d7') it's fixed.

**Comment by gokceneraslan** [comment]
ok, thanks. Adding a test would be useful then.
