### ISSUE TITLE
Make .raw work with AnnData.concatenate

### ISSUE THREAD

**Issue by sjfleming** [theislab/anndata#205]
If I have a list of adata objects, for example
```
adata_list = [adata1, adata2, adata3]
```
and I do
```
adata = adata_list[0].concatenate(adata_list[1:])
```
I get that `adata.raw` is empty, even if `adata1`, `adata2`, and `adata3` had `.raw` slots populated.

I think the desired behavior should be to concatenate the `.raw` data as well (if they all have it).

For the time being, I have worked my way around this, but I think this would be a desirable behavior.

**Comment by simonewebb** [comment]
Hi sjfleming, I am also running into this issue. Would you care to share your workaround solution? Would be very useful to also concatenate the .raw slot!

Thanks

Simone

**Comment by simonewebb** [comment]
Thanks for the reply, flying-sheep!

This is the process I would like to run through, I hope this is clear to you... I have an overall object, containing ~8k cells (this contains a .raw slot). I create two subsets. `adata_1 = adata[adata.obs['cell.labels'].isin(['HSC'])].copy()` gives a subset of 803 cells and `adata_2 = adata[adata.obs['cell.labels'].isin(['MEP'])].copy()` gives a subset of 410 cells. Both adata_1 and adata_2 have retained their raw slot.

I would then like to merge adata_1 and adata_2 into adata_3 and retain the raw data here. When I run `adata_merge_1 = adata_1.concatenate(adata_2, batch_key='treatment')` the .raw slot is empty. When I run `adata_merge_2 = adata_1.concatenate(*adata_2, batch_key='treatment')` I get a ValueError: all the input arrays must have same number of dimensions. 

Really I am trying to find a way to merge subsets (which may be filtered and have .X and .raw slots of differing shape) into a larger object which retains raw so that I can rerun log/normalising/scaling. 

Please let me know if I am missing something basic RE recommended pipelines. Thanks!

**Comment by flying-sheep** [comment]
Shouldn’t be a problem to check if all `.raw`s are identical via `reduce(adatas, operator.is_)`.

>     adata_1.concatenate(*adata_2, batch_key='treatment')

This is obviously wrong! `*things` means “use all elements of the list/tuple/iterable `things` as arguments”. I meant that you can write

    adata = adata_list[0].concatenate(*adata_list[1:])

much more beautifully as

    adata = AnnData.concatenate(*adata_list)

**Comment by flying-sheep** [comment]
Actually when slicing, raw gets sliced too, so this doesn’t seem easy: A `.raw` for the concatenated object wouldn’t be a simple view of any adata anymore, but a pretty complex one:

```py
ad = AnnData(...)
ad.raw = ad
ad_1 = ad[2:4]
ad_2 = ad[0:2]
ad_concat = AnnData.concatenate(ad_1, ad_2)
assert ad_concat.raw.oidx.tolist() == [3, 4, 0, 1]
```

I’m not sure if it’s even possible in all cases. An implementation would

1. Check if the `._adata`s are the same
2. Coerce the `oidx`s and `vidx`s to integer indexes and concatenate them. (Idk if they’re allowed to overlap or not)

**Comment by ivirshup** [comment]
As another workaround, you could store the values of `.raw.X` into `layers`.

**Comment by sjfleming** [comment]
Just to throw in my two cents here... my use case was that I do a pre-processing step on my data to [remove ambient RNA](https://cellbender.readthedocs.io/en/latest/), and this pre-processed count matrix gets stored in the `adata.X` slot.  However, I also want the real raw count data for comparisons downstream, so I want to always keep that in the `adata.raw` slot.  I have a lot of separate datasets I want to aggregate together.

My "workaround" was

```python
adatas = []
adatas_raw = []

for s in samples:

    # load the current dataset, pre-processed data
    adata_tmp = sc.read_10x_h5(preprocessed_files[s])
    
    # load the current dataset, raw count data
    adata_raw_tmp = sc.read_10x_h5(raw_files[s])
    
    # add these to lists 
    adatas.append(adata_tmp)
    adatas_raw.append(adata_raw_tmp)

# the big concatenation
adata = AnnData.concatenate(*adatas)

# and fill in the raw slot by separately concatenating all the raw data
adata.raw = AnnData.concatenate(*adatas_raw)
```

As it is, this is not difficult, and I'm fine with it.

But... compared to the desired behavior I was hoping for:

```python
adatas = []

for s in samples:

    # load the current dataset, pre-processed data
    adata_tmp = sc.read_10x_h5(preprocessed_files[s])
    
    # populate the .raw slot with raw count data
    adata_tmp.raw = sc.read_10x_h5(raw_files[s])
    
    # add dataset to the list
    adatas.append(adata_tmp)

# the big concatenation
adata = AnnData.concatenate(*adatas)

# at this point, I would hope that the .raw slot is properly populated with the concatenated .raw slots of all the individual datasets
```

The nice thing here would be that the .raw data never leaves its corresponding pre-processed dataset, and so there's no chance for me to mess up the order of lists when concatenating and get something screwed up.

**Comment by LuckyMD** [comment]
Hi @sjfleming,

It sounds like in your use case, you could use `adata.layers` as I would assume that removal of ambient RNA doesn't change the number of features in your dataset, but only changes the expression matrix. If you store the original data in a different layer, concatenation should work out of the box. The only caveat is that e.g., `adata.layers['raw']` has to have the same dimensions as `adata.X`.

**Comment by sjfleming** [comment]
This sounds like a perfect solution for me.  I did not know about `adata.layers`!  Thanks @LuckyMD  @ivirshup

**Comment by flying-sheep** [comment]
Great!
