### ISSUE TITLE
Write error

### ISSUE THREAD

**Issue by falexwolf** [theislab/anndata#213]
Pasting this, unfortunately, without a minimal example as I can't even write the data.

But the error message is quite clear and it maybe you'll spot the thing immediately. If not, let me think about a case in which I can reproduce it.
```pytb
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-17-29fdb1c29373> in <module>
----> 1 adata.write('./test.h5ad')

/mnt/data/repos/anndata/anndata/core/anndata.py in write_h5ad(self, filename, compression, compression_opts, force_dense)
   2064 
   2065         _write_h5ad(filename, self, compression=compression,
-> 2066                     compression_opts=compression_opts, force_dense=force_dense)
   2067 
   2068         if self.isbacked:

/mnt/data/repos/anndata/anndata/readwrite/h5ad.py in write_h5ad(filepath, adata, force_dense, dataset_kwargs, **kwargs)
     86             # Otherwise, X should already be up to date
     87             write_attribute(f, "X", adata.X, dataset_kwargs)
---> 88         write_attribute(f, "obs", adata.obs, dataset_kwargs)
     89         write_attribute(f, "var", adata.var, dataset_kwargs)
     90         write_attribute(f, "obsm", adata.obsm, dataset_kwargs)

/mnt/data/repos/anndata/anndata/readwrite/h5ad.py in write_attribute(f, key, value, dataset_kwargs)
    106     if key in f:
    107         del f[key]
--> 108     _write_method(type(value))(f, key, value, dataset_kwargs)
    109 
    110 

/mnt/data/repos/anndata/anndata/readwrite/h5ad.py in write_dataframe(f, key, df, dataset_kwargs)
    169     write_series(group, index_name, df.index, dataset_kwargs)
    170     for colname, series in df.items():
--> 171         write_series(group, colname, series, dataset_kwargs)
    172 
    173 

/mnt/data/repos/anndata/anndata/readwrite/h5ad.py in write_series(f, key, series, dataset_kwargs)
    184         f.create_dataset(key, shape=series.shape, dtype=series.cat.codes.dtype)
    185         f[key][:] = series.cat.codes
--> 186         f[key].attrs["categories"] = list(series.cat.categories)
    187     else:
    188         f[key] = series.values

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

~/data/miniconda3/lib/python3.7/site-packages/h5py/_hl/attrs.py in __setitem__(self, name, value)
     98         use the methods create() and modify().
     99         """
--> 100         self.create(name, data=value)
    101 
    102     @with_phil

~/data/miniconda3/lib/python3.7/site-packages/h5py/_hl/attrs.py in create(self, name, data, shape, dtype)
    199 
    200             try:
--> 201                 attr = h5a.create(self._id, self._e(tempname), htype, space)
    202             except:
    203                 raise

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/h5a.pyx in h5py.h5a.create()

RuntimeError: Unable to create attribute (object header message is too large)
```

**Comment by ivirshup** [comment]
Sorry about that! I think I actually just saw this trying to write @jorvis's file from #52. It looks like hdf5 doesn't storing a large amount of data in an `attrs`, but there are a large amount of categories being stored there.

**Comment by ivirshup** [comment]
@flying-sheep, looks like we might end up using the hdf5 enums after all. I can get them to work (with minor testing) with a large amount of categories, but we've got to do things like specify the byte width of the categories. On the plus side, h5py `v2.10.0` improved the api for hdf5 special dtypes.

**Comment by flying-sheep** [comment]
5000 is not much -.- Did you check that the enums can handle it?

**Comment by ivirshup** [comment]
Enums can handle that example, but there is an upper limit. It looks like the limit for enums comes from datatypes having maximum size, so if there are either many categories or they have long enough names enums also fail. I'm not sure if this is a limitation of hdf5 or h5py at the moment. There's a hard limit on compound dtypes size (for hdf5) of 2^32 bytes, which I would guess applies here as well.

I think the thing to do here will be have another dataset stored in the data frame Group which has the categories in it, then have a pointer in the attrs of the code dataset to the category dataset.

**Comment by falexwolf** [comment]
Oh, I get the error. I was also afraid back at the time that storing categories directly in the hdf5 attrs might hit limits. That's why I stored it as a standard dataset in `.uns`, which wasn't great, obviously.

I like the suggestion of having it be a another dataset in the DataFrame Group. :)
