### ISSUE TITLE
Byte strings

### ISSUE THREAD

**Issue by falexwolf** [theislab/anndata#215]
A lot of my old `.h5ad` files are now loaded with byte string indices.

In the beginning, there was some confusion about whether h5py would support unicode at all and this is how the transformation to str at loading time came about.

I agree that this shouldn't be the default behavior for the updated file format. If someone wants byte strings, they should get byte strings.

However, it would be super nice to have it still activated when reading the old file format, for backwards compat reasons. In fact, the byte strings are breaking a lot of code. Also, if someone then reads the old file format and has the autotransform to `str` and writes to the new format, things will behave as users want it (that is, they need to explicitly transform to byte strings, in case they want that).

What do you think?

**Comment by ivirshup** [comment]
I think this sounds good in general, but could use a few points of clarification to be sure.

> A lot of my old .h5ad files are now loaded with byte string indices.

* Is it only the indices? 
* How old of files are these?
* Could you give examples of code that breaks?

**Comment by ivirshup** [comment]
Oh, I'm also starting to see that `h5py==2.10.0` sometimes reads byte strings where `h5py<2.10.0` did not. Is it possible that's contributing to the errors?

**Comment by ivirshup** [comment]
This should have been fixed by #217. Please let me know if you still see these issues!

**Comment by atarashansky** [comment]
I ran into this same issue again when `h5py` upgraded to `3.0.0`.

**Comment by ivirshup** [comment]
@atarashansky some other people have run into this as well, tracking under #442

**Comment by giovp** [comment]
just had same issue but saw PR is already merged, thanks @ivirshup !
