### ISSUE TITLE
AnnData.concatenate breaks if first matrix is dense and second sparse

### ISSUE THREAD

**Issue by le-ander** [theislab/anndata#226]
I was trying to concatenate two anndata objects, one of which has X stored as a dense matrix and the other one as a sparse one. This is currently not properly handled by anndata and raises an error:

```python
import scanpy as sc
import numpy as np
from scipy.sparse import csr_matrix

a1 = sc.datasets.paul15()
a2 = sc.datasets.paul15()

a1.X = np.array(a1.X)
a2.X = csr_matrix(a2.X).copy()

a1.concatenate(a2)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-11-c31a823598c1> in <module>
      9 a2.X = csr_matrix(a2.X).copy()
     10 
---> 11 a1.concatenate(a2)

~/python/lib/python3.6/site-packages/anndata/core/anndata.py in concatenate(self, join, batch_key, batch_categories, index_unique, *adatas)
   1908 
   1909         if any_sparse:
-> 1910             sparse_format = all_adatas[0].X.getformat()
   1911             X = X.asformat(sparse_format)
   1912 

AttributeError: 'numpy.ndarray' object has no attribute 'getformat'
```

The problem occurs here:
https://github.com/theislab/anndata/blob/914d7375a93ca617bd6dee1565097656e6e1d359/anndata/core/anndata.py#L2096
https://github.com/theislab/anndata/blob/914d7375a93ca617bd6dee1565097656e6e1d359/anndata/core/anndata.py#L2097

`sparse_Xs` in this case is [False, True], this gets evaluated as True in the if statement above, however the sparse format is then determined on the dense array, which consequently breaks.

**Comment by flying-sheep** [comment]
Did you try the current git master version? Pretty sure this is fixed.

**Comment by le-ander** [comment]
fixed indeed, thanks :)
