### ISSUE TITLE
show gene expression in a subset of cells

### ISSUE THREAD

**Issue by wangjiawen2013** [theislab/anndata#240]
Dear,
how to show gene expression levels in only a subset of cells (eg. cluster 1,2 while other clusters are hidden) ?

**Comment by LuckyMD** [comment]
You could subset the anndata object via:
`adata_sub = adata[adata.obs.cluster.isin(['1','2']),:]`
Then you can just plot the expression values of `adata_sub`.

**Comment by gokceneraslan** [comment]
It'd be great if we could use https://scanpy.discourse.group/ for this kind of questions and answers.

**Comment by flying-sheep** [comment]
yes

**Comment by sergiopolid** [comment]
HI @LuckyMD, quick question. After subsetting with the command: adata_sub = adata[adata.obs.cluster.isin(['1','2']),:]

I get a dataset with the subset of genes identify as variable in the 'adata', so this are not necessary the genes I would like to focus for this particular subset. How could I create a subset with all the genes prior to the filtering step?

**Comment by LuckyMD** [comment]
So the step `adata[adata.obs.cluster.isin(['1','2']),:]` does not filter out any genes. You would have to use the `adata` object from before your filtering step and transfer the louvain cluster id's via something like: `adata_unfiltered.obs['cluster'] = adata.obs['cluster']`. And then do the above on `adata_unfiltered`. Note that this only works if both objects have the same number of cells and the same `adata.obs_names`.
