### ISSUE TITLE
write_loom() minor bug

### ISSUE THREAD

**Issue by TobiTekath** [theislab/anndata#246]
Hi,

I just stumbled upon a minor bug in `write_loom()`:

https://github.com/theislab/anndata/blob/106d347971827d6cd1cc620e7a969669801c350c/anndata/readwrite/write.py#L104-L108

is producing an error, as `.keys()` returns a `KeysView` object, where `+` is not defined (`TypeError: unsupported operand type(s) for +: 'KeysView' and 'KeysView'`).

A very easy workaround would be to replace line 107 with:

`f'{list(adata.obsm) + list(adata.varm)}\n'`

Thanks.
___________________________________________
`VersionInfo: scanpy==1.4.4 anndata==0.6.22.post1`

**Comment by flying-sheep** [comment]
Thanks, but we should rather do `adata.obsm.keys() | adata.varm.keys()`

**Comment by yuqiyuqitan** [comment]
Is the bug fixed? I also just ran into this error.

**Comment by flying-sheep** [comment]
yeah, on master

**Comment by MichaelPeibo** [comment]
Hi! Any concise way to convert to loom avoiding this bug and without installing master version?
Thanks!
