### ISSUE TITLE
anndata 适配于 python2.7 的版本是不可用的, 有非常多的错误.

### ISSUE THREAD

**Issue by mr0jue** [theislab/anndata#253]
如题, 我想要在python2.7中使用anndata, 但是conda install 的anndata 版本有很多的错误. 我尝试修改, 但是太多(错误)了

**Comment by mr0jue** [comment]
我使用的是linux系统

**Comment by ivirshup** [comment]
We don't support python 2.7 for AnnData, and don't have plans to. Sorry!

(Going off Google Translate here, hopefully I got that right 😄)

**Comment by flying-sheep** [comment]
Yup:

- [Python 2 will retire in ~40 days](https://pythonclock.org/)
- [Numpy, Pandas, … will stop supporting Python 2 before this year ends](https://python3statement.org/)

**Comment by mr0jue** [comment]
OK, I got it. I think it would be wise not to support py2.(yeh, Google translation is useful.)
