### ISSUE TITLE
Suggestion: everything as a sparse matrix by default

### ISSUE THREAD

**Issue by kridsadakorn** [theislab/anndata#255]
Dealing with big data is quite tricky, it always ends up with a memory issue. Isn't it a good idea to have everything as a sparse matrix automatically and transparently, eg. read, write, etc.?

**Comment by LuckyMD** [comment]
Every dataset we have is in sparse format as far as I'm aware at least...

**Comment by flying-sheep** [comment]
I think so to, but let’s let this discussion open for more perspectives

**Comment by kridsadakorn** [comment]
> Most large datasets we use are in sparse format initially as far as I'm aware at least... I don't think we should enforce it though. There are a lot of methods that return non-sparse data matrices like imputation, batch correction, data integration etc. We have to support that.

Sorry, not precise enough for what I said. I mean when the data are in the memory it can be whatever; dense or sparse. But when it comes to deal with I/O shouldn't it be better to be in sparse format by default? Even better sparse + compression? It will help a lot with the data traffic during I/O time as well as space. Also, we won't use something like ```cat``` or ```vim``` to view the file, rather do via the API anyway. Perhaps, any beneficial point of view to store the data in an uncompressed dense format that I might have missed?

**Comment by flying-sheep** [comment]
If there’s not a significant number of zeros, sparse storage is larger than dense storage:

https://gist.github.com/flying-sheep/f46e89b388fed736ff0b68fb8fd83af6

The main plot. Blue/green means smaller memory/storage use in a dense array (not much, only up to 1.5 in reasonably sized matrices, but it’s also more efficient to do operations on dense arrays). Obviously the sparser you get (orange/red) the more efficient sparse matrices are.

![image](https://user-images.githubusercontent.com/291575/69424460-f5af9800-0d28-11ea-83c0-36c21b0764c4.png)

**Comment by kridsadakorn** [comment]
Nice to see this. Indeed it is difficult to say dense or sparse, it is data dependence. Otherwise, it needs to be like a self-decision function based on the model (the plot) above. Perhaps forget about it, difficult to implement + there will be a bit of overhead.

**Comment by flying-sheep** [comment]
I think so too. We should let the user decide.
