### ISSUE TITLE
AnnData exception in sc.pp.pca

### ISSUE THREAD

**Issue by gokceneraslan** [theislab/anndata#257]
When I subset an anndata and run PCA, I get this exception sometimes:

![image](https://user-images.githubusercontent.com/1140359/69362115-e44c8a00-0c5b-11ea-8735-e61909e64a5a.png)

Any ideas?

**Comment by gokceneraslan** [comment]
Only happens if PCA uses HVGs and if there is a categorical variable with a single category (due to subsetting)

**Comment by flying-sheep** [comment]
Btw, you can use the following to highlight errors instead of pasting images:

````markdown
```pytb
-----------------------------------------------------
FooError            Traceback (most recent call last)
...
```
````

**Comment by gokceneraslan** [comment]
```python
import scanpy as sc

adata = sc.datasets.paul15()
sc.pp.log1p(adata)
sc.pp.pca(adata)
sc.pp.neighbors(adata)
sc.tl.leiden(adata)
sc.pl.pca(adata, color='leiden')

ad = adata[adata.obs.leiden.isin(('5', '10'))].copy()
sc.tl.leiden(ad)
sc.pp.highly_variable_genes(ad, n_top_genes=100)
sc.pp.pca(ad)
```

```pytb
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-30-4dceb039a21d> in <module>
     11 sc.tl.leiden(ad)
     12 sc.pp.highly_variable_genes(ad, n_top_genes=100)
---> 13 sc.pp.pca(ad)

~/Library/Python/3.7/lib/python/site-packages/scanpy/preprocessing/_simple.py in pca(data, n_comps, zero_center, svd_solver, random_state, return_info, use_highly_variable, dtype, copy, chunked, chunk_size)
    467     if use_highly_variable:
    468         logg.info('computing PCA on highly variable genes')
--> 469     adata_comp = adata[:, adata.var['highly_variable']] if use_highly_variable else adata
    470 
    471     if chunked:

~/Library/Python/3.7/lib/python/site-packages/anndata/core/anndata.py in __getitem__(self, index)
   1406         """Returns a sliced view of the object."""
   1407         oidx, vidx = self._normalize_indices(index)
-> 1408         return AnnData(self, oidx=oidx, vidx=vidx, asview=True)
   1409 
   1410     def _remove_unused_categories(self, df_full, df_sub, uns):

~/Library/Python/3.7/lib/python/site-packages/anndata/core/anndata.py in __init__(self, X, obs, var, uns, obsm, varm, layers, raw, dtype, shape, filename, filemode, asview, obsp, varp, oidx, vidx)
    619             if not isinstance(X, AnnData):
    620                 raise ValueError('`X` has to be an AnnData object.')
--> 621             self._init_as_view(X, oidx, vidx)
    622         else:
    623             self._init_as_actual(

~/Library/Python/3.7/lib/python/site-packages/anndata/core/anndata.py in _init_as_view(self, adata_ref, oidx, vidx)
    674         self._slice_uns_sparse_matrices_inplace(uns_new, self._oidx)
    675         # fix categories
--> 676         self._remove_unused_categories(adata_ref.obs, obs_sub, uns_new)
    677         self._remove_unused_categories(adata_ref.var, var_sub, uns_new)
    678         # set attributes

~/Library/Python/3.7/lib/python/site-packages/anndata/core/anndata.py in _remove_unused_categories(self, df_full, df_sub, uns)
   1426                     np.in1d(all_categories, df_sub[k].cat.categories)
   1427                 )[0]
-> 1428             uns[f'{k}_colors'] = np.array(uns[f'{k}_colors'])[(idx,)]
   1429 
   1430     def rename_categories(self, key: str, categories: Sequence[Any]):

IndexError: index 2 is out of bounds for axis 0 with size 2

```

**Comment by flying-sheep** [comment]
Thank you. Sadly I currently have numba problems (It seems to break with Python 3.8), so I can’t help at the moment.

**Comment by ivirshup** [comment]
@gokceneraslan, I think I've seen this before, but thought it was solved by https://github.com/theislab/anndata/pull/168. Are you using release or development AnnData?

**Comment by ivirshup** [comment]
Guess not, I can reproduce. I know how I want to fix it (`*_colors` should be a dict, not a list), but that would be breaking... I'll look into it

**Comment by ivirshup** [comment]
Ah, I see what it is. The clustering was recalculated but the colors weren't, but we expected the number of colors to match the number of clusters. That's a bit of a silly assumption, but easy enough to fix 

If there are more clusters than colors, we'll just delete the existing colors because they must be incorrect. This is what the plotting functions do anyways.

**Comment by gokceneraslan** [comment]
I think colors should be recalculated, these leiden clusters are completely different than the previous ones.

**Comment by ivirshup** [comment]
That should be the effect of deleting the color vector in `uns`. Colors are calculated when a plotting function is called.

I think it would make sense if even generating the clusters removed the old color vector, but I'd like to have more holistic look at how we do colors before trying that. I think it may make the most sense if the color mapping was stored with the categorical vector, which is something we could do if we're able to use Xarray as the backend.

**Comment by gokceneraslan** [comment]
`len(color_vec) < len(all_categories):` check in the PR is not optimal. See the "wrong" colors below:

![image](https://user-images.githubusercontent.com/1140359/69479378-7c688180-0dca-11ea-980e-c243e66c081d.png)

> I think it would make sense if even generating the clusters removed the old color vector, but I'd like to have more holistic look at how we do colors before trying that.

Exactly.

**Comment by gokceneraslan** [comment]
Here is also the same, no exception but misleading colors. sc.tl.leiden call in-between might potentially change everything.

![image](https://user-images.githubusercontent.com/1140359/69479584-df5b1800-0dcc-11ea-8801-ca481a605a23.png)

**Comment by ivirshup** [comment]
So my fix just keeps the current behavior. I figured I'd just keep it the same until I had a better overall solution.

However, I also don't particularly like this behavior, as it sticks you with the ugly high-number-of-clusters color palettes frequently.  @flying-sheep, @falexwolf any objections to going with @gokceneraslan suggestion?

**Comment by flying-sheep** [comment]
see PR
