### ISSUE TITLE
How to call/subset by concatenate category?

### ISSUE THREAD

**Issue by sfortma2** [theislab/anndata#261]
Hi,
I am fairly new to scanpy and am having trouble calling individual batches after concatenating. I have saved the batch identifier under the obs category "sample_id" using default settings. I have 3 batches labeled "0", "1", and "2". I would like to be able to call individual batches so that for example I can just show clustering from one batch. I am able to call the obs "sample_id" using "adata.obs.sample_id" but I cannot figure out how to call just dataset "1" for example. Any help would be greatly appreciated and my apologies for the noob question. I've read many documents and tried numerous strings but I can't seem to figure it out.
- Seth

**Comment by ivirshup** [comment]
Are you looking for something like: `adata[adata.obs.query("sample_id == '1'")]`? That will return a view of just those samples.

I believe there are also arguments to the plotting functions (`groups` for `sc.pl.umap`) that can make this nicer. You could also try something like [this example](https://github.com/theislab/scanpy/issues/759#issuecomment-516742486).

**Comment by sfortma2** [comment]
@ivirshup thanks so much! The example was very helpful.

**Comment by ivirshup** [comment]
No problem!
