### ISSUE TITLE
read_h5ad takes forever and do not give an error

### ISSUE THREAD

**Issue by chenlingantelope** [theislab/anndata#282]
```
from anndata import read_h5ad
ss2 = read_h5ad('endopancreas.Endothelial.h5ad')

import scanpy as sc
sc.api.read('endopancreas.Endothelial.h5ad')

import anndata
anndata.read('endopancreas.Endothelial.h5ad')

```
All of these will run on for a long time without giving any error, but if I remove the "." then it works normally.

**Comment by flying-sheep** [comment]
what version of anndata do you use?

**Comment by ivirshup** [comment]
I can't reproduce this behavior. @chenlingantelope, are you still experiencing this?
