### ISSUE TITLE
AnnData.write("*.h5") cannot save var_names or obs_names of the AnnData object

### ISSUE THREAD

**Issue by Tianran1** [theislab/anndata#283]
After using the AnnData.write function to save the object to h5 file, when I read the saved h5 file, I found the var_names and obs_names of the original matrix are not saved in the h5 file. Why this occurs?

**Comment by ivirshup** [comment]
What should be happening is that the `obs_names` and `var_names` are saved inside the group corresponding to the `obs` and `var` data-frames respectively. Does that answer your question?

If not, would you mind providing an example of what you're seeing? Try running `h5ls -r` on the output file and we'll be able to see the structure.
