### ISSUE TITLE
Slicing of raw data throws (new) error

### ISSUE THREAD

**Issue by alexblaessle** [theislab/anndata#288]
Hi,

I recently upgraded anndata and now have a hard time slicing raw data.

I am trying to get the expression values of a single gene from the ``adata.raw`` data, and so far it worked via ``adata.raw[:,gene_name].X``. However, now it throws,

````pytb
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-112-a6fcd8ac0202> in <module>
----> 1 adata.raw[:,'Ezr'].X

~/.local/lib/python3.6/site-packages/anndata/_core/raw.py in __getitem__(self, index)
    111         if self._varm is not None:
    112             # Since there is no view of raws
--> 113             new._varm = self._varm._view(self, (vidx,)).copy()
    114         return new
    115 

~/.local/lib/python3.6/site-packages/anndata/_core/aligned_mapping.py in copy(self)
     84         d = self._actual_class(self.parent, self._axis)
     85         for k, v in self.items():
---> 86             d[k] = v.copy()
     87         return d
     88 

~/.local/lib/python3.6/site-packages/anndata/_core/aligned_mapping.py in __setitem__(self, key, value)
    148 
    149     def __setitem__(self, key: str, value: V):
--> 150         value = self._validate_value(value, key)
    151         self._data[key] = value
    152 

~/.local/lib/python3.6/site-packages/anndata/_core/aligned_mapping.py in _validate_value(self, val, key)
    212                 f"value.index does not match parent’s axis {self.axes[0]} names"
    213             )
--> 214         return super()._validate_value(val, key)
    215 
    216 

~/.local/lib/python3.6/site-packages/anndata/_core/aligned_mapping.py in _validate_value(self, val, key)
     50                 right_shape = tuple(self.parent.shape[a] for a in self.axes)
     51                 raise ValueError(
---> 52                     f"Value passed for key {key!r} is of incorrect shape. "
     53                     f"Values of {self.attrname} must match dimensions "
     54                     f"{self.axes} of parent. Value had shape {val.shape} while "

ValueError: Value passed for key 'PCs' is of incorrect shape. Values of varm must match dimensions (1,) of parent. Value had shape (1, 40) while it should have had (21725,).
````

Any idea what I am doing wrong or is there a new way how to do this?

Thanks in advance!

**Comment by falexwolf** [comment]
This might be related to you `adata` being a view. Can you make an actual object using `adata.copy()`? Sorry that views still seems buggy. Will work on it!

**Comment by alexblaessle** [comment]
Hey,

thanks for getting back so quickly!

I tried

````
adata2=adata.copy()
adata2.raw[:,'Ezr']

````

Still same error message.

I am not sure if my ``adata`` is a view. 
````
type(adata)
````
returns``anndata._core.anndata.AnnData``, so it seems to be a normal anndata object.

**Comment by falexwolf** [comment]
Thank you! Can reproduce
![image](https://user-images.githubusercontent.com/16916678/71968540-6ccfbb80-3205-11ea-8274-10fc1421a41c.png)

This is for copy and paste (@ivirshup)
```
a = anndata.AnnData(np.ones((4, 3)))
# a.varm['PCs'] = np.ones((3, 3))  # uncommenting this line generates the error
a.raw = a
b = a.raw[:, '0']
```

Three solutions: 
* downgrade to anndata `0.6.22.post1` (scanpy will run with the old anndata).
* delete the `PCs` from your raw object `del a.raw.varm['PCs']`
* store the raw object as an additional `adata_raw = adata.raw.to_adata()` and unset it `adata.raw = None`
* wait for Isaac to fix the bug!

Sorry, 0.7 is still an rc and it was an omission to have it in the Scanpy requirements. It's not actually required by Scanpy 1.4.5. We'll fix this with a post-release.

**Comment by flying-sheep** [comment]
Please create a reproducible example that uses only publicly available data (optimally just some ndarrays and/or DataFrames created on the fly)

```py
AnnData(<insert_code_here>).write('test.h5ad')
```

**Comment by flying-sheep** [comment]
Yeah it’s that “We don’t have views of Raws” bug:

https://github.com/theislab/anndata/blob/cb382437a38ec49b68faafb8463d2490007876de/anndata/_core/raw.py#L111-L113

This shouldn’t use “self”, but instead a hypothetical RawView.

**Comment by alexblaessle** [comment]
Thanks! I will try it out later!
