### ISSUE TITLE
Remove obsm

### ISSUE THREAD

**Issue by chriscainx** [theislab/anndata#29]
Hey guys,

What's the easiest way to remove a field in adata.obsm?
for example, I have 
```
AnnData object with n_obs × n_vars = 48011 × 25583 
    obs: 'n_genes', 'n_counts', 'percent_mito', 'Sample', 'Donor', 'Tissue', 'batch', 'DCA_split', 'size_factors'
    var: 'gene_ids', 'n_counts'
    uns: 'DCA_losses'
    obsm: 'X_dca', 'X_dca_mean', 'X_dca_hidden', 'X_dca_dropout', 'X_dca_dispersion'
```
and I just want to remove the items in obsm to reduce memory consumption.

**Comment by flying-sheep** [comment]
`del adata.obsm['X_dca']` doesn’t work?

**Comment by falexwolf** [comment]
I fear it doesn't work. We could add `__delete__` using the previous implementation, which I removed at some point for some reason...

https://github.com/theislab/anndata/blob/d1f28b84780ab782c788772031ac019beaadf7eb/anndata/ann_data.py#L211-L219

If you have the bandwidth to do so, Phil, than go ahead... I'll be basically offline on holidays for the next week.

**Comment by flying-sheep** [comment]
You deleted it in 9ae684e811a51bb7575416d8b21c088c03befc2e, because you changed everything there :wink: on it

**Comment by falexwolf** [comment]
Oh so great that you restored it @flying-sheep!

**Comment by falexwolf** [comment]
Ah, and regarding the commit you linked, @flying-sheep; this is the commit where I moved from BoundRecArrays to DataFrames for `.obs`. Just a bit later I reintroduced a minimal version of BoundRecArray (without the "manual" index) for `.obsm`, so that multi-dimensional annotations would be restored.
