### ISSUE TITLE
KeyError when obs and var have the same column name - read_h5ad

### ISSUE THREAD

**Issue by ridvaneksi** [theislab/anndata#304]
Trying to read a h5ad file, who has a column under obs and var with categorical data with the same column name. "compat.py" Line 120 raises KeyError, because it's trying to delete same key twice. 
An easy fix is to remove duplicates from the list "k_to_delete" right before the loop.

**Comment by ivirshup** [comment]
Potentially the same issue raised in #277, and should be fixed by #278.

@flying-sheep, since you were looking at that PR, want to add a test and merge it?

**Comment by flying-sheep** [comment]
@ridvaneksi please check if that commit “fixed” it. The fix was purely speculative as I had no old .h5ad with that property to test with.

**Comment by ridvaneksi** [comment]
it's fixed now. thanks.

**Comment by flying-sheep** [comment]
Great!
