### ISSUE TITLE
Anndata vs Xarray

### ISSUE THREAD

**Issue by firmai** [theislab/anndata#308]
I have been sent here by a friend, but I still don't fully understand the purpose of the project. In which way is it different to Xarray. Is it a speed, functionality? Could it all simply be done in structured numpy? Are they all faster than Pandas?

**Comment by flying-sheep** [comment]
See [the documentation](https://anndata.readthedocs.io/en/stable/anndata.AnnData.html):

> AnnData stores a data matrix X together with annotations of observations obs (obsm, obsp), variables var (varm, varp), and unstructured annotations uns.
https://falexwolf.de/img/scanpy/anndata.svg
> 
> An AnnData object adata can be sliced like a DataFrame, for instance `adata_subset = adata[:, list_of_variable_names]`. AnnData’s basic structure is similar to R’s ExpressionSet [[Huber15]](https://anndata.readthedocs.io/en/stable/references.html#huber15). If setting an .h5ad-formatted HDF5 backing file .filename, data remains on the disk but is automatically loaded into memory if needed. See this [blog post](http://falexwolf.de/blog/171223_AnnData_indexing_views_HDF5-backing/) for more details.

**Comment by ivirshup** [comment]
@firmai, I think it's fair to say xarray is meant to be more general than AnnData. We don't particularly care about n-dimensional data, but we do care about two dimensional arrays, and especially having good performance with sparse formats. We also are more focussed on biology than geographic data. I think we contribute to the same upstream libraries, and I'd like to use xarray as once it's better with sparse arrays.

Why do you ask?
