### ISSUE TITLE
could not convert integer scalar

### ISSUE THREAD

**Issue by brianpenghe** [theislab/anndata#339]
adata=adata[:,~mito_genes]
I was running 
```py
sc.pp.filter_cells(adata, min_genes=200)
```
And got this error:
```pytb
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-16-bc34931b4970> in <module>
----> 1 sc.pp.filter_cells(adata, min_genes=200)
      2 sc.pp.filter_genes(adata, min_cells=3)

/usr/local/lib/python3.6/dist-packages/scanpy/preprocessing/_simple.py in filter_cells(data, min_counts, min_genes, max_counts, max_genes, inplace, copy)
    123     if isinstance(data, AnnData):
    124         adata = data.copy() if copy else data
--> 125         cell_subset, number = materialize_as_ndarray(filter_cells(adata.X, min_counts, min_genes, max_counts, max_genes))
    126         if not inplace:
    127             return cell_subset, number

/usr/local/lib/python3.6/dist-packages/anndata/_core/anndata.py in X(self)
    577         elif self.is_view:
    578             X = as_view(
--> 579                 _subset(self._adata_ref.X, (self._oidx, self._vidx)),
    580                 ViewArgs(self, "X"),
    581             )

/usr/lib/python3.6/functools.py in wrapper(*args, **kw)
    805                             '1 positional argument')
    806 
--> 807         return dispatch(args[0].__class__)(*args, **kw)
    808 
    809     funcname = getattr(func, '__name__', 'singledispatch function')

/usr/local/lib/python3.6/dist-packages/anndata/_core/index.py in _subset(a, subset_idx)
    124     if all(isinstance(x, cabc.Iterable) for x in subset_idx):
    125         subset_idx = np.ix_(*subset_idx)
--> 126     return a[subset_idx]
    127 
    128 

/usr/local/lib/python3.6/dist-packages/scipy/sparse/_index.py in __getitem__(self, key)
     73         if row.size == 0:
     74             return self.__class__(np.atleast_2d(row).shape, dtype=self.dtype)
---> 75         return self._get_arrayXarray(row, col)
     76 
     77     def __setitem__(self, key, x):

/usr/local/lib/python3.6/dist-packages/scipy/sparse/compressed.py in _get_arrayXarray(self, row, col)
    663         val = np.empty(major.size, dtype=self.dtype)
    664         csr_sample_values(M, N, self.indptr, self.indices, self.data,
--> 665                           major.size, major.ravel(), minor.ravel(), val)
    666         if major.ndim == 1:
    667             return asmatrix(val)

ValueError: could not convert integer scalar
```

Any ideas?

**Comment by ivirshup** [comment]
Not sure. Could you follow up with these?

* Software versions for scanpy, anndata, scipy, and numpy
* `type(adata)` and `type(adata.X)`

**Comment by brianpenghe** [comment]
> Not sure. Could you follow up with these?
> 
> * Software versions for scanpy, anndata, scipy, and numpy
> * `type(adata)` and `type(adata.X)`
> 
> Also, does it work if you do:
> 
> ```python
> adata = adata.copy()
> sc.pp.filter_cells(adata, min_genes=200)
> ```

`.copy()`
worked!

**Comment by abuchin** [comment]
I have the same problem, but when I run

adata = adata.copy()

it shows the same problem:

...
~/anaconda2/envs/p7/lib/python3.7/site-packages/scipy-1.4.1-py3.7-macosx-10.9-x86_64.egg/scipy/sparse/compressed.py in _get_arrayXarray(self, row, col)
    663         val = np.empty(major.size, dtype=self.dtype)
    664         csr_sample_values(M, N, self.indptr, self.indices, self.data,
--> 665                           major.size, major.ravel(), minor.ravel(), val)
    666         if major.ndim == 1:
    667             return asmatrix(val)

ValueError: could not convert integer scalar
...

scanpy: 1.4.7.dev63+g0a6bf5ac
anndata: Version('0.7.1')
scipy: 1.4.1
numpy: 1.18.4

**Comment by abuchin** [comment]
Somehow the problem got solved when I updated these libraries.

**Comment by ivirshup** [comment]
Thanks for letting us know!

**Comment by dbdimitrov** [comment]
Installing a different scipy version seemed to solve this issue for me :)

Issue was encountered on `scipy-1.17.0` on Ubuntu 24.04, downgrading to `1.16.0` solved it.

**Comment by flying-sheep** [comment]
could you please 1. create a reproducer (runnable by itself, doesn’t access data we don’t have access to) and 2. paste the output of the command below?

```py
import session_info2, anndata
print(session_info2.session_info(dependencies=True)._repr_mimebundle_()["text/markdown"])
```

if you do, we might have a chance to reproduce this and maybe fix it or improve the error message.

**Comment by Jiung-Wen** [comment]
I had the same issue, and @dbdimitrov's trick worked for me by downgrading scipy from 1.17.0 to 1.16.0.

**Comment by LucaMarconato** [comment]
I also just encountered this problem with `scipy==1.17.0`, I will try to distill a MRE.

**Comment by LucaMarconato** [comment]
Not minimal, but this should be an effective way to reproduce the issue: 

1. download this [~400MB adata object from here](https://drive.google.com/file/d/1yzdyc3xFAEvEEtZLIMgj1UYvEOAvsJc8/view?usp=drive_link). For context it's a Visium HD datasets [processed using `spatialdata` here ](https://github.com/scverse/spatialdata-notebooks/blob/main/notebooks/examples/technology_visium_hd_mouse_4.0.1.ipynb), originally [published from 10x](https://www.10xgenomics.com/datasets/visium-hd-three-prime-mouse-brain-fresh-frozen).
2. run this code:
```python
import anndata
table = anndata.read_h5ad('bug.h5ad')
table[table.obs['region'].isin(['Visium_HD_3prime_Mouse_Brain_cell_segmentations'])].copy()
```

After 1 minute it should give you the error above.

<details>
  <summary>Full traceback.</summary>
  
```pytb
Traceback (most recent call last):
  File "/opt/miniconda3/envs/ome_sdc/lib/python3.13/site-packages/IPython/core/interactiveshell.py", line 3701, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
    ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<ipython-input-3-664a302bbfc6>", line 1, in <module>
    table[table.obs[region_key].isin(element_names)].copy()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/opt/miniconda3/envs/ome_sdc/lib/python3.13/site-packages/anndata/_core/anndata.py", line 1492, in copy
    return self._mutated_copy(
           ~~~~~~~~~~~~~~~~~~^
        X=_subset(self._adata_ref.X, (self._oidx, self._vidx)).copy()
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/opt/miniconda3/envs/ome_sdc/lib/python3.13/site-packages/anndata/_core/anndata.py", line 1423, in _mutated_copy
    new[key] = getattr(self, key).copy()
               ~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/opt/miniconda3/envs/ome_sdc/lib/python3.13/site-packages/anndata/_core/aligned_mapping.py", line 126, in copy
    k: copy(v) if isinstance(v, AwkArray) else v.copy() for k, v in self.items()
                                                                    ~~~~~~~~~~^^
  File "<frozen _collections_abc>", line 899, in __iter__
  File "/opt/miniconda3/envs/ome_sdc/lib/python3.13/site-packages/anndata/_core/aligned_mapping.py", line 164, in __getitem__
    _subset(self.parent_mapping[key], self.subset_idx),
    ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/ome_sdc/lib/python3.13/functools.py", line 929, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/ome_sdc/lib/python3.13/site-packages/anndata/_core/index.py", line 202, in _subset_sparse
    return a[subset_idx]
           ~^^^^^^^^^^^^
  File "/opt/miniconda3/envs/ome_sdc/lib/python3.13/site-packages/scipy/sparse/_index.py", line 104, in __getitem__
    res = self._get_arrayXarray(row, col)
  File "/opt/miniconda3/envs/ome_sdc/lib/python3.13/site-packages/scipy/sparse/_compressed.py", line 565, in _get_arrayXarray
    csr_sample_values(M, N, self.indptr, self.indices, self.data,
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                      major.size, major.ravel(), minor.ravel(), val)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: could not convert integer scalar
```
 
</details>

I tried to get a more minimal version of the bug, but subsetting the data makes the bug disappear, so maybe it's something that occurs only for larger matrices.

<details>
  <summary>Session info.</summary>
  
| Package | Version |
| ------- | ------- |
| anndata | 0.12.8  |

| Dependency                    | Version     |
| ----------------------------- | ----------- |
| sphinxcontrib-htmlhelp        | 2.1.0       |
| sphinxcontrib-serializinghtml | 2.0.0       |
| backports.zstd                | 1.3.0       |
| typing_extensions             | 4.15.0      |
| sphinxcontrib-qthelp          | 2.0.0       |
| fast-array-utils              | 1.3.1       |
| scipy                         | 1.17.0      |
| threadpoolctl                 | 3.6.0       |
| sphinxcontrib-bibtex          | 2.6.5       |
| pyarrow                       | 23.0.0      |
| scanpy                        | 1.12        |
| sphinxcontrib-jsmath          | 1.0.1       |
| sphinxcontrib-devhelp         | 2.0.0       |
| fsspec                        | 2026.1.0    |
| google-crc32c                 | 1.8.0       |
| pytz                          | 2025.2      |
| python-dateutil               | 2.9.0.post0 |
| MarkupSafe                    | 3.0.3       |
| session-info2                 | 0.3         |
| donfig                        | 0.8.1.post1 |
| sphinxcontrib-applehelp       | 2.0.0       |
| numpy                         | 2.3.5       |
| charset-normalizer            | 3.4.4       |
| six                           | 1.17.0      |
| zarr                          | 3.1.5       |
| packaging                     | 26.0        |
| h5py                          | 3.15.1      |
| setuptools                    | 80.10.2     |
| pandas                        | 2.3.3       |
| cloudpickle                   | 3.1.2       |
| PyYAML                        | 6.0.3       |
| Jinja2                        | 3.1.6       |
| legacy-api-wrap               | 1.5         |
| toolz                         | 1.1.0       |
| numcodecs                     | 0.16.5      |
| psutil                        | 7.2.1       |
| xarray                        | 2025.12.0   |
| dask                          | 2026.1.1    |
| natsort                       | 8.4.0       |

| Component | Info                                                                             |
| --------- | -------------------------------------------------------------------------------- |
| Python    | 3.13.0 | packaged by conda-forge | (main, Nov 27 2024, 19:18:26) [Clang 18.1.8 ] |
| OS        | macOS-26.2-arm64-arm-64bit-Mach-O                                                |
| Updated   | 2026-01-28 14:07                                                                 |

</details>

**Comment by ilan-gold** [comment]
We will exclude 1.17.0 and I will ask there about the status of patch release
