### ISSUE TITLE
Anndata concatenation is giving an error

### ISSUE THREAD

**Issue by aditisk** [theislab/anndata#347]
Hello,

I'm trying to read hdf5 files and concatenate them. I am following the code in theislab/scanpy#267 

```python
adata = adatas[0].concatenate(adatas[1:])

I tried it and it worked when I had just 2 files. I am trying the same code with 23 files and I am getting an error message in the concatenation step. Any idea on how to fix this ? Thanks.

AttributeError Traceback (most recent call last)
in 
12 adatas.obs['cell_names'] = pd.read_csv(path + sample + 'barcodes.tsv.gz', header=None)[0].values
13
---> 14 adata = adatas[0].concatenate(adatas[1:])

/Applications/anaconda3/lib/python3.7/site-packages/anndata/core/anndata.py in concatenate(self, join, batch_key, batch_categories, index_unique, *adatas)
1908
1909 if any_sparse:
-> 1910 sparse_format = all_adatas[0].X.getformat()
1911 X = X.asformat(sparse_format)
1912

AttributeError: 'numpy.ndarray' object has no attribute 'getformat'
```

Sorry for posting as a new issue but since the old issue is closed and not directly related to my question I created a new one. Thanks.

**Comment by aditisk** [comment]
Here are my version numbers:
scanpy==1.4.5.post2 anndata==0.6.22.post1 umap==0.3.10 numpy==1.17.2 scipy==1.3.1 pandas==0.25.1 scikit-learn==0.21.3 statsmodels==0.10.1 python-igraph==0.7.1

The code above throws an error:
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-5-e461e62f3a69> in <module>
      1 from scipy import sparse
----> 2 assert isinstance(adatas[0].X, sparse.spmatrix)

AssertionError:

**Comment by ivirshup** [comment]
Could you try updating your `anndata` install?

On my side this seems to work.

**Comment by aditisk** [comment]
I updated to version 0.7.1 and the error message goes away but the concatenation doesn't seem to be working. If I check the number of cells in my adata object, it equals the number of cells only in the 1st sample. I'm pasting my code below for your reference:

samples = ['HD_1_PBL/','HD_2_PBL/','HD_3_PBL/',
           'HD_4_PBL/','HD_5_PBL/','HD_6_PBL/']
for sample in samples:
    print(sample)
    adatas = sc.read_10x_h5(path + sample + 'matrix.h5') 
    genes = pd.read_csv(path + sample + 'genes.tsv.gz', header=None, sep='\t')
    adatas.var_names = genes[1]
    adatas.var['gene_ids'] = genes[0]  # add the gene ids as annotation of the variables/genes
    adatas.obs_names = pd.read_csv(path + sample + 'barcodes.tsv.gz', header=None)[0]
    adatas.obs['cell_names'] = pd.read_csv(path + sample + 'barcodes.tsv.gz', header=None)[0].values
   
adata = adatas[0].concatenate(adatas[1:])

adata
AnnData object with n_obs × n_vars = 1408 × 33694 
    obs: 'batch', 'cell_names'
    var: 'gene_ids', 'feature_types', 'genome'

**Comment by ivirshup** [comment]
Don't you just have one `AnnData` object there? It's a little unclear what your loop is doing without indentations but I think `adatas` is only ever one AnnData object. So, your concatenation command is just concatenating the first cell of the last file read, to the rest of the cells from that file.

I think you're looking to do something more like this:

```python
path = ... # whatever your path variable was
samples = ['HD_1_PBL/','HD_2_PBL/','HD_3_PBL/',
'HD_4_PBL/','HD_5_PBL/','HD_6_PBL/']

def load_data(sample_dir):
    adata = sc.read_10x_h5(sample_dir + 'matrix.h5')
    genes = pd.read_csv(sample_dir + 'genes.tsv.gz', header=None, sep='\t')
    adata.var_names = genes[1]
    adata.var['gene_ids'] = genes[0] # add the gene ids as annotation of the variables/genes
    adata.obs_names = pd.read_csv(sample_dir + 'barcodes.tsv.gz', header=None)[0]
    adata.obs['cell_names'] = pd.read_csv(sample_dir + 'barcodes.tsv.gz', header=None)[0].values
    return adata

adatas = [load_data(path + sample) for sample in samples]
adata = adatas[0].concatenate(adatas[1:])
``` 

Also, for future reference, please show your code and versions when you open an issue. We'll be able to figure out what's going on much faster.

**Comment by aditisk** [comment]
Dear @ivirshup, thanks a lot for your help with this. It works perfectly now.

I'm sorry, the code indentation was lost while pasting, I'll ensure that doesn't happen again. I will also keep in mind to post versions and my code at the beginning of the issue.

Thanks once again for your help.
