### ISSUE TITLE
Can't index into anndata object with integer obs_names

### ISSUE THREAD

**Issue by ivirshup** [theislab/anndata#35]
Trying to index into an `AnnData` object which has integer `obs_names` throws an assertion error. I expected either not allowing the construction an object with integer `obs_names` or allowing indexing into them.

Here's a quick example. First I instantiate an `AnnData` object, give it integers for observation names, then get an error when I try to index into it:

```python
>>> import scanpy.api as sc
>>> import pandas as pd
>>> import numpy as np
>>> adata = sc.datasets.krumsiek11()
Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
... storing 'cell_type' as categorical
>>> adata.obs_names = np.array(range(adata.n_obs))
>>> adata[:, ['Gata2', 'Gata1']]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/anndata/base.py", line 1211, in __getitem__
    return self._getitem_view(index)
  File "/usr/local/lib/python3.6/site-packages/anndata/base.py", line 1214, in _getitem_view
    oidx, vidx = self._normalize_indices(index)
  File "/usr/local/lib/python3.6/site-packages/anndata/base.py", line 1190, in _normalize_indices
    obs = _normalize_index(obs, self.obs_names)
  File "/usr/local/lib/python3.6/site-packages/anndata/base.py", line 231, in _normalize_index
    'Don’t call _normalize_index with non-categorical/string names'
AssertionError: Don’t call _normalize_index with non-categorical/string names
```

This error in indexing can be recovered by using a `pandas.RangeIndex` for the observation names:

```python
>>> adata.obs_names = pd.RangeIndex(stop=adata.n_obs)
>>> adata[:, ['Gata2', 'Gata1']]
View of AnnData object with n_obs × n_vars = 640 × 2 
    obs: 'cell_type'
    uns: 'iroot', 'highlights'
```

However, range indexes are frequently implicitly replaced with integer indexes:

```python
>>> adata_norm = sc.pp.normalize_per_cell(adata, copy=True)
>>> adata_norm.obs_names
Int64Index([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,
            ...
            630, 631, 632, 633, 634, 635, 636, 637, 638, 639],
           dtype='int64', length=640)
>>> adata_norm[:, ['Gata2', 'Gata1']]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/anndata/base.py", line 1211, in __getitem__
    return self._getitem_view(index)
  File "/usr/local/lib/python3.6/site-packages/anndata/base.py", line 1214, in _getitem_view
    oidx, vidx = self._normalize_indices(index)
  File "/usr/local/lib/python3.6/site-packages/anndata/base.py", line 1190, in _normalize_indices
    obs = _normalize_index(obs, self.obs_names)
  File "/usr/local/lib/python3.6/site-packages/anndata/base.py", line 231, in _normalize_index
    'Don’t call _normalize_index with non-categorical/string names'
AssertionError: Don’t call _normalize_index with non-categorical/string names
```

Thanks!

**Comment by ivirshup** [comment]
Just cause I feel like my current work-around is silly (converting the integer obs_names to strings), I was looking into why this is happening. Am I correct in thinking [the assertion I'm triggering](https://github.com/theislab/anndata/blob/6c85c8cb280ebbb867202d1aed79648bf0021b50/anndata/base.py#L219) was added since indexing into an `AnnData` object with a numeric is supposed to be positional, like `pandas` `.iloc` method, while indexing with a string/ categorical is supposed to behave like `.loc`?

**Comment by falexwolf** [comment]
I added this warning when people try to work with non-string indices: https://github.com/theislab/anndata/commit/51be5d85e62b1aa19d6f55ffc21aedbe9628c4c5.

**Comment by ltosti** [comment]
Hi @falexwolf, @ivirshup , 
I was trying to use BBKNN and got this error when trying to concatenate different datasets ([see here](https://github.com/Teichlab/bbknn/issues/7)). Could you please clarify how you managed to fix that?

Thank you!

**Comment by falexwolf** [comment]
Sorry about this bug! It might be related to the objects having integer indices: we shouldn't have an error thrown, I guess. But previously, this was presumably inconsistent behavior. @flying-sheep, did you add the following line at some point to `_normalize_index`, which triggers the error:
```
assert names.dtype != float and names.dtype != int, \
    'Don’t call _normalize_index with non-categorical/string names'
```

**Comment by flying-sheep** [comment]
am I missing something? AFAIK datasets still can’t have integer `var_names` or `obs_names`. else it’s impossible to distinguish if e.g. `adata[0, :]` means `adata[adata.obs_names == 0, :]` or `adata[np.arange(adata.shape[0]) == 0, :]`.

**Comment by ltosti** [comment]
Thank you for the clarification! I think this error was not thrown in scanpy 1.2.2 (for example [here](https://nbviewer.jupyter.org/github/Teichlab/bbknn/blob/master/examples/pancreas.ipynb)), but it does occur now (scanpy 1.3.6). I guess a solution could be to force the ```var_names``` to string.

**Comment by falexwolf** [comment]
> am I missing something? AFAIK datasets still can’t have integer var_names or obs_names. 

@flying-sheep we never threw an error when people set non-string indices; so there will be objects out there that have non-string indices; the assert statement that was probably inserted by you was the first to actually throw an error; before, integer indices were interpreted `.iloc` - style even if there was an integer index... that's the only way I can imagine that the notebook above broke

**Comment by flying-sheep** [comment]
Well, I think it’s an useful error to throw. We could add a tip on how to resolve it by removing the index…

**Comment by falexwolf** [comment]
Yes, it's a useful error, but it shouldn't be thrown in `getitem` and it broke the notebook! Instead, an error should be thrown when setting a non-string index; but in that case I accounted for it via a warning, knowing that I would otherwise break things that previously worked.

We shouldn't allow people to have objects in an invalid state and then be surprised by throwing an error later on.

It would be better if here, we output a warning saying that one matches `.iloc`-style and not on the elements of the index. This is what happened before, it's OK in many cases and allowed the pancreas notebook referenced above to run through. There might be many such notebooks out there and it would be nice to renable them.

**Comment by flying-sheep** [comment]
You’re right, let’s throw a warning in `__getitem__`. (Btw: I don’t know if I introduced that exception, I probably did)
