### ISSUE TITLE
concatenate layers with outer join

### ISSUE THREAD

**Issue by VolkerBergen** [theislab/anndata#351]
Outer join concatenation is not yet available [here](https://github.com/theislab/anndata/blob/e4581abc6297752b8954645b0fe08e0aee843b7f/anndata/_core/anndata.py#L1744). I fear, I'm currently out of capacity to make a PR. Anyone who could take care of that?

**Comment by ivirshup** [comment]
I've got this working. I'll have to wait until the `uns` merging PR is through though, since my solution depends on that code. It's also about ~5x faster!

**Comment by VolkerBergen** [comment]
Awesome, thanks!
