### ISSUE TITLE
create conda recipe to upload to bioconda 

### ISSUE THREAD

**Issue by imyiningliu** [theislab/anndata#36]
Hi, [scvi](https://github.com/YosefLab/scVI) supports automatically loading an `.h5ad` file to analyze scRNA-seq. Since we included `anndata` as one of our dependencies and we uploaded `scvi` to `bioconda` channel, I'm wondering if it's okay if I upload a `conda` recipe for `anndata` to `bioconda`?

**Comment by falexwolf** [comment]
Awesome that you support `anndata`! :smile:

Of course it's OK to upload a conda recipe to for `anndata` to `bioconda`. Please tell me when you've done it, I'll link to it from the documentation then.

**Comment by imyiningliu** [comment]
You should be able to install `anndata` using `conda install anndata -c bioconda`.

**Comment by falexwolf** [comment]
Thanks! :smile:
