### ISSUE TITLE
Anndata dense matrix, outer join fills with NA

### ISSUE THREAD

**Issue by jayypaul** [theislab/anndata#365]
Hi,

I've separated 8 batches into distinct groups based to carry out QC on groups that are most similar in their n_counts distributions. Each time I merge them I noticed that it was getting rid of genes, due to the join = "inner" parameter. I chose "outer", but I guess since my anndata.X matrix is dense, it fills it with NAN values and it seems pointless to carry on from there. 

Is there a way to keep the genes unique to each batch, fill with 0s like with a sparse matrix? Can I make the matrix sparse or would that be problematic?

**Comment by jayypaul** [comment]
To elaborate, I want to do my normalization with all batches together, then separate into 8 batches again to do mnn_correct, exemplified here: https://nbisweden.github.io/workshop-scRNAseq/labs/compiled/scanpy/scanpy_03_integration.html

**Comment by jayypaul** [comment]
Another update, I found this: coo_matrix(adata.X).tocsr() .... but will this cause problems later on?

**Comment by ivirshup** [comment]
In the next release there is going to be a key word argument for choosing the fill value.

Until then, you could try something like `adata.X = np.nan_to_num(adata.X)`

```python
coo_matrix(adata.X).tocsr()
```

This should be fine as long as your data is actually sparse. Otherwise it might cause some efficiency issues, but should be fine.

**Comment by jayypaul** [comment]
Ok will try this out, thanks a lot!
