### ISSUE TITLE
adata.obsp.copy() and adata.obsp access causes extremely rapid memory consumption

### ISSUE THREAD

**Issue by alasla** [theislab/anndata#380]
This is a relatively new bug, because this used to work fine until I updated scanpy and anndata. 

```
scanpy==1.5.0 anndata==0.7.2 umap==0.3.10 numpy==1.18.1 scipy==1.4.1 pandas==1.0.3 scikit-learn==0.22.1 statsmodels==0.11.1 python-igraph==0.8.0 louvain==0.6.1
``` 

On my ~250k cell dataset (csr sparse matrix):
```
adata.X

<233963x38615 sparse matrix of type '<class 'numpy.float32'>'
	with 437654478 stored elements in Compressed Sparse Row format>
```

This works great:
```
cell_subset, num_per_cell = sc.pp.filter_cells(adata.X, min_genes=1)
adata.obs['n_genes'] = num_per_cell
adata = adata[cell_subset]
```

However this rapidly explodes to > 128G of memory (the amount on my server).  
```
sc.pp.filter_cells(adata, min_genes=1)
```

I've been digging to see why, and get the same memory explosion doing
```
cell_subset, num_per_cell = sc.pp.filter_cells(adata.X, min_genes=1)
adata.obs['n_genes'] = num_per_cell
adata._inplace_subset_obs(cell_subset)
```

Further digging produces that this also explodes (this is what is done inside of _inplace_subset_cell):
```
adata = adata[cell_subset].copy()
```

I walked through the copy() function and found the following immediately consumes all memory on my machine
```
adata = adata[cell_subset]
adata.obsp.copy()
```

Obsp only contains: 
```
PairwiseArraysView with keys: distances, connectivities
```

Hell even accessing the 'distances' element of obsp causes an immediate memory explosion:
```
type(adata.obsp['distances'])
```

I'm going to keep digging but there are lots of layers of abstraction down own this far, and you might be more familiar than I.  I'll also try to get a simple reconstruction.  Do you happen to know off the top of your head what computes the 'distances' obsp entry?

**Comment by alasla** [comment]
This is off of data saved from a previous anndata (though one that was .7+ I believe).  Just noticed this warning which might be part of the issue: 
```
/usr/local/lib/python3.6/dist-packages/anndata/compat/__init__.py:161: FutureWarning: Moving element from .uns['neighbors']['distances'] to .obsp['distances'].

This is where adjacency matrices should go now.
  FutureWarning,
/usr/local/lib/python3.6/dist-packages/anndata/compat/__init__.py:161: FutureWarning: Moving element from .uns['neighbors']['connectivities'] to .obsp['connectivities'].

This is where adjacency matrices should go now.
  FutureWarning,
```

**Comment by alasla** [comment]
Ok this is definitely a result of opening the old saved dataset.  If I build the dataset fresh I don't get the same errors.  

Not sure how much you want to go into troubleshooting backwards compatibility problems in anndata.  Feel free to close if you don't want to go there.

**Comment by gokceneraslan** [comment]
I think this is very important since users will definitely load datasets created by older versions of anndata. I am also not familiar with the new `obsp` code but @Koncopd or @ivirshup would know.

**Comment by Koncopd** [comment]
distances, connectivities are written by `sc.pp.neighbors`, but i doubt this is the reason. It may be related to the internals of obsp or to https://github.com/theislab/anndata/issues/360.

**Comment by alasla** [comment]
Yeah I recreated this situation entirely with ```scanpy==1.5.0 anndata==0.7.2 ``` so its not just about the old files either.  It seems to happen when I do filter_cells (which does the obsp.copy() under the coveres) after having stuff in obsp.

**Comment by alasla** [comment]
But I'm not able to replicate this with an small synthetic test yet.  If I do I'll post it here.

**Comment by ivirshup** [comment]
I think I see what's going on:

```python
%load_ext memory_profiler

from scipy import sparse
import numpy as np

# Getting a sparse matrix of similar density to a connectivity matrix
# Sadly, this is very slow
conn = sparse.random(10000, 10000, density=10000 * 15 / (10000**2), format="csr")

s_idx = np.arange(conn.shape[0], dtype=int)

%memit sub1 = conn[s_idx.reshape(-1, 1), s_idx]
# peak memory: 68.25 MiB, increment: 5.02 MiB

%memit sub2 = conn[np.ix_(s_idx, s_idx)]
# peak memory: 1978.67 MiB, increment: 1910.39 MiB

assert not np.any((sub1 != sub2).data)  # Same results
```

We are doing the latter at:

https://github.com/theislab/anndata/blob/405b43e5beb4a211114544442f3aaeff0b62a12e/anndata/_core/index.py#L120-L126

I'm pretty surprised this hasn't come up before, since this is how the neighbors graphs were subset while they were in `uns` before.

Either way, I'll open a PR to fix this and probably an issue at scipy.
