### ISSUE TITLE
drastically changed behavior of category observations?

### ISSUE THREAD

**Issue by alasla** [theislab/anndata#384]
I swear I used to be able to:
```
adata.obs['my_cateogory'] = ['a', 'b', 'c', 'd']
``` 
And that would happily function as a categorical annotation.  And indeed if I open up previously saved datasets category obs annotations behave that way, and then allow you to do stuff like:
```
sc.pl.matrixplot(adata, var_names=[...], groupby='my_category')
```

But something has changed recently:

```
adata = anndata.AnnData(np.array([[1,1,1,1], [2,2,2,2], [3,3,3,3]]))
adata.var_names = ["A", "B", "C", "D"]

adata.obs['test_cat'] = ["a", "b", "c"]
```

```
adata.obs['test_cat']
```
gives
```
0    a
1    b
2    c
Name: test_cat, dtype: object
```
... so its an object now not a category.  Fine.  

```
pd.Series(['a', 'b', 'c'], dtype='category')
```
ordinarily gives
```
0    a
1    b
2    c
dtype: category
Categories (3, object): [a, b, c]
```

Or even in a dataframe
```
temp = pd.DataFrame(pd.Series(['a', 'b', 'c'], dtype='category'), columns=['test_cat'])
temp['test_cat']
```
yields 
```
0    a
1    b
2    c
Name: test_cat, dtype: category
Categories (3, object): [a, b, c]
```

But for some reason in AnnData now:
```
adata.obs['test_cat_explicit'] = pd.Series(['a', 'b', 'c'], dtype='category')
adata.obs['test_cat_explicit']
```
yields
```
0    NaN
1    NaN
2    NaN
Name: test_cat_explicit, dtype: category
Categories (3, object): [a, b, c]
```
... which has those NaN values in there.  That would just be weird, but if I then attempt to use this category in categorical places, it does not work:
```
sc.pl.matrixplot(adata, var_names=adata.var_names, groupby='test_cat_explicit')
```
yields
<img width="704" alt="image" src="https://user-images.githubusercontent.com/6528204/82696710-6d00ae80-9c1c-11ea-8e49-e313e8e57165.png">

So I think there is some handling of string/categorical data that has changed recently.  Any suggestions?

**Comment by ivirshup** [comment]
I think I see what's happening in these examples, and I think it's the expected behavior.

### Null values

```python
>>> import pandas as pd
>>> df = pd.DataFrame(index=list("01234"))
>>> df["cat"] = pd.Series(list("aabcd"), dtype="category")
>>> df
   cat
0  NaN
1  NaN
2  NaN
3  NaN
4  NaN
```

The `pd.Index` labels of `AnnData` objects are always strings. Otherwise we would run into trouble with ambiguity for positional vs label based indexing.

So when you assign a series with a numeric index, it can't be aligned to the `adata.obs` since the values don't match up.

If you were to instead do:

```python
>>> import numpy as np
>>> from anndata import AnnData
>>> a = AnnData(np.ones((5, 5)))
>>>  a.obs["cat"] = pd.Categorical(list("aabbc"))
>>> a
  cat
0   a
1   a
2   b
3   b
4   c
````


### Non categorical values:

We don't actually control the `__setitem__` method when you assign to `obs`, that's just pandas. We do conversion to categorical (for efficiency) when we have a reason to check, like when plotting.

For example:

```python
>>> import scanpy as sc
>>> blobs = sc.datasets.blobs()
>>> blobs.obs["cat"] = "a"
>>> blobs.obs["cat"][::2] = "b"
>>> blobs.obs["cat"].dtype
dtype('O')
>>> sc.pp.pca(blobs)
>>> sc.pl.pca(blobs)
... storing 'blobs' as categorical
... storing 'cat' as categorical
>>> blobs.obs["cat"].dtype
CategoricalDtype(categories=['a', 'b'], ordered=False)
```

**Comment by alasla** [comment]
Interesting.  Maybe there was an underlying change in how __setitem__ works in pandas, because (looking at old code) I'm 100% sure that:
```
adata.obs["cat"] = ['a', 'b', 'c', 'd']
``` 
... along with the scanpy conversion to categorical when plotting, used to do the right thing.  I can just work around it using pd.Categorical() .

**Comment by ivirshup** [comment]
What exactly isn't working the way you expect with assigning strings to a column of obs? Is it just that isn't immediately converted to a categorical value? I'd also note that we don't convert arrays of string to categoricals if all the values are actually unique.

**Comment by alasla** [comment]
Oh the latter is probably what is happening then.  I didn't realize it wouldn't convert to categorical in that case, and that is exactly what was biting me.  I'll close this.  I think everything working as intended.
