### ISSUE TITLE
TYPE ERROR NO CONVERSION PATH FOR DTYPE: DTYPE( <U8)  

### ISSUE THREAD

**Issue by cmorris2945** [theislab/anndata#389]
Adata file can not be saved.

import h5py
save_file = './donors.h5ad'
donors.write(save_file)

here is what I got:

![error](https://user-images.githubusercontent.com/30676606/83467287-7a514080-a447-11ea-8729-201ce9b6a6ed.png)

**Comment by ivirshup** [comment]
Could you let us know what versions of anndata, pandas, and h5py you're using? I believe current versions of pandas objects try not to allow numpy fixed length strings in their values.

**Comment by cmorris2945** [comment]
Its ok i figured it out.
Thank you for your attention.
