### ISSUE TITLE
No module named pathlib on install

### ISSUE THREAD

**Issue by scottgigante** [theislab/anndata#39]
I believe pathlib needs to be added as a dependency.

```
> pip install anndata
Collecting anndata
  Using cached https://files.pythonhosted.org/packages/a2/31/abf1918b45012977f1f78de6cdd01ee6c3650acae538ff8f7b0b17c1f47f/anndata-0.6.5.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\scott\appdata\local\temp\pip-build-lzqa4a\anndata\setup.py", line 2, in <module>
        from pathlib import Path
    ImportError: No module named pathlib
```

This is with Python 2.7 on Windows.

**Comment by scottgigante** [comment]
Or perhaps AnnData doesn't support Python2, in which case setup.py should complain about my Python version, since after that I get another error:
```
    import anndata
  File "C:\Python27\lib\site-packages\anndata\__init__.py", line 1, in <module>
    from .base import AnnData, _MAIN_NARRATIVE
  File "C:\Python27\lib\site-packages\anndata\base.py", line 66
    def __new__(cls, input_array: np.ndarray, parent: Any, attr: str):
                                ^
SyntaxError: invalid syntax
```

**Comment by flying-sheep** [comment]
Yup, we only support somehow recent python versions!

FYI: 2.7 is really old, deprecated and its end-of-life is 2020-01-01! https://pythonclock.org

**Comment by scottgigante** [comment]
Thanks for the fix @flying-sheep. I'm only using Python2 to run tests to make sure my code is backwards compatible, something I've committed to do until pandas drops support next January.

Thanks for the quick response!

**Comment by flying-sheep** [comment]
That’s very laudable! Sorry if I came over preachy, it’s just that I still meet some people who are surprised that Python 2.7 is about to die :smile:

**Comment by scottgigante** [comment]
Not a problem :) A lot of users (hopefully not devs) _are_ still using Python 2.7 though - hopefully the great python gods have a plan of how to migrate everyone across.

**Comment by flying-sheep** [comment]
Ha, of course they do! A >10 year migration period should have been plenty for even the most glacial company.

Whoever is still invested in 2.7 by 2020 had it coming for a loooong time and their users should switch to a competitor.
