### ISSUE TITLE
Deprecation warning from pandas

### ISSUE THREAD

**Issue by Jeff1995** [theislab/anndata#392]
anndata/_core/anndata.py:21: FutureWarning: pandas.core.index is deprecated and will be removed in a future version.  The public classes are available in the top-level namespace.
  from pandas.core.index import RangeIndex

`RangeIndex` is now accessible directly as `pandas.RangeIndex`.

**Comment by flying-sheep** [comment]
Please use the search function: https://github.com/theislab/anndata/search?q=RangeIndex+is%3Aissue&type=Issues

This has been fixed as #319
