### ISSUE TITLE
Calling AnnData(numpy.ndarray) fails

### ISSUE THREAD

**Issue by galicae** [theislab/anndata#4]
Hi,

thanks for putting this out there, python needed an annotated data format :)

I am trying to use the diffusion maps from [scanpy](https://github.com/theislab/scanpy), and it requires me to format my input array in AnnData format. Now, according to the [documentation](http://scanpy.readthedocs.io/en/latest/api/scanpy.api.AnnData.html), I should be able to call AnnData with a numpy.ndarray and without any annotation. However, when I do that, even with `ad = AnnData(np.ones((2, 2)))`, like in the documentation, I get a TypeError:

```
TypeError                                 Traceback (most recent call last)
<ipython-input-8-1792540ebafc> in <module>()
----> 1 ad = AnnData(X1)

~/miniconda2/envs/py35/lib/python3.5/site-packages/anndata/anndata.py in __init__(self, data, smp, var, uns, smpm, varm, dtype, single_col)
    334 
    335         # multi-dimensional array annotations
--> 336         if smpm is None: smpm = np.empty(self._n_smps, dtype=[])
    337         if varm is None: varm = np.empty(self._n_vars, dtype=[])
    338         self._smpm = BoundRecArr(smpm, self, 'smpm')

TypeError: Empty data-type
```

the error persists in jupyter notebooks and in the python console. Any ideas what may be causing that?

cheers,
Niko

**Comment by falexwolf** [comment]
Hm, super strange. Do you have a recent numpy version? With numpy 1.13.3, this works
```
>>> np.empty(10, dtype=[])
array([), ), ), ), ), ), ), ), ), )],
      dtype='[]')
```
This is a structured array of length 10.

**Comment by galicae** [comment]
```
> conda list | grep numpy
numpy   1.13.3    py35_blas_openblas_200
```

but when I run the command I get an error... this is apparently a problem with my installation though, and not with anndata.

Thanks for your time!

**Comment by falexwolf** [comment]
Very strange; no one reported the error before... The problem is that I cannot think of another way of initializing an empty structured array of a certain length. Please let me know if this persists...

**Comment by galicae** [comment]
Update: I updated python to 3.6 and then it worked. Probably not a numpy problem - I can confirm that numpy 1.12.something with python 3.6 worked too.
