### ISSUE TITLE
Concatenate concatenated annData object with Vanilla annData object does not work correctly

### ISSUE THREAD

**Issue by Chillig** [theislab/anndata#406]
Hi,

I was trying to concatenate adatas containing Spatial data using the function concatenate with uns_merge="unique'.
Frist I concatenated the adata objects in a for loop, by doing so, the information of the 'library_id' in adata.obs only contains the first two sample names after the concatenation process.
Plotting the images with the spots belonging to them does then not work then correctly. 
I then tried to load all samples and store them in a list. Afterwards I applied on that list the function concatenate for annData objects and for some reason the entries in the 'library_id' contain now all sample ids.

I have prepared a code snippet to make more clear what I mean:

```python
# scanpy==1.5.0 anndata==0.7.4 umap==0.4.2 numpy==1.18.4 scipy==1.5.0 pandas==1.0.3 scikit-learn==0.22.1
# statsmodels==0.11.0 python-igraph==0.7.1 louvain==0.6.1 leidenalg==0.7.0

import scanpy as sc
import numpy as np


def load_samples():
    """
    Load 10x Genomics public samples

    :return:
    """

    adata_spatial_sagital_posterior = sc.datasets.visium_sge(sample_id="V1_Mouse_Brain_Sagittal_Posterior")
    adata_spatial_sagital_anterior = sc.datasets.visium_sge(sample_id="V1_Mouse_Brain_Sagittal_Anterior")
    adata_spatial_lymph_node = sc.datasets.visium_sge(sample_id="V1_Human_Lymph_Node")

    adata_spatial_sagital_posterior.var_names_make_unique()
    adata_spatial_sagital_anterior.var_names_make_unique()
    adata_spatial_lymph_node.var_names_make_unique()

    return adata_spatial_sagital_posterior, adata_spatial_sagital_anterior, adata_spatial_lymph_node


def concatenate_samples(adatas):
    """
    Concatenate annData objects

    :param adatas: [list] list containing annData objects
    :return:
    """
    adata_spatial = adatas[0].copy()

    # save .uns (images, image properties) and .obsm (spot positions)
    list_adata_uns = [adata.uns['spatial'] for adata in adatas]
    adata_spatial = adata_spatial.concatenate(adatas[1:], batch_key="library_id",
                                              batch_categories=[k + '_' + str(counter + 1)
                                                                for counter, d in enumerate(list_adata_uns)
                                                                for k, v in d.items()],
                                              uns_merge='unique')

    return adata_spatial


def main():
    adata_spatial_sagital_posterior, adata_spatial_sagital_anterior, adata_spatial_lymph_node = load_samples()

    list_adatas = [adata_spatial_sagital_posterior, adata_spatial_sagital_anterior, adata_spatial_lymph_node]

    # Works: merge adatas in one go
    adata = concatenate_samples(list_adatas)
    # make barcode names unique
    adata.obs_names = [c.split("-")[0] for c in adata.obs_names]

    print(adata.obs['library_id'])
    print(np.unique(adata.obs['library_id']))
    # Categories (3, object): [V1_Mouse_Brain_Sagittal_Posterior_1, V1_Mouse_Brain_Sagittal_Anterior_2,
    #                          V1_Human_Lymph_Node_3]

    # Does not work: merge concat adata with vanilla adata object
    adatas = [list_adatas[0]]
    for counter in range(len(list_adatas[1:])):
        adatas.append(list_adatas[counter + 1])
        concat_adatas = concatenate_samples(adatas)
        adatas = [concat_adatas]

    # make barcode names unique
    adatas[0].obs_names = [c.split("-")[0] for c in adatas[0].obs_names]

    print(adatas[0].obs['library_id'])
    print(np.unique(adatas[0].obs['library_id']))

    # Categories (3, object): [V1_Mouse_Brain_Sagittal_Posterior_1, V1_Mouse_Brain_Sagittal_Anterior_1,
    #                          V1_Human_Lymph_Node_2]


if __name__ == '__main__':
    main()
```

**Comment by ivirshup** [comment]
I'm not sure I understand the problem. Is the issue that the result of these two strategies isn't the same? Or is there something wrong with the result of your current `concatenate_samples`?

Those results won't be the same, due to how keys get modified by `AnnData.concatenate`. This is part of why we've introduced a new API for this with `anndata.concat`.

--------------------------

By the way, if you pass `index_unique=None` to `AnnData.concatenate` you won't have to modify the `.obs_names` of your result. This is the default behavior for `anndata.concat`.

Here's how I would do what I think you're going for:

```python
import scanpy as sc
import anndata as ad

dsets =  [
    "V1_Mouse_Brain_Sagittal_Posterior", "V1_Mouse_Brain_Sagittal_Anterior", "V1_Human_Lymph_Node"
] 
adatas = {k: sc.datasets.visium_sge(k) for k in dsets}

for a in adatas.values():
    a.var_names_make_unique()

adata = ad.concat(adatas, label="library_id", uns_merge="unique")
```

**Comment by Chillig** [comment]
Hi,

sry, I will try to make the problem more clear:
I want to concatenate my samples which have additional data stored in var, obs, uns, obsm. 
If I concatenate two annData objects using the function concatenate and uns_merge="unique" everything works fine and is saved in the variable adata. 
If I want to concatenate to this adata another annData object adata_single using the same function concatenate and uns_merge="unique" the library_id of the adata_single object is not saved in the resulting new adata_3_samples object. That means I cannot plot the image with the spots on top from properly. 

One workaround would be to load all samples into a list and to concatenate them under the condition that you don't want to add another sample any time afterwards to your already concatenated annData object.

Is this explanation more clear? 

I tried your code snippet, and it did not work for me.
This was the result:
print(adata)
AnnData object with n_obs × n_vars = 10088 × 16
    obs: 'in_tissue', 'array_row', 'array_col', 'library_id'
    uns: 'spatial'
    obsm: 'spatial'

print(adata[0].obs['library_id'])
AAACAAGTATCTCCCA-1    V1_Mouse_Brain_Sagittal_Posterior
Name: library_id, dtype: category

print(np.unique(adata[0].obs['library_id']))
Categories (1, object): [V1_Mouse_Brain_Sagittal_Posterior]
['V1_Mouse_Brain_Sagittal_Posterior']

**Comment by ivirshup** [comment]
When you tried my example, did you mean to try this?

```python
print(np.unique(adata.obs['library_id']))
```

In your example, you were looking at the unique values of `obs` after you subset it to one entry (`adata[0].obs`).

-----------

I think that makes sense to me. The column used for adding labels corresponding to the original objects get written when you concatenate the objects. It's only going to have as many categories as there were objects the last time you called concatenate. The intended use case is to have all of the samples at once (as this will be more efficient).

If you wanted to append them one at a time you could do something more like this:

```python
import anndata as ad
import pandas as pd
import numpy as np

def make_anndata(size, label):
    adata = ad.AnnData(np.zeros(size))
    adata.obs["library_id"] = label  # Adding the label
    return adata

adatas = [make_anndata((10, 10), x) for x in ("a", "b", "c")]
ad.concat(adatas).obs["library_id"].value_counts()
# b    10
# c    10
# a    10
# Name: library_id, dtype: int64
```

**Comment by Chillig** [comment]
Hi,
yes I meant: print(np.unique(adata.obs['library_id']))

----
ok, yes I agree that the use case is to have all samples at once. I just thought that if you add additional samples afterwards to your already concatenated annData object could save time, in case you have a lot of samples and did not receive all samples at once. 

Thank you :)
