### ISSUE TITLE
last version on bioconda is 0.6.22.post1

### ISSUE THREAD

**Issue by dangeles** [theislab/anndata#414]
And there seems to be an `anndata` package on `conda-forge` that's v0.7.1 and 0.7.4.

Which one is supported? 

Thanks! This package is really great and I look forward to continue using it!

**Comment by flying-sheep** [comment]
The conda-forge one is of course! It’s the current version.

**Comment by dangeles** [comment]
Could you update the README on `anndata` please?

**Comment by flying-sheep** [comment]
Aaah! Yes we have a conda-forge badge, but the text still mentions bioconda. Sorry!

anndata was originally on bioconda, but I think other conda-forge projects wanted to depend on it so it got moved there. Supporting conda-forge is much nicer, their build system is easier to handle.

But personally I just use PyPI for everything, that works nicely as well as long as you don’t use windows (some packages aren’t provided as wheels for windows, and compiling on windows is a pain)

**Comment by dangeles** [comment]
That makes sense! 

Unfortunately, we use `conda` for pretty much everything, since it plays best with `nextflow`. 


Thanks so much for the explanation! Really appreciate it.
