### ISSUE TITLE
is_categorical is deprecated in Pandas 1.1, use is_categorical_dtype instead

### ISSUE THREAD

**Issue by gokceneraslan** [theislab/anndata#419]
Apparently is_categorical is deprecated in pandas 1.1, as you probably already know:

https://github.com/pandas-dev/pandas/pull/33385

Here are the instances I can find:

https://github.com/theislab/anndata/blob/master/anndata/_core/anndata.py#L1094

https://github.com/theislab/anndata/blob/master/anndata/_core/anndata.py#L1192

https://github.com/theislab/anndata/blob/master/anndata/tests/test_readwrite.py#L8

Here is how highly_variable_genes look like, a bit annoying:

<img width="1441" alt="image" src="https://user-images.githubusercontent.com/1140359/90412236-ddcc3100-e07a-11ea-98fc-d0d0a86c18a6.png">

**Comment by ivirshup** [comment]
Good to know! I've been on pandas<1.1 since it breaks our tests. It might be a bit difficult to make a PR for fixing this until pandas 1.1.1 is released (tracking issue: https://github.com/pandas-dev/pandas/issues/35489).
