### ISSUE TITLE
'AnnData' object has no attribute 'to_anndata'

### ISSUE THREAD

**Issue by hahia** [theislab/anndata#424]
Hello,
I install the anndata use pip install anndata, the version is 0.7.4, but when I run, there happen a bug
**'AnnData' object has no attribute 'to_anndata'**

![image](https://user-images.githubusercontent.com/49113803/90975978-a4f4f600-e56b-11ea-8c44-6513d5169bad.png)

Anyone known how to solve this? Thanks any comments!!!

**Comment by hahia** [comment]
> Can you share what exactly you are running?

I'm run the wot python package
This is the command
![image](https://user-images.githubusercontent.com/49113803/90993778-c2b47080-e5e8-11ea-8c66-0861090f9f3b.png)
Is this information enough？

**Comment by ivirshup** [comment]
It looks to me like the issue is with the `wot` package, not `anndata`, since the error is being thrown there. I'd recommend opening an issue with them.
