### ISSUE TITLE
`conda` package out of date

### ISSUE THREAD

**Issue by jbloom** [theislab/anndata#431]
The version of `anndata` on `conda` seems out of date (0.6.22): https://github.com/jbloomlab/software

Is it possible to make a new `conda` package?

**Comment by ivirshup** [comment]
Are you looking on `conda-forge`?

I see:


```sh
$ conda search anndata
...
anndata                        0.7.4  py38h32f6830_0  conda-forge 
```

**Comment by jbloom** [comment]
You're correct. I was looking on bioconda, where it's an older version. But I'll just use conda-forge.
