### ISSUE TITLE
subsetting anndata on basis of clusters(louvain)

### ISSUE THREAD

**Issue by sidrahmaryam** [theislab/anndata#432]
Hello,
I want subset anndata on basis of clusters, but i am not able to understand how to do it. 

I am running scVelo pipeline, and in that i ran `tl.louvain` function to cluster cells on basis of louvain.
I got around 32 clusters, of which cluster 2 and 4 is of my interest, and i have to run the pipeline further on these clusters only. 
(Initially i had the loom file which i read in scVelo, so i have now the anndata.)

I tried using adata.obs["louvain"] which gave me the cluster information, but i need to write a new anndata and process further.

Please help. Any help is highly appreciated.

**Comment by Koncopd** [comment]
@sidrahmaryam you can do 
```
mask = (adata.obs["louvain"]  == "2") I (adata.obs["louvain"]  == "4")
adata_new = adata[mask].copy()
```

**Comment by sidrahmaryam** [comment]
Thank you so much for the help.
