### ISSUE TITLE
Find differentially expressed between multiple subsets of cells based on certain barcodes

### ISSUE THREAD

**Issue by josinejansen** [theislab/anndata#437]
Dear Theis Lab,

I have three questions for you, I would very much appreciate your help!

1. I would like to find differentially expressed genes between five different groups of cells based on specific barcodes (so not between Leiden clusters). What would be the best way to do this? What I have tried so far is:

_adata.obs['filtered_barcodes_group_1'] = data.obs_names.isin['TTGGAACCAGCGTCCA-1', 'TTGGCAAAGCTCCCAG-1']_

However I do get an error saying: 'method object is not subscriptable'.

2. Is it correct that if I could make the above work, that I could then afterwards use:

_sc.tl.rank_genes_groups(adata, 'barcodes', groups=['filtered_barcodes_group_1'], reference='filtered_barcodes_group_2', method='wilcoxon')_

3. How can I rank genes between filtered_barcodes_group_1 and **multiple** other groups (for example 2,3,4, and 5)?

Thanks in advance,

Josine

**Comment by LuckyMD** [comment]
Hi @josinejansen,

I think this question is more apt for the scanpy discourse group here: https://scanpy.discourse.group/. I will quickly reply here, but for further questions please head over there.

>1. I would like to find differentially expressed genes between five different groups of cells based on specific barcodes (so not between Leiden clusters). What would be the best way to do this?

You have correctly identified that you need to create a new `adata.obs` column with the grouping you want to do. You're just missing brackets after `.isin` as that's a method. As the error says, you cannot subscript this, which is what`[]` does.

> 2. Is it correct that if I could make the above work, that I could then afterwards use: `sc.tl.rank_genes_groups(adata, 'barcodes', groups=['filtered_barcodes_group_1'], reference='filtered_barcodes_group_2', method='wilcoxon')`

No, you could then use `sc.tl.rank_genes_groups(adata, 'filtered_barcodes_group_1', groups=['True'], reference=['False'], ...)` as you have only assigned a covariate that assesses whether the barcodes are in group 1 or not. To do the above you would need to have the more complex covariate assignment above:
```
barcode_group1 = ['TTGGAACCAGCGTCCA-1', 'TTGGCAAAGCTCCCAG-1']
barcode_group2 = []
adata.obs['barcodes'] = ['filtered_barcodes_group_1' if id.isin(barcode_group1) else 'filtered_barcodes_group_2' if id.isin(barcode_group2) else 'filtered_barcodes_group_3' for id in adata.obs_names]
```

> 3. How can I rank genes between filtered_barcodes_group_1 and multiple other groups (for example 2,3,4, and 5)?

By definition a differential expression test is always only between two groups. You can either do a DE test between group 1 and the rest (just use leave out the `reference=` parameter, this is the default behaviour), or you have to do all pairwise comparisons. If you want to choose which groups you compare to, you will need to make another `adata.obs` covariate with the grouping you are looking for.

All this being said, I don't think it makes sense to do a DE test comparing only 2 cells with another group. Typically you would want at least 50 cells in a group to get a robust assessment of the variation within this group.

**Comment by josinejansen** [comment]
Thanks !
