### ISSUE TITLE
anndata in R

### ISSUE THREAD

**Issue by rcannood** [theislab/anndata#440]
Hello all (@flying-sheep, @falexwolf, @ivirshup, @Koncopd and others)!

An increasing number of my projects have come to rely on anndata and h5ad. Up until now, I was reading the file using [hdf5r](https://cran.r-project.org/web/packages/hdf5r/index.html), changing it, and writing it back to a .h5ad file. However, that makes the code quite convoluted in order to perform a simple such as adding a column to the `.obs`. 

I decided to bite the bullet and created a reticulate wrapper for anndata in R: [https://github.com/rcannood/anndata](https://github.com/rcannood/anndata). I'm trying to match the interface to the anndata API as close as possible, though some parts might not work 100% yet (e.g. `ad$chunked_X(...)` is a bit of a hassle to work with. I also need to write a lot more tests to verify that everything keeps on working.

Do you have any suggestions regarding this package? I listed all anndata authors as authors in the [anndata R package](https://github.com/rcannood/anndata/blob/master/DESCRIPTION) as well, is this okay for you? 

Is there a branch in [`theislab/anndata`](https://github.com/theislab/anndata) which receives a PR only when a new version of anndata is published on PyPI? I could update the R [`anndata`](https://github.com/rcannood/anndata) whenever a new version of Python anndata is about to be released. I could also just watch the anndata releases and fetch a diff between versions to do pretty much the same thing.

Thanks for taking a look at this,
Robrecht

**Comment by LuckyMD** [comment]
Hi @rcannood, 

The AnnData R version looks interesting. I guess the idea here is to store as h5ad directly from R? So far we've being working with conversion to SingleCellExperiment objects and back to Anndata in python via [Zellkonverter](https://github.com/theislab/zellkonverter) (from R) and [Anndata2ri](https://github.com/theislab/anndata2ri) (from python). Is there something you think cannot be stored in an SCE object that is stored in AnnData? Or is it just the joint R and python environment that you perceive as a hindrance?

**Comment by rcannood** [comment]
> I guess the idea here is to store as h5ad directly from R?

No, I interface directly with Python's anndata API, in order to provide exactly the same experience with anndata in R as in Python.

Zellkonverter is certainly an interesting project, but in my case I want to avoid having to convert between SCE and h5ad every time I switch from R to Python and back -- I just want to use h5ad all the way through the pipeline. Does this make sense?

**Comment by LuckyMD** [comment]
I see... so you reimplemented the data structure in R and are directly mapping to the python functions to use the R anndata structure. That's pretty cool.

I guess I'm the wrong person to ask about whether we are happy with this, but I like it! Do you then just interface with other scanpy functions directly via this package and reticulate?

**Comment by flying-sheep** [comment]
That’s pretty cool! I’m okay with you using our “brand”, let’s hear from the others though.

I guess reticulate does end up copying data in the end right? So even though Python and R live in the same process, accessing some big array from R means it’s being copied from Python’s memory to R’s?

**Comment by falexwolf** [comment]
Cool! 😄  Happy to announce this and link from the anndata webpage if @ivirshup is also on board!

**Comment by falexwolf** [comment]
Can we invite you to the Scanpy + anndata Slack? So that you're better in the loop on things?

**Comment by rcannood** [comment]
> So even though Python and R live in the same process, accessing some big array from R means it’s being copied from Python’s memory to R’s?

I'm not 100% sure how reticulate works when it comes to this, but I think so, yes.

It would be good to try how well my setup works when dealing with large h5ad files.

> Cool! smile Happy to announce this and link from the anndata webpage if @ivirshup is also on board!

That's nice to hear :) Before making any announcements, let me first write some more unit tests to ensure that everything works properly!

> Can we invite you to the Scanpy + anndata Slack? So that you're better in the loop on things?

Sure, that might help me to keep on top of things :)

**Comment by lazappi** [comment]
Just stumbled across this, pretty cool! @rcannood I think the goals are slightly different but there might be some overlap between this and **zellkonverter** that we can explore. Happy to discuss anyway.

**Comment by rcannood** [comment]
@lazappi Good idea :) Maybe we can talk about this on the scanpy slack?

I'm going to close this issue, since it --in essence-- my R wrapper has no impact on this repository ¹.

I'd just like to mention that the R anndata works pretty seamlessly with scanpy through reticulate. 

```
ad <- anndata::read_h5ad("dataset.h5ad")

ad$raw <- ad

sc <- reticulate::import("scanpy")
sc$pp$normalize_per_cell(ad)

ad$X

##        var1 var2     var3
## s1 1.166667  3.5 5.833333
## s2 1.750000  3.5 5.250000

ad$raw

##    var1 var2 var3
## s1    1    3    5
## s2    2    4    6
```

I'm still porting more of the python unit tests to R and encountering small discrepancies along the way. WIP :)


¹ (other than that I'm continuously bringing up other issues ;))

**Comment by flying-sheep** [comment]
> other than that I'm continuously bringing up other issues

Perfect :D
