### ISSUE TITLE
del adata.raw

### ISSUE THREAD

**Issue by rcannood** [theislab/anndata#445]
Hello all!

[Quoting](https://github.com/theislab/anndata/blob/77a633cc825b428d02dabdf75491841c3a175a8d/anndata/_core/anndata.py#L738) from AnnData documentation:

> Its content can be deleted:
> ```
> adata.raw = None
> # or
> del adata.raw
> ```

Running `adata.raw = None` throws an error, however:
```
>>> adata_dense.raw = None
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/rcannood/.local/lib/python3.8/site-packages/anndata/_core/anndata.py", line 756, in raw
    raise ValueError(
ValueError: Can only init raw attribute with an AnnData object. Do `del adata.raw` to delete it
```

Could you add `if raw is None` to the raw setter?

Robrecht

**Comment by ivirshup** [comment]
Haha, sounds reasonable. Thanks for the report!
