### ISSUE TITLE
Is there a way to merge adata objects with vars ordered differently

### ISSUE THREAD

**Issue by xguse** [theislab/anndata#458]
I am trying to integrate and batch correct scRNA data from multiple experiments. I have found a package called scanorama that provides a convenient wrapper for anndata objects. The method seems to generate low dimensional embeddings that suggest it is performing relatively well. The problem comes because scanorama re-orders the var axis to be sorted alphabetically in the corresponding corrected anndata objects it produces, while the original anndata objs are NOT sorted.

I have a ton of important information in the original anndata objs that is NOT retained in the corrected anndata objects scanpy produces as discussed here (https://github.com/brianhie/scanorama/issues/57). In addition to this the index of the originals `obs` table is obliterated and replaced with numbers (but the order here is NOT changed).

I believe that I can simply do this to faithfully regain annotations in the original `obs` axis 
```
corrected.obs = original.obs
``` 
because this order is not altered but I have important data saved about the genes in `var` as well as the other attributes in the original that I really want/need in the corrected anndata object. The author suggested ensuring that the `var` axis be sorted prior to being provided to the scanorama function but I must admit that I am not sure how to do this even. My explorations lead me to believe that I do not understand the "guts" of these objects well enough to know if I am on the right track.

The following
```
adata[:,["OR4F5", "FAM138A"]].copy().X != adata[:,["FAM138A","OR4F5"]].X.copy()
```
shows no alteration to the `X` attributes but the corresponding `var` attributes reflect the altered order.

Is there a way to import the corrected anndata object as a "layer" or "view" accessible from the original? Or perhaps is there a better way than I have thought of so far to integrate these two very important versions of my data?

Thank you for your tool and any advice/guidance you are able to provide!

**Comment by Koncopd** [comment]
Hi, @xguse . You can reorder variables in adata objects like this
```
adata = sc.datasets.pbmc3k_processed()
sorted_var_names = np.sort(adata.var_names)
sorted_genes_adata = adata[:, new_var_names].copy() # or without copy, then you get a view
```

**Comment by brianhie** [comment]
I just wrote up a new version of Scanorama that preserves .obs in the corrected output.

You can also now just do integration (which [benchmarks better](https://www.biorxiv.org/content/10.1101/2020.05.22.111161v2) than "batch correction") if you are only concerned with clustering/visualization. Scanorama v1.7 just adds this to the adatas as `adata.obsm['X_scanorama']`.

Hope that helps!

**Comment by ivirshup** [comment]
`ad.concat` with an inner merge will keep the variable ordering from the first `AnnData`. 

@Koncopd, minor efficiency point: `adata[:, np.argsort(adata.var_names)].copy()` will be a bit more efficient than `adata[:, np.sort(adata.var_names)].copy()` since you don't have to map the strings to indices a second time.

> shows no alteration to the X attributes but the corresponding var attributes reflect the altered order.

@xguse, I'm not sure I understand what you're saying here. Those two `X` values should definitely be different. Is that not what you're seeing?

**Comment by xguse** [comment]
> I just wrote up a new version of Scanorama that preserves .obs in the corrected output.
> 
> You can also now just do integration (which [benchmarks better](https://www.biorxiv.org/content/10.1101/2020.05.22.111161v2) than "batch correction") if you are only concerned with clustering/visualization. Scanorama v1.7 just adds this to the adatas as `adata.obsm['X_scanorama']`.
> 
> Hope that helps!

I believe that the issue is not SO much the obs. You already said that the obs are not re-ordered. It IS nice to keep the labels however, I agree. But the real issue here is the potential misalignment of the gene names in the **var** attribute.

**Comment by xguse** [comment]
@ivirshup 


> 
> > shows no alteration to the X attributes but the corresponding var attributes reflect the altered order.
> 
> @xguse, I'm not sure I understand what you're saying here. Those two `X` values should definitely be different. Is that not what you're seeing?

They are not different if I am performing the inequality comparison correctly?

![image](https://user-images.githubusercontent.com/138931/99680982-a68b6880-2a4b-11eb-8ef9-14adfe2a5088.png)

**Comment by xguse** [comment]
Wait... I just realized that the values in X man NOT have changed because they are likely all zeros and reordered zeros would be indistinguishable. 

Let me try specifically chosen genes that HAVE DATA...

**Comment by xguse** [comment]
@ivirshup 

Ok. that was the problem. I just happened to randomly choose two genes that are zero across the board. So reordering them is undetectable via equality testing. Choosing populated genes shows the expected behavior.

![image](https://user-images.githubusercontent.com/138931/99682046-d5eea500-2a4c-11eb-8132-d01fbf28d6d3.png)

**Comment by xguse** [comment]
@brianhie


> You can also now just do integration (which [benchmarks better](https://www.biorxiv.org/content/10.1101/2020.05.22.111161v2) than "batch correction") if you are only concerned with clustering/visualization. Scanorama v1.7 just adds this to the adatas as `adata.obsm['X_scanorama']`.

Unfortunately the integration can already be incorporated directly into the original adata object through adding a new attribute and referencing THAT reduced dimension when forming the KNN graph and subsequent UMAP representations. And it DOES seem to work well! (thank you for that!)

What I need now is to be able to more appropriately evaluate differential gene expression across 10X encapsulations to minimize the effect of batch. So, unless I am mistaken, I need the corrected adata objects, no?

**Comment by LuckyMD** [comment]
> What I need now is to be able to more appropriately evaluate differential gene expression across 10X encapsulations to minimize the effect of batch. So, unless I am mistaken, I need the corrected adata objects, no?

I would advise against this. Instead, use a model that can take count data and add a batch covariate in there. Not sure I would trust corrected data outputs. I argue this in our best-practices [paper](http://msb.embopress.org/lookup/doi/10.15252/msb.20188746)

**Comment by xguse** [comment]
@LuckyMD 

Thats certainly a valid point and I tend to agree in general. So given that general concession, why would one ever "correct" the data? What purpose does producing this output serve? Where are people using it?

Secondly, is it not slightly dishonest or at least a bit misleading to display UMAPs from integrated/batch-accommodating reduced dimensions alongside diff gene expression results that arise from data treated differently?

**Comment by LuckyMD** [comment]
I think it's typically used to get a more accurate representation of relative distances between cells, for example for clustering, trajectory analysis or other cell-level analysis methods. Gene-level analysis tends to be about statistical modeling, which relies on assumed noise distributions that will no longer hold upon data correction.

> Secondly, is it not slightly dishonest or at least a bit misleading to display UMAPs from integrated/batch-accommodating reduced dimensions alongside diff gene expression results that arise from data treated differently?

Hmm... I'm not sure about this. I think it has to do with being conservative. I correct my data to get the most accurate representation of the underlying biological signal to use to e.g., generate UMAP embeddings. But if I use that version of the data, I'm violating the assumptions of my DE analysis framework that has its own way to deal with batch effects and can account for the way the data is generated (e.g, by NB noise). I would still assume that overall the batch effects are better accounted for in a non-linear method, but I choose to be more conservative in my DE test by using only a linear correction and assigning the remaining variance to background variance against which my DE shift will be evaluated.

I just found a new relevant [paper](https://www.pnas.org/content/early/2020/11/17/2001238117) from Jeff Leek about statistical modeling of inferred/predicted outputs that is relevant to this discussion today
