### ISSUE TITLE
Issue with merging subsets

### ISSUE THREAD

**Issue by vladie0** [theislab/anndata#460]
Subsetting in scanpy is well documented and straightforward, for example, if I would want to remove mitochondrial genes, the tutorial suggest to perform this as such:

```python
mt_genes = rna.var_names.str.startswith(‘MT-’)
inv_mt_genes=[not elem for elem in mt_genes]

rna_MT=[:,mt_genes]
rna_without_MT=rna[:,inv_mt_genes]
```

However, what if after analysis (normalization, etc…) I want to add the mt_genes back to the the rna_without dataset. With other word, I can’t figure out how to combine 2 subsets, it would if someone could help me how rna_MT and rna_without_MT, which are complementary, could be merged again. This could not make sense for this easy sample but does make sense for multi-layered data such as in my case.

**Comment by ivirshup** [comment]
Are you looking for something like this?

```python
rna = sc.concat([rna_MT, rna_without_MT], axis=1)
```

There are additional docs for this function [here](https://anndata.readthedocs.io/en/latest/concatenation.html#)
