### ISSUE TITLE
concatenate and layers 2

### ISSUE THREAD

**Issue by 117999** [theislab/anndata#480]
Hi, 
I have got a problem about the concatenate function in anndata. (considering to add layers)
When we processed our data, we have to concatenate the two loom files into one adata, and distinguish their identity into different layers in the adata file. 
So, we have tried the adata.read_loom() to import these two loom files, and tried to labelled them before concatenate. 
However, when we tried to concatenate the two files, it reports an index error.
Could anyone help me with it. 
Thx a lot.

**Comment by ivirshup** [comment]
Could you post the error?

**Comment by 117999** [comment]
sorry for not posting the error
the error is
`InvalidIndexError: Reindexing only valid with uniquely valued index objects`

**Comment by ivirshup** [comment]
I can't be sure without a full example and stack trace, but I think what's happening is that the axis not being concatenated has non-unique names. Here's an example:

```python
import anndata as ad, pandas as pd, numpy as np

# Creating these will warn you about non-unique var_names
a = ad.AnnData(
    np.ones((5, 5)),
    obs=pd.DataFrame(index=list("abcde")),
    var=pd.DataFrame(index=list("ffghi")),
)
b = ad.AnnData(
    np.ones((5, 5)),
    obs=pd.DataFrame(index=list("abcde")),
    var=pd.DataFrame(index=list("ffghi")),
)

ad.concat({"a": a, "b": b})
# InvalidIndexError: Reindexing only valid with uniquely valued Index objects
```

<details>
<summary> Full traceback </summary>

```pytb
<ipython-input-8-67af5ca4a545> in <module>
----> 1 ad.concat({"a": a, "b": b})

~/github/anndata/anndata/_core/merge.py in concat(adatas, axis, join, merge, uns_merge, label, keys, index_unique, fill_value, pairwise)
    803         [dim_indices(a, axis=alt_axis) for a in adatas], join=join
    804     )
--> 805     reindexers = [
    806         gen_reindexer(alt_indices, dim_indices(a, axis=alt_axis)) for a in adatas
    807     ]

~/github/anndata/anndata/_core/merge.py in <listcomp>(.0)
    804     )
    805     reindexers = [
--> 806         gen_reindexer(alt_indices, dim_indices(a, axis=alt_axis)) for a in adatas
    807     ]
    808 

~/github/anndata/anndata/_core/merge.py in gen_reindexer(new_var, cur_var)
    396            [1., 0., 0.]], dtype=float32)
    397     """
--> 398     return Reindexer(cur_var, new_var)
    399 
    400 

~/github/anndata/anndata/_core/merge.py in __init__(self, old_idx, new_idx)
    266         self.no_change = new_idx.equals(old_idx)
    267 
--> 268         new_pos = new_idx.get_indexer(old_idx)
    269         old_pos = np.arange(len(new_pos))
    270 

/usr/local/lib/python3.8/site-packages/pandas/core/indexes/base.py in get_indexer(self, target, method, limit, tolerance)
   2984 
   2985         if not self.is_unique:
-> 2986             raise InvalidIndexError(
   2987                 "Reindexing only valid with uniquely valued Index objects"
   2988             )

InvalidIndexError: Reindexing only valid with uniquely valued Index objects
```

</details>

Basically, the issue is that when you have two variables with the same name we can't know which one to use.

If this is the case, I'd suggest making the indices unique either by `.var_names_make_unique` or by choosing identifiers which should already be unique (e.g. ensembl ids instead of gene symbols).

**Comment by ivirshup** [comment]
@117999, did that solve your issue?
