### ISSUE TITLE
Error while reading H5AD file into R using reticulate()

### ISSUE THREAD

**Issue by aditisk** [theislab/anndata#481]
Hello,

I'm not sure if this is the right place to post this issue so apologies in advance. I'm trying to using the reticulate() package to load my h5ad file in R and getting an error message:

`Error in py_call_impl(callable, dots$args, dots$keywords) : 
  AttributeError: 'dict' object has no attribute 'dtype' `

Scanpy version numbers used to create h5ad file:

`scanpy==1.4.5.post2 anndata==0.7.1 umap==0.3.10 numpy==1.18.1 scipy==1.4.1 pandas==1.0.1 scikit-learn==0.22.2 statsmodels==0.11.1 python-igraph==0.8.0`

I saw posts about anndata0.7 and later causing issues but I have already saved my h5ad files using this version. If I downgrade my anndata version, I believe files generated by the newer version will not get loaded ? How should I proceed with overcoming this issue ?

Thanks a lot.

**Comment by ivirshup** [comment]
I think I'd have to see a longer traceback to figure out what's happening. Can you read that file from python?

**Comment by aditisk** [comment]
Hi @ivirshup, I can read the file from Python. What I landed up doing was converting the h5ad to a Seurat object using SeuratDisk and then used it in R. It worked that way so my problem is solved for now.

**Comment by ivirshup** [comment]
That's good. Please let us know if that issue crops up again. My uninformed guess was that `reticulate` may be using a much older version of anndata, but I couldn't say for sure without more info.
