### ISSUE TITLE
Adding columns to matrix

### ISSUE THREAD

**Issue by TheAustinator** [theislab/anndata#485]
I'm interested in adding columns to adata.X and adata.var as opposed to adata.obs so that they can be included in normalization, dim reduction, etc. Is there currently a simple interface to do this? If not, I'm more than happy to contribute this feature if it resonates with you guys -- two potential ways to integrate it into the api would be:
1. ` adata[:, "ALL_TCR"] = ...`
2. `ad.concat([adata_1, adata_2], axis=1)` where `adata_1` could be e.g. 30k genes x 10k cells and `adata_2` could be 1 feature x 10k cells.

**Comment by ivirshup** [comment]
Doesn't option 2 work right now?

**Comment by TheAustinator** [comment]
Ohh, my mistake -- I was looking at `anndata.concatenate` rather than `anndata.concat`. Thanks!

**Comment by ivirshup** [comment]
No worries!
