### ISSUE TITLE
Anndata.write error

### ISSUE THREAD

**Issue by hahia** [theislab/anndata#494]
Hello, when I run 
`adata.write('../HCC14_F2.h5ad', compression='gzip')`
![image](https://user-images.githubusercontent.com/49113803/104418244-91493b00-55b1-11eb-8684-a81ba2325037.png)

The version info
![image](https://user-images.githubusercontent.com/49113803/104418011-3fa0b080-55b1-11eb-9a80-effc7c1829bc.png)

Does anyone know how to solve this problem? Thank you for your help.

**Comment by ivirshup** [comment]
It looks like `h5py` is having trouble creating the file at all. Does this work in the directory you're trying to write to?

```python
import h5py

with h5py.File("tmp.h5", "w"):
    pass
```

**Comment by hahia** [comment]
> It looks like `h5py` is having trouble creating the file at all. Does this work in the directory you're trying to write to?
> 
> ```python
> import h5py
> 
> with h5py.File("tmp.h5", "w"):
>     pass
> ```
I try this
![image](https://user-images.githubusercontent.com/49113803/104863531-388eef00-5971-11eb-8269-bd27d059e36f.png)
It still can't save file

**Comment by ivirshup** [comment]
I think error has to do with your h5py install, and I don't think I can help with that. I'd recommend opening an issue over the [h5py project](http://github.com/h5py/h5py).

**Comment by hahia** [comment]
> I think error has to do with your h5py install, and I don't think I can help with that. I'd recommend opening an issue over the [h5py project](https://github.com/h5py/h5py).

Ok, thank you very much
