### ISSUE TITLE
Assigning sparse matrix with an unary dimension to .X throws an error 

### ISSUE THREAD

**Issue by WeilerP** [theislab/anndata#500]
## Description

The conversion of a dense entry in `X`, `AnnData.layers` or `AnnData.obsm` to a sparse matrix fails:

```python
>>> import numpy as np
>>> from scipy.sparse import csr_matrix
>>> 
>>> from anndata import AnnData
>>> 
>>> adata = AnnData(np.ones((1, 1)))
>>> adata.X = csr_matrix(adata.X)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/anaconda3/envs/anndata_bug/lib/python3.8/site-packages/anndata/_core/anndata.py", line 655, in X
    or (self.n_vars == 1 and self.n_obs == len(value))
  File "/opt/anaconda3/envs/anndata_bug/lib/python3.8/site-packages/scipy/sparse/base.py", line 295, in __len__
    raise TypeError("sparse matrix length is ambiguous; use getnnz()"
TypeError: sparse matrix length is ambiguous; use getnnz() or shape[0]
```

I ran the code using both `anndata==0.7.4` and `anndata==0.7.5`.

**Comment by ivirshup** [comment]
Huh. That's weird.

Looks like it has something to do with `X` being having a size of `(1, 1)`. For example, this works:

```python
adata = AnnData(np.ones((10, 10)))
adata.X = csr_matrix(adata.X)
```

I bet this has to do with old machinery which would have `a[1, 1].X` return an int.

**Comment by WeilerP** [comment]
Hm, yes, your example works. However, the cases

```python
adata = AnnData(np.ones((10, 1)))
adata.X = csr_matrix(adata.X)
```

and

```python
adata = AnnData(np.ones((1, 10)))
adata.X = csr_matrix(adata.X)
```

fail with the same error message as before.

**Comment by ivirshup** [comment]
Looks like the issue was us trying to handle cases like `a.X = [1, 2, 3]`, so I've just made it that we check for the `shape` attribute before trying `len`.
