### ISSUE TITLE
Incorrect attribute names in AnnData write_loom()

### ISSUE THREAD

**Issue by ACastanza** [theislab/anndata#509]
Loom file created by anndata names the gene and sample attributes incorrectly. In the AnnData loom they are called "var_names" and "obs_names" containing the Gene IDs and Cell IDs respectively, but the expected name for the attribute "var_names" is "Gene" and for "obs_names", "CellID". This is what the attributes are named in the Loompy sample files, and are what is expected by, for example, seurat's function to load loom files.

If you create an attribute named "Gene" or "CellID", AnnData.write_loom seems to ignore those attributes.

I believe this change https://github.com/theislab/anndata/pull/508 will allow AnnData to write out files with the expected attribute names for downstream analysis.

**Comment by ivirshup** [comment]
@VolkerBergen, I believe you're more familiar with the `loom` format. Any thoughts on this? Is this part of the `loom` spec?

**Comment by ivirshup** [comment]
I would be up for using `adata.var_names.name` and `adata.obs_names.name` if they are defined, but I'm not up for defaulting to a convention which we don't use and I can't find a spec for. Does this sound reasonable to you @ACastanza?

**Comment by VolkerBergen** [comment]
If you were to continue with Seurat after velocity analysis, you'd want to have them called `Gene` and `CellID`, I agree. Yet, I would not change the convention, but rather allow this to be optionally set as @ivirshup suggested, either through the `name` attribute, and/or duplicating the `read_loom` attributes to `write_loom`.

**Comment by ACastanza** [comment]
Sorry, my health system was sending github emails to spam. I don't think this fixes the issue. Anndata produced loom files will still not have the proper variable names to be read in with loompy or seurat's built in loom parser (unless they adopt your changes here).

@ivirshup the spec for loom is here: http://linnarssonlab.org/loompy/format/index.html and it does define CellID for col_attrs, although it doesn't explicitly specify Gene as the row_attrs.

**Comment by ivirshup** [comment]
@ACastanza from my reading of that document I don't see `CellID` as a required dataset name. To me it looks like an example of a dataset name that could be in `col_attrs`. It also says `CellID` has float entries, which we don't allow in `obs_names` or `var_names`.
