### ISSUE TITLE
Documentation of `.layers`

### ISSUE THREAD

**Issue by falexwolf** [theislab/anndata#51]
Hi @Koncopd,

would you write a proper documentation of the `.layers` attribute you built?  Currently, it's only a very non-informative stub:
https://anndata.readthedocs.io/en/latest/anndata.AnnData.layers.html
It should contain a reference to loompy, scvelo and very basic examples.

Here, even the heading in the table is missing:
https://anndata.readthedocs.io/en/latest/anndata.AnnData.html

**Comment by Koncopd** [comment]
Hi, @falexwolf,
Yes, i'll add the needed details.

**Comment by falexwolf** [comment]
Great, I saw https://github.com/theislab/anndata/commit/4358768532b24877f9b07b260009a4a43a3e4b8e!
