### ISSUE TITLE
Can't find module 

### ISSUE THREAD

**Issue by rachel662** [theislab/anndata#511]
Hi there
I'm trying to access anndata through R using reticulate, but when I do this occurs
I can see that i have sucessfully installed anndata through both pip and conda forge but it still won't find it? 

would anyone be able to help me with this 
thanks 
Rachel 

error in py_module_import(module, convert = convert) :    ModuleNotFoundError: No module named 'anndata'  Detailed traceback:    File "/Library/Frameworks/R.framework/Versions/4.0/Resources/library/reticulate/python/rpytools/loader.py", line 19, in _import_hook     module = _import(   File "/Library/Frameworks/R.framework/Versions/4.0/Resources/library/reticulate/python/rpytools/loader.py", line 19, in _import_hook     module = _import(

**Comment by ivirshup** [comment]
I think this is a bit out of scope for our issue tracker, but I believe @lazappi or @rcannood could probably point you to some useful resources for handling this.

**Comment by lazappi** [comment]
Most likely **{reticulate}** is finding a different Python environment to where you have installed **anndata**. The "Python Version Configuration" vignette is probably a good place to start for checking that https://rstudio.github.io/reticulate/articles/versions.html.
