### ISSUE TITLE
Error loading in UMAP layer 

### ISSUE THREAD

**Issue by rachadele** [theislab/anndata#525]
Hi there,

I am trying to create an h5ad file from a raw expression matrix, a metadata file and UMAP coordinates. I'm getting the following error loading in anndata.obsm['X_umap']:

`ValueError: value.index does not match parent’s axis 0 names`

the index values for the UMAP tsv and the metadata file used to create .obs are exactly the same, so i'm not sure what's causing this. I did run .var_names_make unique on the matrix, but from my understanding that doesn't apply to the index column. let me know if anyone can help!

**Comment by ivirshup** [comment]
I think you could do:

`adata.obsm["X_umap"] = umap_df.set_index(adata.obs_names)`

But it would be good to check on your end if:

```python
assert adata.obs_names.equals(umap_df.index)
```

But I'm not completely sure I'm understanding what you're doing correctly. Could you provide a small code example to show what you're trying to do?

**Comment by rachadele** [comment]
hi, thanks for your response! 
I ran the assert command and it didn't return anything. then I tried to set the umap indexes to the anndata.obs_names but got the same error I mentioned above. here is the code I'm using:

matrix=ad.read_csv("mat_combined.tsv.transposed",delimiter='\t')
matrix.var_names_make_unique()
meta=pd.read_csv("Purkayastha_merged_metadata.txt",sep='\t',index_col=0)
umap=pd.read_csv("umap.tsv",sep='\t',index_col=0)
matrix.obs=meta
matrix.obsm['X_umap']=umap

let me know if you would like to see the files I'm using!

**Comment by ivirshup** [comment]
Hmm, yeah that seems like it should work to me.

Sharing those files would be very helpful, thanks!

**Comment by rachadele** [comment]
hi, sorry for the delayed response! here is a google drive link to the matrix, umap and metadata files. [](https://drive.google.com/drive/folders/1sXPwhpnBmP2RrNO56Jei5xnVglcU-T_B?usp=sharing)

**Comment by ivirshup** [comment]
I think this has actually been fixed on master, but not in a release yet.

This package could definitely use a bugfix release, so I'm aiming to do that over the long weekend.
