### ISSUE TITLE
Anndata.concatenate() fails when .X has a dimension of size 0

### ISSUE THREAD

**Issue by chris-rands** [theislab/anndata#526]
```
>>> from anndata import AnnData
>>> import numpy as np
>>> adata = AnnData(X=np.empty([1,0]))
>>> adata
AnnData object with n_obs × n_vars = 1 × 0
>>> AnnData.concatenate(adata, adata)
```

Error:
`IndexError: index 0 is out of bounds for axis 0 with size 0`

Running anndata '0.7.5'

The reason this is an issue for me is that the scirpy TCR package builds adata like that https://github.com/icbi-lab/scirpy/blob/507c943e50a2d2ba5b0011575030db85dd5b316b/scirpy/io/_convert_anndata.py#L81

A fix or workaround would be great, thanks

**Comment by ivirshup** [comment]
Huh, I don't think I thought of this case. Could probably use a test.

In general I would recommend using `anndata.concat` instead, which does seem to work here.

```python
import anndata as ad
import numpy as np
a = ad.AnnData(np.ones((1, 0)))
ad.concat([a, a])
```

**Comment by chris-rands** [comment]
Great, thanks, I didn't know about `anndata.concat()`. I can confirm that it works for my use case. Since it looks like `Anndata.concatenate()` will be deprecated, perhaps not necessary to fix this

**Comment by LuckyMD** [comment]
Quick question... `concat` does the same as `concatenate` and a bit more, no? The main difference is feeding in a list vs separate objects, and the merging. I haven't seen input parameters as there's no documentation for the function other than the long example notebook. We're relying on `concatenate` in `scIB` to concatenate scanorama output (https://github.com/theislab/scib/blob/7d11d7959baaebc3ad588356407a78ac2c3271f4/scIB/integration.py#L26-L28).

**Comment by chris-rands** [comment]
The argument names appear a bit different e.g. batch_key>label, batch_categories>keys

**Comment by grst** [comment]
I can update scirpy's [tutorial section](https://icbi-lab.github.io/scirpy/tutorials/tutorial_io.html#Combining-multiple-samples) to use `concat` as well. When I wrote it `concat` was still considered experimental. 

-->  https://github.com/icbi-lab/scirpy/issues/255

**Comment by ivirshup** [comment]
`concatenate` even uses `concat` internally now, with some special handling for backwards compatibility. @LuckyMD, the function is [documented here](https://anndata.readthedocs.io/en/latest/anndata.concat.html), though I suppose it isn't documented in scanpy.

**Comment by LuckyMD** [comment]
I see. I was looking under `AnnData.anndata`.

**Comment by gokceneraslan** [comment]
One thing that sometimes confuses me is the lack of documentation for "scanpy.concat" (which actually is imported from anndata) on the scanpy documentation page. A bit strange to be able to access the function but not finding documentation of it and/or pointers to anndata.concat documentation. 

For example, for the IO functions borrowed from anndata we have this line:

`Read other formats using functions borrowed from anndata`

at https://scanpy.readthedocs.io/en/stable/api/index.html#reading, but we don't mention scanpy.concat anywhere at all.

**Comment by ivirshup** [comment]
> One thing that sometimes confuses me is the lack of documentation for "scanpy.concat" (which actually is imported from anndata) on the scanpy documentation page. A bit strange to be able to access the function but not finding documentation of it and/or pointers to anndata.concat documentation.

Yeah, it is in a bit of a weird spot. We could add a section for `AnnData` that links to parts of the anndata documentation at the top of the API docs?

**Comment by gokceneraslan** [comment]
@ivirshup the following code (from my poor man's reindex) still errors out, is this expected? (axis=0 version still works though)

```python
import scanpy as sc
import pandas as pd
import anndata as ad
import numpy as np

adata = sc.datasets.paul15()
labels = ['A', 'B', '0', '1']

ph = ad.AnnData(np.ones([len(labels), 0]), obs=pd.DataFrame(index=labels))   
ret = ad.concat([adata, ph], join='outer', axis=1)
```

```pytb
WARNING: In Scanpy 0.*, this returned logarithmized data. Now it returns non-logarithmized data.
... storing 'paul15_clusters' as categorical
Trying to set attribute `.uns` of view, copying.

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-2-70a65516d436> in <module>
      8 
      9 ph = ad.AnnData(np.ones([len(labels), 0]), obs=pd.DataFrame(index=labels))
---> 10 ret = ad.concat([adata, ph], join='outer', axis=1)

~/Code/anndata/anndata/_core/merge.py in concat(adatas, axis, join, merge, uns_merge, label, keys, index_unique, fill_value, pairwise)
    820     )
    821 
--> 822     X = concat_arrays(
    823         [a.X for a in adatas], reindexers, axis=axis, fill_value=fill_value
    824     )

~/Code/anndata/anndata/_core/merge.py in concat_arrays(arrays, reindexers, axis, index, fill_value)
    425         )
    426     else:
--> 427         return np.concatenate(
    428             [
    429                 f(x, fill_value=fill_value, axis=1 - axis)

<__array_function__ internals> in concatenate(*args, **kwargs)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2732 and the array at index 1 has size 4
```

**Comment by ivirshup** [comment]
@gokceneraslan I've opened a new issue for that since it seems different. I certainly think it's a weird thing to do (since you are extending axis=1 with no elements), but I can't think of a reason why we would want to error for that. It's also a different bug from this since it's coming from different code.

**Comment by gokceneraslan** [comment]
Thanks! You are paving the way to reindex and align maybe 😛
