### ISSUE TITLE
obs annotation added as bound method

### ISSUE THREAD

**Issue by mezwick** [theislab/anndata#557]
Hi,
I have multiple anndata objects (adata1, adata2, adata3...) that I want to concatenate. Rather than specify keys to track these adata objects at the point of concatenation, I'd like to add a string categorical label as an annotated observation to each adata object individually.

i.e.
```
adata1.obs['sample'] = 'sample1'
adata2.obs['sample'] = 'sample2'
adata3.obs['sample'] = 'sample3'
```
Then concatenate in a later step. 

However, these annotations keep getting added to my adata objects as a bound method rather than as a dtype. 

How do i ensure my string annotations are added as a dtype? (ultimately to be categorical in later concatenated adatas)
Thanks!

**Comment by ivirshup** [comment]
To make sure I'm understanding correctly, is something like this not working for you?

```
a.obs["label"] = "a"
b.obs["label"] = "b"
combined = anndata.concat([a, b])
combined.obs["label"]
```


I'm a little confused about what you mean by this: 

> However, these annotations keep getting added to my adata objects as a bound method rather than as a dtype.

Could you elaborate on this? An example would be great.

**Comment by mezwick** [comment]
Apologies, but this is a big error on my part in terms of calling the annotation from obs.

As per your example...
```
a.obs["label"] = "a"
b.obs["label"] = "b"
combined = anndata.concat([a, b])
combined.obs["label"]
```
Returns the list

But I had been calling 
``` 
combined.obs.label
```
which returned 
```<bound method NDFrame.sample of      cell_ids   area  sample```
