### ISSUE TITLE
Tarball on PyPI doesn't contain setup.py

### ISSUE THREAD

**Issue by yurivict** [theislab/anndata#561]

**Comment by ivirshup** [comment]
Can you give some more details on why this is an issue? `anndata` is installable from that tarball.

<details>
<summary> Example: </summary>

```sh
$ conda create -yn anndata-pypi-tarball python=3.8 pip
...
$ conda activate anndata-pypi-tarball
$ which pip
/Users/isaac/miniconda3/envs/anndata-pypi-tarball/bin/pip
$ pip install ./anndata-0.7.6.tar.gz
Processing ./anndata-0.7.6.tar.gz
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
    Preparing wheel metadata ... done
Collecting scipy>1.4
  Using cached scipy-1.6.3-cp38-cp38-macosx_10_9_x86_64.whl (30.8 MB)
Collecting numpy>=1.16.5
  Using cached numpy-1.20.2-cp38-cp38-macosx_10_9_x86_64.whl (16.0 MB)
Collecting h5py
  Using cached h5py-3.2.1-cp38-cp38-macosx_10_9_x86_64.whl (2.9 MB)
Collecting pandas>=1.1.1
  Using cached pandas-1.2.4-cp38-cp38-macosx_10_9_x86_64.whl (10.5 MB)
Collecting packaging>=20
  Using cached packaging-20.9-py2.py3-none-any.whl (40 kB)
Collecting xlrd<2.0
  Using cached xlrd-1.2.0-py2.py3-none-any.whl (103 kB)
Collecting natsort
  Using cached natsort-7.1.1-py3-none-any.whl (35 kB)
Collecting pyparsing>=2.0.2
  Using cached pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
Collecting python-dateutil>=2.7.3
  Using cached python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
Collecting pytz>=2017.3
  Using cached pytz-2021.1-py2.py3-none-any.whl (510 kB)
Collecting six>=1.5
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Building wheels for collected packages: anndata
  Building wheel for anndata (PEP 517) ... done
  Created wheel for anndata: filename=anndata-0.7.6-py3-none-any.whl size=73463 sha256=807f80748cc8129b7d4b2dcfaf681805664262cddf2af9f4505f87ba16cebfed
  Stored in directory: /Users/isaac/Library/Caches/pip/wheels/80/e9/08/ab581a8fe1f35039ec0bd78475f01fbc0be2a949881e742555
Successfully built anndata
Installing collected packages: six, pytz, python-dateutil, pyparsing, numpy, xlrd, scipy, pandas, packaging, natsort, h5py, anndata
Successfully installed anndata-0.7.6 h5py-3.2.1 natsort-7.1.1 numpy-1.20.2 packaging-20.9 pandas-1.2.4 pyparsing-2.4.7 python-dateutil-2.8.1 pytz-2021.1 scipy-1.6.3 six-1.16.0 xlrd-1.2.0
```

</details>

**Comment by yurivict** [comment]
Python ports on FreeBSD are built with Python's distutils which expect ```setup.py```.

**Comment by ivirshup** [comment]
I'm not sure I see this as an issue with anndata. I don't think we say anywhere that we support installation with `distutils`. As it's [scheduled to be deprecated](https://www.python.org/dev/peps/pep-0632/) I don't think there's a lot of incentive to start saying that. It's also my impression users on freebsd can use pip or conda to install anndata (though conda may take some doing).

Would this issue fit better with the freebsd python ports project?

**Comment by yurivict** [comment]
I am not an expert in Python, I only maintain some Python ports.
I will ask about this.

**Comment by flying-sheep** [comment]
If `setup.py` is an expectation FreeBSD has about Python packages, it slept on the standardization process that was [decided on 6 years ago](https://www.python.org/dev/peps/pep-0517/).

I assume a good generic packaging system will look like this (`build()` in the present, `package()` in the future):

```bash
srcdir=...
distroot=...

pydistname=...
pyversion=...

build() {
    cd "$srcdir"
    # Check if the PEP 517 build-backend is specified in a TOML file
    if toml get pyproject.toml build-system.build-backend; then
        # Standard build via https://pypa-build.readthedocs.io/
        # we rely on dependencies being installed in the system
        python3 -m build --skip-dependencies --no-isolation --wheel
    elif [ -f setup.py ]; then
        # Legacy build
        python setup.py build bdist_wheel
    else
        echo 'Neither a PEP 517 build system nor a legacy setup.py found, exiting' >&2
        exit 1
    fi
}

package() {
    cd "$srcdir"
    # Once this one has a CLI https://installer.readthedocs.io/en/latest/
    python3 -m installer "dist/$pydistname-$pyversion-py3-none-any.whl" --root="$distroot"
}
```

**Comment by flying-sheep** [comment]
Background: There’s different expectations about installing things.

Users want a painless experience. Binary packages for their platform are a nice thing. They’ll therefore use `pip` or `conda` as a package manager able to install wheels, distutils packages and conda packages.

Distribution packages need to translate the Python-specific dependencies into the names they have in that distribution, and build them without making any internet requests from the raw source (not even source wheels). This means turning off dependency resolution and installing to a temporary root directory (`$distroot`), which is then packed up with dependency metadata into a distribution package.

**Comment by yurivict** [comment]
Current python packaging process based on ```setup.py``` has been sufficient so far for all practical purposes. ```anndata``` is the first package that is different.

``conda``` is mostly python-focused and has only about 2k packages, but the  FreeBSD's package manager handles packages in many languages and has about 30k packages.

I filed a request to update it to handle setuptools-based projects.

**Comment by flying-sheep** [comment]
> Current python packaging process based on setup.py has been sufficient so far for all practical purposes. anndata is the first package that is different.

Good, they’re lucky it’s not some foundational package that breaks everything. Now they hopefully have a bit of time to fix this.

> `conda` is …

… not relevant to this discussion. It’s a whole different package manager, and as I said, OS packages scratch a different itch, so both should be supported.

> I filed a request to update it to handle setuptools-based projects.

Can I have a link please? You mean standards-based, not setuptools-based. The way it works is that the build backend is specified in pyproject.toml, and setuptools is just one possible choice of build backend. AnnData happens to use flit.

**Comment by yurivict** [comment]
> Can I have a link please?

https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=255722

**Comment by flying-sheep** [comment]
Well, Python packaging using the standard method doesn’t.

Which is consistent with modern build tools like cargo: Human-written configuration is static (defined by config files), inferring stuff about the system like autotools’ ./configure does are a part of the build system and therefore a build step that doesn’t need to be separate from other build steps.

**Comment by yurivict** [comment]
@flying-sheep I tried to build ```anndata``` with ```flit``` but it fails:
```
$ flit build
Found 0 files tracked in git                                                                                                                                                      I-flit.sdist
Traceback (most recent call last):
  File "/usr/local/bin/flit", line 11, in <module>
    load_entry_point('flit==3.2.0', 'console_scripts', 'flit')()
  File "/usr/local/lib/python3.8/site-packages/flit/__init__.py", line 154, in main
    main(args.ini_file, formats=set(args.format or []),
  File "/usr/local/lib/python3.8/site-packages/flit/build.py", line 46, in main
    sdist_file = sb.build(dist_dir, gen_setup_py=gen_setup_py)
  File "/usr/local/lib/python3.8/site-packages/flit_core/sdist.py", line 182, in build
    files_to_add = self.apply_includes_excludes(self.select_files())
  File "/usr/local/lib/python3.8/site-packages/flit_core/sdist.py", line 157, in apply_includes_excludes
    raise Exception("Crucial files were excluded from the sdist: {}"
Exception: Crucial files were excluded from the sdist: anndata/__init__.py, README.rst, pyproject.toml
```

py38-flit-3.2.0
Python-38
FreeBSD 13

**Comment by flying-sheep** [comment]
`flit` is a development tool, i.e. you use it when you want to work on the package.

You want to use an build-agnostic tool as described in https://github.com/theislab/anndata/issues/561#issuecomment-835770254
