### ISSUE TITLE
transfer adata.raw.X to adata.X

### ISSUE THREAD

**Issue by dm8000** [theislab/anndata#566]
Hello

Is there anyway to replace adata.X with adata.raw.X? I had to filter out some vars but now I need all of them again.

**Comment by gokceneraslan** [comment]
`adata.raw.to_adata()` is what you are looking for I think: https://anndata.readthedocs.io/en/refpaths/anndata.Raw.html

**Comment by dm8000** [comment]
Thanks!!

**Comment by vtrifonov-altos** [comment]
This does not work if adata is backed. I get `AttributeError: '_CSRDataset' object has no attribute 'copy'`. I would like to get only the `raw` part (which is sparse) without having to read the full and rather large full object.
