### ISSUE TITLE
Don’t set a log level on import

### ISSUE THREAD

**Issue by flying-sheep** [theislab/anndata#57]
In 4233e0773d03b12eb52b2205cd007569c836c33f we started calling `logging.basicConfig` and in 40bdcbb88653162c13b839f886a53967c66c1fd1 we changed the global log level to INFO. This means that everyone’s logging configuration is overridden (not nice) and they start seeing INFO-level noise from all modules!

Python modules should never call any code with global side effects on import. `logging.basicConfig` goes into `__main__`.

@falexwolf said that the goal was to have similar output to scanpy’s. The problem is that scanpy uses its own logging infrastructure instead of python’s. My proposal:

1. get rid of this side effect
2. get rid of scanpy’s logging infrastructure and use python’s (theislab/scanpy#256)

We can still use our own logging format and set scanpy and anndata to INFO level like this:

```py
logger = logging.getLogger(__name__)
logger.propagate = False  # Don’t pass log messages on to the root logger and its handler
logger.setLevel('INFO')

handler = logging.StreamHandler(sys.stderr)  # Why did we use stdout?
handler.setFormatter(logging.Formatter('%(message)s'))
handler.setLevel('INFO')
logger.addHandler(handler)
```

**Comment by falexwolf** [comment]
See https://github.com/theislab/scanpy/issues/256#issuecomment-418711035.

Regarding use of stdout: stderr makes all your notebooks red on the slightest warning. Looks awful.

**Comment by flying-sheep** [comment]
hahaha this is a completely unexpected reason for this decision.

well, logs belong into stderr. maybe we can autodetect if we’re in an ipython notebook [like this](https://stackoverflow.com/a/39662359/247482), and use stdout in case we are.
