### ISSUE TITLE
ModuleNotFoundError: No module named 'anndata.base'

### ISSUE THREAD

**Issue by jinrui6** [theislab/anndata#572]
Hi,

I'm a first time user and I got the error when I try to read in a pkl file. 

I haven't found an answer yet, hope someone can help here. I use python 3.7.3 and anndata 0.7.6. 

Thanks in advance.

Code:
```
import pickle
import anndata
import sys

infile=open('~/pid4191_spleen_logNorm_regMito_PCA_wt_marker_umap_cluster.pkl','rb')
dat=pickle.load(infile)
```

Error:
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-29-5893a66631c3> in <module>
      4 
      5 infile=open('/data/home/jinrui.liu/5017_il18bp/mouse/pid4191_spleen_logNorm_regMito_PCA_wt_marker_umap_cluster.pkl','rb')
----> 6 dat=pickle.load(infile)

ModuleNotFoundError: No module named 'anndata.base'

**Comment by louisjrliu** [comment]
I used two other smaller pkl files to test.

![image](https://user-images.githubusercontent.com/45375847/121417805-49e49200-c938-11eb-843c-f0ac0882778c.png)

1 went through and 1 gave the same error. I don't know if this is a missing module problem since anndata 0.7.6 was installed since the beginning. I'd really appreciate if someone can advise.

**Comment by ivirshup** [comment]
Have you written these pickle files? If so, can you show an example of writing the file then getting this error?

I would have to look into if we have done much for backwards compatibility for pickled AnnData objects, but it could be that there is an environment issue.

**Comment by louisjrliu** [comment]
Hi I did not written the pickle files. Those were generated back in 5/30/2019. I tried use different environments both on HPC and local machine. And didn't work.
I don't know if this is going be helpful, but the pickle files were written simply using the below example code:

```
data_dir_smps = [os.path.join(data_dir,x) for x in os.listdir(data_dir) if os.path.isdir(os.path.join(data_dir,x))]
adatas = loadSmpToList(data_dir_smps)
pickle_dump_file(adatas, suffix + "_raw.pkl")
```

**Comment by ivirshup** [comment]
We haven't established backward compatibility for anndata's saved as pickles, just the `h5ad` and `zarr` formats.

Can you recreate the environment that was used to write these files, and save them as `h5ad` from there?

**Comment by louisjrliu** [comment]
Hi,

Thanks for the reply. Yes I have those data saved as h5ad. Are we expecting the updates with pickles anndata capability any time soon?

**Comment by ivirshup** [comment]
It's not a priority at the moment. If we do add it, we may also limit how far back the backwards compatibility extends.

I'll open a new feature request for this so we can track this feature.
