### ISSUE TITLE
Problem caused by `within_flit()` when building own package with flit

### ISSUE THREAD

**Issue by LustigePerson** [theislab/anndata#573]
Hello,

we are using `anndata` and `scanpy` in our FASTGenomics [reader module](https://github.com/FASTGenomics/fgread-py).
We are also using flit to built this package. During build flit tries to load `scanpy`, which then loads `anndata`, which ultimately crashes because `AnnData` cannot be imported due to the [`within_flit()` function](https://github.com/theislab/anndata/blob/0ec97410702f61b29acef80b6377d1232699fa94/anndata/_metadata.py#L47) called in the [`anndata/init.py`](https://github.com/theislab/anndata/blob/0ec97410702f61b29acef80b6377d1232699fa94/anndata/__init__.py#L5).

Are you aware of any way to overcome this issue?

**Comment by ivirshup** [comment]
Ping @flying-sheep

As another point of reference, [scirpy](https://github.com/icbi-lab/scirpy) also uses flit for it's build system but is able to work with `anndata>0.7.6`. @grst, maybe you've already worked out a solution here?

**Comment by grst** [comment]
I don't think I did anything specific, except maybe that I use the `within_flit` function myself: 
https://github.com/icbi-lab/scirpy/blob/0f0b28243ee9db5e0bf1ffac24d78dbed83cb628/scirpy/__init__.py

**Comment by flying-sheep** [comment]
That hack means that during `get_docstring_and_version_via_import`, the module will be empty. How does that turn out to be a problem for you @LustigePerson?

**Comment by LustigePerson** [comment]
@flying-sheep Well as I said, during flit build all imports are executed. This includes `import scanpy`. The error then occurs when scanpy is trying to import `AnnData` from `anndata`.
But perhaps it help that you say it occurs during `get_docstring_and_version_via_import`, I will have a look if flit allows to not do this for all packages.
For now I fixed it by just using an older anndata version for build. But I could also try to use the same "hack".

**Comment by flying-sheep** [comment]
> But I could also try to use the same "hack".

You should. The only shortcoming of flit is that it doesn’t have great support for dynamic retrieval of versions:

Besides parsing a string literal, it only supports importing the base package namespace. That’s a hen-and-egg problem, since by that point the package’s dependencies are not necessarily available.

@takluyver only needs to merge one of takluyver/flit#382 and takluyver/flit#374, or implement a feature fixing takluyver/flit#257 and takluyver/flit#271 to make this limitation go away.

**Comment by LustigePerson** [comment]
Thannks, for the clarification. I'll try and close this issue!
