### ISSUE TITLE
Changing the name of var category

### ISSUE THREAD

**Issue by bapoorva** [theislab/anndata#574]
Hi,

New to python here. I have a basic question. 

```
>>>adata=ad.read_h5ad('Xinh5F_sparse3.h5ad')
>>>adata.var
             gene_name alt_gene_name
uid                                 
AL627309.1  AL627309.1    AL627309.1
AC114498.1  AC114498.1    AC114498.1
AL669831.5  AL669831.5    AL669831.5
LINC00115    LINC00115     LINC00115
FAM41C          FAM41C        FAM41C
```

How do I change the column name from 'gene_name' to 'gene_symbol' ? I looked up rename_categories in the anndata documentation and they seem to be for rows. 

Thanks

**Comment by ivirshup** [comment]
You can use the [`rename`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.rename.html) method for pandas dataframes, something like:

```python
import scanpy as sc

pbmc = sc.datasets.pbmc3k_processed()
pbmc.obs.rename(columns={"n_genes": "genes_expressed"}, inplace=True)
```

Hope that helps!
