### ISSUE TITLE
Are there tools with a GUI to inspect anndata objects?

### ISSUE THREAD

**Issue by Midnighter** [theislab/anndata#575]
Sometimes I just want to quickly look up a piece of information in an anndata file on disk. Or I get a file from a colleague and I'd like to inspect it without firing up a Python session.

For SQLite there is the excellent and powerful [SQLite Browser](https://sqlitebrowser.org/) which is sort of my reference. For HDF5 files in general there is also [ViTables](https://vitables.org/) which can also open h5ad files but it doesn't seem to support categorical data yet. Are there any viewing or inspection tools especially for anndata files?

**Comment by Koncopd** [comment]
Hi, https://github.com/chanzuckerberg/cellxgene

**Comment by Midnighter** [comment]
Thank you for the link. I should have specified that I'm using anndata not for single cell data but custom data descriptions. I find it to be a convenient data structure in many contexts. So with cellxgene I get 

```
Error: No valid layout data.
```

**Comment by Zethson** [comment]
Maybe Rich's inspection helps a little bit?

https://rich.readthedocs.io/en/stable/introduction.html#rich-inspect

Might be too simple as to that you are looking for

**Comment by Midnighter** [comment]
Thank you both for your comments. Probably such a tool doesn't exist (yet). I will close the issue to clean up the issue list but if anyone finds anything, I welcome their comment here 😉
