### ISSUE TITLE
Different files size for the same h5ad when reading in it and saving it immediately 

### ISSUE THREAD

**Issue by Bio-MingChen** [theislab/anndata#581]
Recently when I tried to run a example come from scvi tutorial which is used to do cell assignment by cellassign, the dataset it used is 80M initially ,but when I simply load it into python and write it back, its size increased to 279M. I tried to find answer from google but nothing related topic was found, I guess this is something about data structure but I just can not expain what has happend, Dataset link is https://drive.google.com/uc?id=10l6m2KKKioCZnQlRHomheappHh-jTFmx. I really want to know th reason, please give me some help. Best Wishes

**Comment by ivirshup** [comment]
Could the issue be compression? E.g. `adata.write_h5ad(pth)` vs `adata.write_h5ad(pth, compression="lzf")`

**Comment by Bio-MingChen** [comment]
That's the point! Thanks for your so quick reply and I just tried it with argument of compression.
