### ISSUE TITLE
Exporting adata.X and gene names to csv

### ISSUE THREAD

**Issue by Gabi86** [theislab/anndata#582]
Hi all,

Someone else have asked similar questions already but I've been wondering if it's possible to extract data matrix and gene names only into a csv? I've used this to export adata.X into csv (but as expected it was only data matrix without any indication which column shows which gene)

```ruby
data = adata.X
df = pd.DataFrame(data.toarray())
df.to_csv()
compression_opts = dict(method='zip',
                       archive_name='df.csv')  
df.to_csv('df.zip', index=False,
         compression=compression_opts) 
```

I was wondering whether it is possible to extract only gene names from adata.var with adata.X (without the rest of the metadata as it's not important).

Thank you!

**Comment by ivirshup** [comment]
If you'd like to write everything (including values in `obsm`, `obs`, etc.) to CSVs you can use [`adata.write_csvs`](https://anndata.readthedocs.io/en/latest/anndata.AnnData.write_csvs.html#anndata.AnnData.write_csvs). If you just want `X` with labels, I would use the `to_df()` method to get a dataframe of `X` with `obs_names` and `var_names` as the `index` and `columns`. E.g.:

```python
adata.to_df().to_csv(...)
```
