### ISSUE TITLE
anndata noarch for mac M1 

### ISSUE THREAD

**Issue by vivekbhr** [theislab/anndata#592]
Hello anndata team

Could you update the anndata noarch version to >0.7.6 on conda-forge so that it's possible to install anndata (and scanpy) on the new M1 macbook? The current noarch version (anndata-0.6.22) is not supported by the scanpy (1.7.2) on conda-forge.

Thanks in advance,
Vivek

**Comment by ivirshup** [comment]
I believe this should be done now
