### ISSUE TITLE
Loading precomputed tSNE from loom file not working

### ISSUE THREAD

**Issue by AAA-3** [theislab/anndata#608]
I was wondering if you could help me here since my issue is a continuation of the above. I managed to import my seurat clusters using the same methods as above.

However, when I try to load my saved loom file, I get an error each time I set the `obsm_mapping` parametre:

`adata = scv.read_loom("/home/ali/Dokumente/RPractise/Velocity/PythonCodes/adata.loom", obs_names="CellID", var_names="Gene", obsm_mapping="X_tsne")`
![image](https://user-images.githubusercontent.com/68068335/130209166-3b1126fd-529a-4026-a36a-1b3f3f149562.png)

Without setting the `obsm_mapping` parametre, the file loads normally and one can even see the tsne coordinates:
![image](https://user-images.githubusercontent.com/68068335/130209483-da0b29dc-82d9-4d16-ac4e-34250417f568.png)

Seeing as the information is available in the loom file, I assume that it is in an incorrect format...would it have something to do with it being an array? I notice that there is no `["tsne_1", "tsne_2"]`  headers, as listed in the [scvelo.read_loom API page](https://scvelo.readthedocs.io/scvelo.read_loom/)

**Comment by ivirshup** [comment]
Your code is erroring since you are passing a string as an argument which requires a mapping (like a `dict`). Why do you want to pass the extra argument if you're getting the result you want without it?

**Comment by AAA-3** [comment]
I'm quite new to Python so I may be wrong in understanding this:


I thought that if I do not have the obsm mapping, the file will not be read correctly by scvelo but looks like thats not the case

**Comment by ivirshup** [comment]
By default, any one dimensional arrays aligned to the obs axis will go in `obs`, while multidimensional arrays will go in `obsm`. The `obsm_mapping` argument lets you select multiple one dimensional arrays which can each be a column in a multidimensional array in `obsm`.

I do think this could be better documented.
