### ISSUE TITLE
copy.deepcopy(adata.X) produces copy of adata.raw.X

### ISSUE THREAD

**Issue by YitengDang** [theislab/anndata#616]
When I run copy.deepcopy(adata.X) on an AnnData file, this produces adata.raw.X as output if adata.raw is present. How do I instead create a copy of adata.X?
This is not the first time I encountered this problem, so I thought it might be something systematic.

EDIT: sorry, this might have something to do with the scrublet package specifically. The part I am running is 
`import scrublet as scr`
`scrub_data = copy.deepcopy(adata.X);`
`scrub = scr.Scrublet(scrub_data) # NB use unnormalized raw data`
`adata.obs['doublet_scores'], adata.obs['predicted_doublets'] = scrub.scrub_doublets()`
`scrub.plot_histogram()`
`sum(adata.obs['predicted_doublets'])`

Somehow this keeps producing this error, with `scrub_data` taking the dimensions of adata.raw.X, but after some trial and error somehow this was resolved (but I don't remember how).

**Comment by Koncopd** [comment]
You can copy with `adata.X.copy()`?
