### ISSUE TITLE
Error loading loomxpy formatted files from Fly Cell Atlas

### ISSUE THREAD

**Issue by dkobak** [theislab/anndata#627]
I am trying to load .loom files from https://flycellatlas.org and am getting an odd error. For example:
```
fly_ann = sc.read_loom('s_fca_biohub_antenna_10x.loom')
```
gives me
```
s_fca_biohub_antenna_10x.loom does not appead to be a valid Loom file according to Loom spec version '3.0.0'
```
error, even though it can be opened in R just fine. Link to the file: https://cloud.flycellatlas.org/index.php/s/PcHBoL23CmxGNsb.

I have a fresh conda environment, scanpy 1.8.1, loompy 3.0.6.

**Comment by ivirshup** [comment]
Moved this to `anndata` since that's where the function lives.

I would agree that this would have to be a widespread variant to justify making changes to accommodate it.
