### ISSUE TITLE
Concatenate and layers

### ISSUE THREAD

**Issue by Marius1311** [theislab/anndata#63]
The concatenate function does not take care of layers of an anndata object yet.

**Comment by falexwolf** [comment]
Yes, you currently need to work around by concatenating manually. 
```
unspliceds = [ad.layers['unspliced'] for ad in adatas]
unspliced  = unspliceds[0]
for m in unspliceds[1:]:
    unspliced = sp.sparse.vstack([unspliced, m])

adata = adatas[0].concatenate(
    adatas[1:], batch_key='timepoints', batch_categories=timepoints)

adata.layers['spliced'] = adata.X
adata.layers['unspliced'] = unspliced
```

@Koncopd We need to be careful not to mess up the concatenate function, it's already way too long. Can you check whether you can essentially a one-line edit to bring in the functionality, write a test for it and make PR?
```
X_type = ['X', 'key1', 'key2', ...]
Xs = [adata.X if X_type == 'X' else adata.layers[key] for for adata in adatas]
```

Mid-term, we want to split all of this so that it also works in backed mode.

**Comment by Koncopd** [comment]
@falexwolf 
I'll look.

**Comment by ijayden-lung** [comment]
> Yes, you currently need to work around by concatenating manually.
> 
> ```
> unspliceds = [ad.layers['unspliced'] for ad in adatas]
> unspliced  = unspliceds[0]
> for m in unspliceds[1:]:
>     unspliced = sp.sparse.vstack([unspliced, m])
> 
> adata = adatas[0].concatenate(
>     adatas[1:], batch_key='timepoints', batch_categories=timepoints)
> 
> adata.layers['spliced'] = adata.X
> adata.layers['unspliced'] = unspliced
> ```
> 
> @Koncopd We need to be careful not to mess up the concatenate function, it's already way too long. Can you check whether you can essentially a one-line edit to bring in the functionality, write a test for it and make PR?
> 
> ```
> X_type = ['X', 'key1', 'key2', ...]
> for key in X_type:
>      Xs = [adata.X if key == 'X' else adata.layers[key] for adata in adatas]
> ```
> 
> Mid-term, we want to split all of this so that it also works in backed mode.

---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-75-eb3640cb5ec2> in <module>()
      3 unspliced  = unspliceds[0]
      4 for m in unspliceds[1:]:
----> 5     unspliced = sp.sparse.vstack([unspliced, m])
      6 
      7 adata = adatas[0].concatenate(

NameError: name 'sp' is not defined

**Comment by LuckyMD** [comment]
you need to add the line:
```import scipy as sp```

**Comment by ijayden-lung** [comment]
> you need to add the line:
> `import scipy as sp`

---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-81-eb3640cb5ec2> in <module>()
      6 
      7 adata = adatas[0].concatenate(
----> 8     adatas[1:], batch_key='timepoints', batch_categories=timepoints)
      9 
     10 adata.layers['spliced'] = adata.X

NameError: name 'timepoints' is not defined

**Comment by LuckyMD** [comment]
And replace the `timepoints` covariate with your batch covariate over which you want to concatenate.

Maybe take a look at the help page for `AnnData.concatenate()` here:
https://anndata.readthedocs.io/en/latest/anndata.AnnData.concatenate.html#anndata.AnnData.concatenate

**Comment by fidelram** [comment]
@ijayden-lung as a workaround you can use loom:

```PYTHON
import loom
loompy.combine(["file1.loom", "file2.loom"], "combined.loom")
```

You can write and read loom files with scanpy

**Comment by VolkerBergen** [comment]
@Koncopd Just a brief reminder, whether this can be fixed. Thanks.

**Comment by Koncopd** [comment]
Hi, yes, i'll try to get to this after finishing my current work.

**Comment by falexwolf** [comment]
@VolkerBergen, maybe it's faster if you give it a shot? @Koncopd is still involved in some highly urgent things where no real workaround exists... One could also build a simple version that assumes that the variables are shared (essentially pasting the code from https://github.com/theislab/anndata/issues/63#issuecomment-424702356) and outputs an error otherwise. Meanwhile, you have the most experience working with `.layers` and you'll probably do it best. :wink:

**Comment by falexwolf** [comment]
Great! I didn't think it would be a one-liner, did I state it somewhere? :wink:

With *variables being shared* I meant that the variables indices are identical among all passed objects (the elements and their order match exactly); which should be the case if you read in loom files; I think. In that case, a lot of the code becomes superfluous and a much faster implementation is possible. That simple case should end up in a helper function and not in the too-long code for `.concatenate`. No need to do that; I might go for it at some point...
