### ISSUE TITLE
networkx support

### ISSUE THREAD

**Issue by huidongchen** [theislab/anndata#64]
Hi guys,

Is there any way to store networkx object in anndata? 

I tried to store it in adata.uns['networkx'] and saved it as a  .h5ad-formatted file adata.write(results_file).

But when I read back in the object, the networkx object can't be restored. It's transformed into an array. I wonder what should be the right way to deal with networkx or other graph object in anndata. 

Any suggestions would be much appreciated. Thanks!

**Comment by huidongchen** [comment]
This could be a good comprise for the purpose of saving graph structure. But if I have different attributes added to nodes and edges, I'm afraid converting it to one adjacency matrix won't help keep these these attributes. (unless multiple adjacency matrices for edge attribute are used and nodes attributes are saved separately)

**Comment by falexwolf** [comment]
No, this is not supported. AnnData is only allows basic types (scipy sparse matrices, numpy arrays, dictionary) to be stored. One would have to come up with an hdf5 storage of the networkx object, if there is an easy way to do it, we can think about it.
