### ISSUE TITLE
Writing and reading h5ad with lists in .uns casts to incorrect types

### ISSUE THREAD

**Issue by stanleyjs** [theislab/anndata#643]
Hi,

I am attempting to write an h5ad file with lists of objects stored in the keys of `adata.uns`. A synopsis of the bug is that writing and re-reading an h5ad casts all lists and their elements to the closest numpy type; in the case of a dictionary, we end up with a list of strings.
For example,
```
> import anndata as ad
> x = ad.AnnData()

> x.uns['listofdicts'] = [{'foo':'bar'},{'foo2':'bar2'}]
> x.uns['listofints'] = [0,1,2,3]
> x.uns['listoflists'] = [[]*4]

```
In this example, `x.uns['listofdicts']` holds a list of dictionaries, `x.uns['listofints']` holds a list of integers., `x.uns['listoflists']` holds a list of lists.

We can verify this:

```
> print(all(isinstance(ele,dict) for ele in x.uns['listofdicts']))
True
> print(all(isinstance(ele,int) for ele in x.uns['listofints']))
True
> print(all(isinstance(ele,list) for ele in x.uns['listoflists']))
True
```

If we now write `x` to an `h5ad` file and then reload the file into the `anndata` `y`,

```
> x.write('foobar.h5ad')
> y = ad.read_h5ad('foobar.h5ad')
```

and perform the same checks, we've now lost our inner types:
```
> print(all(isinstance(ele,dict) for ele in y.uns['listofdicts']))
False
> print(all(isinstance(ele,int) for ele in y.uns['listofints']))
False
> print(all(isinstance(ele,list) for ele in y.uns['listoflists']))
False
```
It appears that all of our lists have been cast as `np.ndarray`:

```
> print(type(y.uns['listofints']))
<class 'numpy.ndarray'>
> print(type(y.uns['listofdicts']))
<class 'numpy.ndarray'>
> print(type(y.uns['listoflists']))
<class 'numpy.ndarray'>
```

The inner types have been cast to their closest numpy equivalent. For the `listofints` and `listoflists` this isn't so much a problem, as they become `np.int64` and `np.ndarray`, respectively, which is close enough.  **However, we lose our list of dicts: it becomes an array of strings:**

```
> print(type(y.uns['listofints'][0]))
<class 'numpy.int64'>
> print(type(y.uns['listoflists'][0]))
<class 'numpy.ndarray'>
> print(type(y.uns['listofdicts'][0]))
<class 'str'>
````

**Comment by ivirshup** [comment]
A similar issue has been raised previously in #493.

Are you using `h5py<3`? I would actually expect the list of dicts to error with h5py 3.

**Comment by ivirshup** [comment]
Closing as duplicate
