### ISSUE TITLE
subsetting anndata based on the barcodes

### ISSUE THREAD

**Issue by mostafa-ti** [theislab/anndata#648]
Is it possible to subset the anndata based on the barcodes? I have a list of barcodes for different regions, and I'm wondering if there is a method to subset my anndata by the list of the barcodes.

**Comment by LuckyMD** [comment]
If you have a list of barcodes, the following should work:
`adata_sub = adata[adata.obs_names.isin(myListOfBarcodes)]`

**Comment by mostafa-ti** [comment]
> If you have a list of barcodes, the following should work:
> `adata_sub = adata[adata.obs_names.isin(myListOfBarcodes)]`
![Screenshot 2021-11-15 at 13 40 07](https://user-images.githubusercontent.com/62187054/141783736-eeae5606-9986-4dcd-bbfd-addebcad0827.png)
I have the list of the barcodes in my andata.obs but I don't know how to reach them. It seems the barcodes are located in the [0] index of the data but the following code:` adata.obs.columns[0]` returns 'n_genes_by_counts' as the first index not the barcodes.

**Comment by ivirshup** [comment]
> I have the list of the barcodes in my andata.obs but I don't know how to reach them. It seems the barcodes are located in the [0] index of the data but the following code

They are set as the `index` of the dataframe. They will be accessible via `adata.obs_names` or `adata.obs.index`.

**Comment by mostafa-ti** [comment]
> > I have the list of the barcodes in my andata.obs but I don't know how to reach them. It seems the barcodes are located in the [0] index of the data but the following code
> 
> They are set as the `index` of the dataframe. They will be accessible via `adata.obs_names` or `adata.obs.index`.

thanks, but when I subset my adata with `adata_sub = adata[adata.obs_names.isin(SVZ3_barcodes)]` it removes all the SVZ3_barcodes and adata_subset actually didn't filter based on the list of my barcodes
![Screenshot 2021-11-15 at 14 08 26](https://user-images.githubusercontent.com/62187054/141787249-56ebf496-2c76-43ce-8809-e0d5b17eb270.png)
.

**Comment by mostafa-ti** [comment]
> It sounds like the barcodes might not be matching up. Could you show those?

I have a tsv file for each subset of the anndata and I made a list of tsv file with the following code:
```
with open('SVZ3.tsv') as tsv_file:
    while (line := tsv_file.readlines()):
        SVZ3_barcodes = list (line)
        #print(SVZ3_barcodes)
I attached the photo of the output list of my barcodes.
``
![Screenshot 2021-11-15 at 14 28 06](https://user-images.githubusercontent.com/62187054/141790101-143b4318-d2f9-4dbd-9b04-f35f3fbe8234.png)
`

**Comment by mostafa-ti** [comment]
> It sounds like the barcodes might not be matching up. Could you show those?

I have a tsv file for each subset of the anndata and I made a list of tsv file with the following code:
```
with open('SVZ3.tsv') as tsv_file:
    while (line := tsv_file.readlines()):
        SVZ3_barcodes = list (line)
        #print(SVZ3_barcodes)
```
![Screenshot 2021-11-15 at 14 28 06](https://user-images.githubusercontent.com/62187054/141790262-dd2104f3-9639-438e-bc52-f7e58d7903ba.png)
e:

**Comment by ivirshup** [comment]
I think you'll need to strip out the newline character at the end of each of those barcodes. E.g.:

```python
with open('SVZ3.tsv') as tsv_file:
    SVZ3_barcodes = [l.strip() for l in tsv_file.readlines()]
```

**Comment by mostafa-ti** [comment]
> I think you'll need to strip out the newline character at the end of each of those barcodes. E.g.:
> 
> ```python
> with open('SVZ3.tsv') as tsv_file:
>     SVZ3_barcodes = [l.strip() for l in tsv_file.readlines()]
> ```

yes, you're right but after removing the new lines, I still got 0 value for the n_vars
![Screenshot 2021-11-15 at 14 50 35](https://user-images.githubusercontent.com/62187054/141793427-c7bb15ad-c7dc-4a03-84d1-1d001a2124de.png)
rs

**Comment by ivirshup** [comment]
Is it possible that the barcodes in your file don't exist in the `AnnData`?

Btw, if you are expecting the barcodes to be the `obs_names` you can also do: `adata[barcodes]`. E.g.:

```python
In [1]: import scanpy as sc, numpy as np
   ...: 
   ...: pbmc = sc.datasets.pbmc3k_processed()
   ...: barcodes = np.random.choice(pbmc.obs_names, 10)

In [2]: barcodes
Out[2]: 
array(['ACTAGGTGGAACTC-1', 'CAAGAAGATTCTAC-1', 'GATGCCCTTTTGCT-1',
       'TAGATTGACTTGTT-1', 'GTGATTCTCATTTC-1', 'TTATTCCTGGACAG-1',
       'TAATGTGATTACTC-1', 'ATGCGATGCTGAGT-1', 'CATCAACTCCCTCA-1',
       'CGTGTAGAGTTCAG-1'], dtype=object)

In [3]: pbmc[barcodes].obs
Out[3]: 
                  n_genes  percent_mito  n_counts          louvain
index                                                             
ACTAGGTGGAACTC-1     1046      0.017007    3528.0      CD4 T cells
CAAGAAGATTCTAC-1      864      0.012866    2798.0      CD4 T cells
GATGCCCTTTTGCT-1      587      0.036137    1522.0      CD4 T cells
TAGATTGACTTGTT-1      622      0.034548    1592.0          B cells
GTGATTCTCATTTC-1      943      0.009349    2567.0      CD4 T cells
TTATTCCTGGACAG-1      788      0.013132    2513.0          B cells
TAATGTGATTACTC-1      839      0.028387    2325.0      CD8 T cells
ATGCGATGCTGAGT-1      850      0.015360    2539.0      CD4 T cells
CATCAACTCCCTCA-1      994      0.007353    3672.0      CD4 T cells
CGTGTAGAGTTCAG-1      720      0.017470    1889.0  CD14+ Monocytes
```

**Comment by mostafa-ti** [comment]
> Is it possible that the barcodes in your file don't exist in the `AnnData`?
> 
> Btw, if you are expecting the barcodes to be the `obs_names` you can also do: `adata[barcodes]`. E.g.:
> 
> ```python
> In [1]: import scanpy as sc, numpy as np
>    ...: 
>    ...: pbmc = sc.datasets.pbmc3k_processed()
>    ...: barcodes = np.random.choice(pbmc.obs_names, 10)
> 
> In [2]: barcodes
> Out[2]: 
> array(['ACTAGGTGGAACTC-1', 'CAAGAAGATTCTAC-1', 'GATGCCCTTTTGCT-1',
>        'TAGATTGACTTGTT-1', 'GTGATTCTCATTTC-1', 'TTATTCCTGGACAG-1',
>        'TAATGTGATTACTC-1', 'ATGCGATGCTGAGT-1', 'CATCAACTCCCTCA-1',
>        'CGTGTAGAGTTCAG-1'], dtype=object)
> 
> In [3]: pbmc[barcodes].obs
> Out[3]: 
>                   n_genes  percent_mito  n_counts          louvain
> index                                                             
> ACTAGGTGGAACTC-1     1046      0.017007    3528.0      CD4 T cells
> CAAGAAGATTCTAC-1      864      0.012866    2798.0      CD4 T cells
> GATGCCCTTTTGCT-1      587      0.036137    1522.0      CD4 T cells
> TAGATTGACTTGTT-1      622      0.034548    1592.0          B cells
> GTGATTCTCATTTC-1      943      0.009349    2567.0      CD4 T cells
> TTATTCCTGGACAG-1      788      0.013132    2513.0          B cells
> TAATGTGATTACTC-1      839      0.028387    2325.0      CD8 T cells
> ATGCGATGCTGAGT-1      850      0.015360    2539.0      CD4 T cells
> CATCAACTCCCTCA-1      994      0.007353    3672.0      CD4 T cells
> CGTGTAGAGTTCAG-1      720      0.017470    1889.0  CD14+ Monocytes
> ```

The `Anndata` generated based on the `10x_mtx` from the `filtered_feature_bc_matrix` folder . as I used same barcodes to create  10X matrices I assume that the barcodes should be exist in the AnnData.
Btw `np.random.choice(pbmc.obs_names, 10)` return random barcodes and seems does not solve my issue. I want to have subset of my `AnnData` based on the list of the selected barcodes.

**Comment by ivirshup** [comment]
> Btw np.random.choice(pbmc.obs_names, 10) return random barcodes and seems does not solve my issue.

Yes. This was meant to demonstrate that if you have barcodes which are in `obs_names` you can use them to index into the AnnData object.

> as I used same barcodes to create 10X matrices I assume that the barcodes should be exist in the AnnData.

This may be the issue, if I'm understanding you here. Could you elaborate?

The barcodes in `obs_names` are bead level. Are the barcodes you're referring to sample level?

**Comment by mostafa-ti** [comment]
> > Btw np.random.choice(pbmc.obs_names, 10) return random barcodes and seems does not solve my issue.
> 
> Yes. This was meant to demonstrate that if you have barcodes which are in `obs_names` you can use them to index into the AnnData object.
> 
> > as I used same barcodes to create 10X matrices I assume that the barcodes should be exist in the AnnData.
> 
> This may be the issue, if I'm understanding you here. Could you elaborate?
> 
> The barcodes in `obs_names` are bead level. Are the barcodes you're referring to sample level?

Maybe I don't get what you mean or I'm totally wrong with the bead level and sample level barcodes.
I assume all the barcodes in the AnnData are associated with the cells (barcoded cDNA). My idea is to cluster the cells that come from  different regions based on the barcodes.

**Comment by akhst7** [comment]
@mostafa-ti ,  I am having an the same issue.  If you have figured this out, I'd appreciate if you could let me know, 

Thanks.
