### ISSUE TITLE
Unable to create AnnData from input pandas DataFrame

### ISSUE THREAD

**Issue by fbrundu** [theislab/anndata#67]
When trying to create an AnnData from a pandas DataFrame I get the following error:

```python
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-18-235904346c66> in <module>()
----> 1 adata_prova = sc.AnnData(adata_to_df(adata=adata_p))

~/.pyenv/versions/3.6.4/lib/python3.6/site-packages/anndata/base.py in __init__(self, X, obs, var, uns, obsm, varm, layers, raw, dtype, shape, filename, filemode, asview, oidx, vidx)
    681                 layers=layers,
    682                 dtype=dtype, shape=shape,
--> 683                 filename=filename, filemode=filemode)
    684 
    685     def _init_as_view(self, adata_ref: 'AnnData', oidx: Index, vidx: Index):

~/.pyenv/versions/3.6.4/lib/python3.6/site-packages/anndata/base.py in _init_as_actual(self, X, obs, var, uns, obsm, varm, raw, layers, dtype, shape, filename, filemode)
    824                 class_names = ', '.join(c.__name__ for c in StorageType.classes())
    825                 raise ValueError('`X` needs to be of one of {}, not {}.'
--> 826                                  .format(class_names, type(X)))
    827             if shape is not None:
    828                 raise ValueError('`shape` needs to be `None` is `X` is not `None`.')

ValueError: `X` needs to be of one of ndarray, MaskedArray, spmatrix, ZarrArray, not <class 'pandas.core.frame.DataFrame'>.
```

The line in the current version is:

https://github.com/theislab/anndata/blob/4c40622b7b5889f2893162d7c067256a5df5132e/anndata/base.py#L821

I am using the latest (from git) version of scanpy (1.3.1+68.ga045533) and the latest published version of AnnData (0.6.10).

I am creating an AnnData using:

```python
adata = sc.AnnData(df)
```

**Comment by falexwolf** [comment]
It's not in an release yet, only on GitHub, I'll release a new anndata version this weekend, then it's out there. I'll also change the docs to show the releases only in the future, now that things converge a little.

**Comment by fbrundu** [comment]
Perfect, thanks. Can I ask you if the reverse function will be available? I.e. from AnnData to pandas DataFrame (adata.X + var_names and obs_names). I wrote some helper functions for that but I'd like to know if it's implemented directly into AnnData.

Thanks anyway.

**Comment by falexwolf** [comment]
Initialization from DataFrames is now in v0.6.11.

Yes, we can think about a `.to_df` soon. If you want to make a pull request, that's welcome, too.

**Comment by fbrundu** [comment]
Thanks.
I put a draft in https://github.com/theislab/anndata/pull/68 
Let me know your comments.
