### ISSUE TITLE
ModuleNotFoundError: No module named 'anndata.experimental'

### ISSUE THREAD

**Issue by xiangwei6963** [theislab/anndata#686]
Hi there,
     I am running into this error when I am trying to run "from anndata.experimental.multi_files import AnnCollection"!
     error: ModuleNotFoundError: No module named 'anndata.experimental'
      Thank you so much for your help!

**Comment by Koncopd** [comment]
Hi, what version of anndata do you use?

**Comment by xiangwei6963** [comment]
my anndata is 0.7.6

**Comment by Koncopd** [comment]
These things are available from 0.7.7.

**Comment by xiangwei6963** [comment]
Thank you so much!
