### ISSUE TITLE
Anndata slice with pandas error

### ISSUE THREAD

**Issue by xiangwei6963** [theislab/anndata#687]
Hi authors,
    I'm trying to use  pandas  operators to slice my data as follows:
     adata1=adata[adata.obs.iloc[0:2]]
    But returns "IndexError: Unknown indexer"
    Thank you!

**Comment by ivirshup** [comment]
You're passing a dataframe as an indexer. 

What would work is either the indices of obs that you'd like to subset

```python
adata1 = adata[adata.obs.iloc[0:2].index]
```

or just passing the positional indices directly:

```python
adata1 = adata[0:2]
```
