### ISSUE TITLE
uns field is replicated for all observation which makes it annotation of observation.

### ISSUE THREAD

**Issue by marouf-git** [theislab/anndata#69]
when uns field is used to save some dictionary which has too many keys/values, the file size will increase massively.   Expectedly, the reading and writing operation will  be slow.

**Comment by falexwolf** [comment]
what do you mean specifically and what do you suggest? can you give an example?

**Comment by marouf-git** [comment]
So, if I make a new anndata object using:
adata = sc.AnnData(X=adata_training.X, obs = adata_training.obs, uns = adata_training.uns)
The uns field is supposed to be one unstructured annotation for all observations. However, we can still use adata[0].uns , adata[1].uns ....etc. This would be fine if this uns a small dictionary because replicating it to all observations will not significantly increase the size and query time of the andata. 
However, once we have more meta data or information added to the uns field, the size of the file as well as query/read/write time increases massively.

**Comment by falexwolf** [comment]
Usually you wouldn't split up your AnnData's into many tiny objects. Also, usually, `.uns` doesn't contain a lot of data, just some very light-weight annotations.

**Comment by marouf-git** [comment]
Hi @falexwolf .
> Usually you wouldn't split up your AnnData's into many tiny objects. 
Well, sometimes you just need to run and process the observations one by one.

> Also, usually, .uns doesn't contain a lot of data, just some very light-weight annotations.
That was not my use case.

Anyway thanks for the great package and for your clarification :)
