### ISSUE TITLE
How to properly read csv file

### ISSUE THREAD

**Issue by ivanpanshin** [theislab/anndata#714]
I'm having one of the most basic issues with anndata: how to read data. 

My pandas dataframe is of the following format: rows x columns, where rows = names of samples, columns = names of features. No matter how I read the data (for example, `data = anndata.read_csv(path)` or `data = sc.AnnData(df)`) my `data.obs` is a DataFrame with some rows, but zero columns. 

Hence, `data.obs_keys()` returns an empty list instead of actual values in obs. Hence, scanpy methods that I'm trying to use (for example, `scanpy.pp.combat`) fail.

So, the question is simple - how to properly transfer my pandas dataframe into anndata so that `data.obs_keys()` is not empty, and scanpy methods work?

**Comment by ivirshup** [comment]
Thanks for checking out our libraries.

`data = sc.AnnData(df)` will end up with an AnnData where:

```python
np.array_equal(data.X, df.values)
np.array_equal(data.obs_names, df.index)
np.array_equal(data.var_names, df.columns)
```

I think [this brief introduction to anndata](https://adamgayoso.com/posts/ten_min_to_adata/) may be helpful here.

For a method like `sc.pp.combat` you will need to have a column in `obs` which corresponds to batch information. Are you expecting this to be somewhere in your passed dataframe?

**Comment by ivanpanshin** [comment]
Well, let's say I define `batch` as follows. Would you say that's the correct option? 

This is a dummy example, so dataframe values, as well as batch values, are random. 

<img width="994" alt="Screenshot 2022-03-02 at 18 37 35" src="https://user-images.githubusercontent.com/48650449/156372183-f4382fd6-af52-447e-a92c-5c417a2b092f.png">
