### ISSUE TITLE
installing in dev mode via pip fails

### ISSUE THREAD

**Issue by giovp** [theislab/anndata#717]
with `pip install -e .` gets this error:
```
ERROR: File "setup.py" not found. Directory cannot be installed in editable mode: /Users/giovanni.palla/Projects/anndata
(A "pyproject.toml" file was found, but editable mode currently requires a setup.py based build.)
```

**Comment by giovp** [comment]
with `flit install -s --deps=develop` it works, shall I update readme?

**Comment by Koncopd** [comment]
Yes, it works with flit. Do we really have anything related to dev install with pip in anndata docs or readme? I can't find.

**Comment by giovp** [comment]
couldn't find it either, fine in main page or better to have an installation page?

**Comment by ivirshup** [comment]
@giovp, what version of pip are you using?

`pip install -e` should work with `pip>21.3`

**Comment by ivirshup** [comment]
For contributing docs, this should basically be the same as scanpy, except without the scanpy specific paths. Not sure what the best way to convey this info in the docs is

**Comment by ivirshup** [comment]
@giovp, was the issue the version of `pip`?

**Comment by ivirshup** [comment]
I'll open another issue with a more specific name
