### ISSUE TITLE
Unable to write categorical booleans in .obs to .h5ad

### ISSUE THREAD

**Issue by Imipenem** [theislab/anndata#724]
While working on ehrapy, we had to deal with mixed data (non-numerical/numerical dtypes). Some of those were stored on `.obs` with pandas `dtype=category`.
However, when trying to write them to a `.h5ad` file it fails to do so because it was unable to write the actual categories (e.g. `True` and `False`), but not the column itself.

**Minimal Example:**

```
from anndata import AnnData
import numpy as np
import pandas as pd

if __name__ == "__main__" :
    obs = pd.DataFrame({"ObsCol1":[1,2,3], "ObsCol2":[True,False,False]}, dtype="category")
    var = pd.DataFrame(index=["Col1", "Col2"])
    X = np.zeros([3,2])
    adata = AnnData(X=X, var=var, obs=obs)
    adata.write("testfile.h5ad")
```

**results in:**

```
TypeError: Can't implicitly convert non-string objects to strings

Above error raised while writing key '__categories/ObsCol2' of <class 'h5py._hl.group.Group'>
from /.

Above error raised while writing key 'ObsCol2' of <class 'h5py._hl.group.Group'> from /.

Above error raised while writing key 'obs' of <class 'h5py._hl.files.File'> from /.
```

**Comment by ivirshup** [comment]
This one is a little weird. I think there's an upstream issue, but also that the column should just be boolean.

## Why it's upstream

```python
In [1]: import pandas as pd
   ...: 
   ...: obs = pd.DataFrame({"int_cat":[1,2,3], "bool_cat":[True,False,False]}, dtype="category")
   ...: obs["bool_cat"].cat.categories.dtype
Out[1]: dtype('O')
```

This is weird. Shouldn't the type of the categories be `bool`? And yet:

```python
In [2]: bools = pd.Series([True, False, True])
   ...: bools.dtype
Out[2]: dtype('bool')

In [3]: bools.astype("category").cat.categories.dtype
Out[3]: dtype('O')
```

## But also, why even make a categorical where the categories are boolean?

I'm not aware of a case where it makes sense to encode a boolean as a categorical. There are already only two values. We also support nullable booleans as of 0.8.

From discussion offline it sounds like @Imipenem can just use booleans here.

**Comment by ivirshup** [comment]
Closing as this is being solved upstream
