### ISSUE TITLE
anndata - deleting specific row

### ISSUE THREAD

**Issue by ltosti** [theislab/anndata#73]
Hi there,

Sorry for the simple question, but I just started using anndata within Scanpy and was wondering: is there a way to remove a specific row? Something like  
```
if 
adata.var_names == "foo"
remove the row
 ```
 (It is to remove some mitochondrial genes)

Thank you!

**Comment by falexwolf** [comment]
Checkout the [basic tutorial](https://nbviewer.jupyter.org/github/theislab/scanpy_usage/blob/master/170505_seurat/seurat.ipynb).

What you want specifically is
```
non_mito_genes_list = [name for name in adata.var_names if not name.startswith('MT-')]
adata_no_mito_genes = adata[:, non_mito_genes_list]
```

Or you can also do
```
mito_gene_list = sc.queries.mitochondrial_genes()
mito_gene_indicator = np.in1d(adata.var_names, mito_gene_list)
adata_no_mito_genes = adata[:, ~mito_gene_indicator]
```
where `~` inverts the boolean indicator array, making it a mask.

Depending on the scenario, one or the other will be more convenient.

PS: AnnData stores observations as rows and variables as columns as common in machine learning,  statistics and Python, but opposite to the genomics convention.

**Comment by JPV95** [comment]
I ran the above solution, only to get memory error, I am running 64 bit python, is there a way to delete a row based on observation value?

essentially
if anndata['value'] == "threshold"
      delete()

**Comment by falexwolf** [comment]
No, sorry, there is no way to delete a row as storage is in contiguous arrays.

**Comment by falexwolf** [comment]
How come you are getting a memory error from the above? Are you dealing with a huge matrix on a machine with very little memory?

**Comment by wubaosheng** [comment]
> No, sorry, there is no way to delete a row as storage is in contiguous arrays.

you can do like this:
 t = adata.obs.drop(index=["C_DeepM_r_2_FRAS210239463_1r"])
adata= adata[adata.obs["sample_index"].isin(t["sample_index"].to_list())]
