### ISSUE TITLE
'dtype' within reading functions doesn't work

### ISSUE THREAD

**Issue by huidongchen** [theislab/anndata#75]
Hi, 

I'm trying to read in a matrix file in the format of  '**float64**'. I did the following:

`adata = ad.read_text('./test.txt',delimiter='\t',dtype='float64')
` 

I have specified the dtype as 'float64' but still `adata.X` is showing the default '**float32**'. Is it a bug or did I miss anything?

I'm attaching a short script here to reproduce this issue. I will really appreciate your help.  Many thanks!
[Archive.zip](https://github.com/theislab/anndata/files/2516811/Archive.zip)

**Comment by huidongchen** [comment]
update: 

The 'dtype' is missing in `_read_text()`

```
    return AnnData(data,
                   obs={'obs_names': row_names},
                   var={'var_names': col_names})
```

Similarly, in `transpose()` and `copy()`,etc, it's missing too

**Comment by huidongchen** [comment]
Sure. I will do that.  

But I noticed for the function transpose() , if I don’t add dtype = float64, after read_text() and transpose, it will be reverted to float32 again . I guess there must be something else that needs to be fixed.

**Comment by falexwolf** [comment]
Sorry for being so slow, @huidongchen , it's been fixed for copy (https://github.com/theislab/anndata/commit/989f13e6ff120306e40e6dc05bff89a6a0402cbc) and for transpose (https://github.com/theislab/anndata/commit/b7dca41c3b816a3cbd1793781ebab60de4b63ff0).

The PR for the read functions will only affect the read functions themselves. Should be very straight forward. Thank you!

**Comment by huidongchen** [comment]
Hi Alex @falexwolf  thanks a lot for updating other relevant parts. I will make a PR shortly.

**Comment by falexwolf** [comment]
Fixed via https://github.com/theislab/anndata/pull/81.
