### ISSUE TITLE
numpy/scipy version dependencies

### ISSUE THREAD

**Issue by Hoeze** [theislab/anndata#76]
Hi, would it be possible to change the numpy/scipy dependencies to numy >= 1.14 and scipy >= 1.0?
anndata otherwise causes problems with other packages requiring newer versions of numpy/scipy.

**Comment by falexwolf** [comment]
Yes, I guess that won't harm anyone. PR welcome!

**Comment by flying-sheep** [comment]
Hi, what problems are you talking about? we just fixed a problem regarding this syntax in #80.

I’m confident that we understand everything now, so #83 won’t be needed, and will actually cause problems once numpy 2.0 or scipy 2.0 are released.

**Comment by Hoeze** [comment]
Ah sorry I did not see that change ^^

I usually just use '>=' to keep pip from downgrading packages :)
