### ISSUE TITLE
adata.write not working when calling from R

### ISSUE THREAD

**Issue by aopisco** [theislab/anndata#87]
hey! I'm trying to write a Seurat object to anndata but it fails in the write part

`adata <- Convert(sc, to = "anndata")`
works no problem

`adata <- Convert(sc, to = "anndata",filename = "~/Lung_facs_seurat.h5ad")`
`Error in py_call_impl(callable, dots$args, dots$keywords) : ValueError: name already used as a name or title`

**Comment by flying-sheep** [comment]
That certainly sounds like a bug in seurat or reticulate and not here.

**Comment by flying-sheep** [comment]
We don’t provide any R interop. Seurat does that. so this is a Seurat bug.

**Comment by aopisco** [comment]
thanks for clarifying this!

**Comment by flying-sheep** [comment]
No problem. If the whole thing ends up uncovering anndata/scanpy bugs, of course be free to post them! If you have clearly correct usage causing an error, feel free to file an issue including a stack trace :smiley:

**Comment by falexwolf** [comment]
I can debug anything that gives a python error traceback and I'm happy to do so for the Seurat-AnnData interface. But the above error message tells me nothing... Does it work with a very simple AnnData object? Like the one provided in the Seurat Vignette?

**Comment by aopisco** [comment]
hi @falexwolf 
I'm using this object: https://drive.google.com/open?id=1yETT6XcUixPTREdxNI0unenTRIyqj9m4
