### ISSUE TITLE
improve the exception thrown when a sparse matrix is created as an obsm value

### ISSUE THREAD

**Issue by gokceneraslan** [theislab/anndata#89]
I was thinking about storing binarized gene expression in `obsm` where `adata.X` is sparse. Does it make sense to allow sparse representations in `obsm`? Here is an example where `adata.X` is sparse:

```python
adata.obsm['X_binary'] = (adata.X > 0).astype(int)
```
Right now this fails (unless I convert it to dense array):

![image](https://user-images.githubusercontent.com/1140359/50265253-be37bd80-03ec-11e9-8e89-afbf9312d4cd.png)

(I know it's an anndata issue, but I feel lonely and scared in anndata github page :P )

**Comment by flying-sheep** [comment]
it *is* an anndata ~issue~question :wink:

Isn’t `.layers` there for things like this?

**Comment by gokceneraslan** [comment]
Oh, I always forget about the existence of `.layers`, so true, for binarized expression it makes a lot of sense to use it. However, this doesn't change the fact that sparse matrices are not supported in `.obsm`, and getting a weird `ValueError` exception seems more like an issue to me rather than a question :) 

But anyway, if there is need for it I'm closing the issue. Maybe a better issue would be `improve the exception thrown when a sparse matrix is created as an obsm value`.

**Comment by flying-sheep** [comment]
sure! let’s rename this one then.

**Comment by falexwolf** [comment]
So, in principle, I wouldn't mind that `.obsm` was able to take sparse objects, but it would be a lot of work to make this happen. If we hadn't implemented this as a structured array but rather as a custom collection of `n_obs` sized arrays, it would be easier. But I don't know what the loopholes of this are going to be.

For now, `.layers` should do the job for you. Also, there exists the hack that sparse matrices of size `n_obs x n_obs` are sliced when they are stored in `.uns`.

That being said I wonder what the big advantage of the structured array in the obsm is. But, yeah, it would be quite a big change, also on the backing file side...

And yes, a nicer error message would be cool. 🙂
