### ISSUE TITLE
Subtracting cells from anndata

### ISSUE THREAD

**Issue by bioguy2018** [theislab/anndata#90]
Dear developers,
I am interested in subtracting cells in the pre-processing step that contains a specific gene expression and do my analysis only on that subset.
I managed to identify these cells by simply using adata[:,adata.var_names.str.match('mygene') ] but I have problem in obtaining those cells because through this method I get them only with that gene which is not my intention.
I also tried the following approches:
adata[adata.obs.where(adata.var_names=="mygene"),:]
but it was not that simple as I thought
Can you please suggest me some ideas as I am new to pandas like data frames such anndata
Thanks

**Comment by falexwolf** [comment]
You can always remove cells using something like
```
adata_subset = adata[adata[:, 'mygene'].X > 2]
```
which will subset to those cells that have expression of 'mygene' greater than 2.
