### ISSUE TITLE
Cannot re-open a h5ad file opened in backed = 'r+' mode

### ISSUE THREAD

**Issue by bli25broad** [theislab/anndata#92]
Hi, 

I tried the following:

```py
adata = anndata.read_h5ad('test.h5ad', backed = 'r+')
adata.write('test.h5ad')
adata = anndata.read_h5ad('test.h5ad')
```

And encountered the following error:

> Can't broadcast (911, 22385) -> (912, 22385)

It seems that for some reason, one more cell was added to the h5ad ...

Any suggestions?

**Comment by Koncopd** [comment]
Hi, yes, this problem should be fixed now.
If you install anndata from github, it should work fine.

**Comment by bli25broad** [comment]
Thanks! 

Do you know when you will update PIP for the fix?

Thanks,
Bo

**Comment by falexwolf** [comment]
@Koncopd: could you reference a commit? I don't see anything here: https://github.com/theislab/anndata/commits/master

@bli25broad, we can immediately make a release, no problem. Sorry about the bug and keen to see what it was about.

**Comment by Koncopd** [comment]
Hi, @falexwolf 
It is https://github.com/theislab/anndata/commit/b081deafa400c43d9aac90ac49ec828173755cfb

**Comment by falexwolf** [comment]
But why would the above error have anything to do with  `_chunked_rows`? Is, meanwhile,  `anndata.read_h5ad` working via `_chunked_rows`?

**Comment by Koncopd** [comment]
Yes, for sparse datasets that are stored as dense.

**Comment by falexwolf** [comment]
@Koncopd: can you make a small test for this combination of parameters? We have read write tests also in backed mode but this seems not have been tested. As it's likely subject to change in the future a test would be super important. Thank you!

**Comment by Koncopd** [comment]
I will.

**Comment by flying-sheep** [comment]
> Got it! @flying-sheep, can we make a new release?

I’m pretty sure I made no experimental changes. But I’ll fix the docs badge before we move on.

**Comment by Koncopd** [comment]
added test and the option to set chunk_size.
https://github.com/theislab/anndata/pull/95

**Comment by falexwolf** [comment]
Thank you! :smile:

**Comment by falexwolf** [comment]
@flying-sheep Yes, agreed! I'll make a new release now.

**Comment by falexwolf** [comment]
anndata 0.6.17 with the fix is out now on PyPI.

**Comment by bli25broad** [comment]
@falexwolf  Thanks!
